### ISSUE TITLE
Occasional assert failed on macOS with 0.9.3.x

### ISSUE THREAD

**Issue by edoardocomar** [edenhill/librdkafka#1000]
Description
===========
```
Assertion failed: (r == 0), function rwlock_wrlock, file ../deps/librdkafka/src/tinycthread.c, line 1000.
```
happens occasionally on macOS with `librdkafka` > 0.9.3.x

How to reproduce
================
running the entire e2e suite of https://github.com/Blizzard/node-rdkafka 
with its librdkafka submodule pointing at current head of 0.9.3.x
https://github.com/edenhill/librdkafka/commit/81a673da0d1ed457d8c19dd5896651ffd178289d

NOTE - does NOT seem to happen with current HEAD master
https://github.com/edenhill/librdkafka/commit/c73d2bbaf6a4c15ea9d196ae1f9d79e448e119e6

Checklist
=========
Please provide the following information:

 - [ ] librdkafka version (release number or git tag):
81a673da0d1ed457d8c19dd5896651ffd178289d
 - [ ] Apache Kafka version: 
0.10.1.1
 - [ ] librdkafka client configuration:
defaults
 - [ ] Operating system:
macOS
 - [ ] Using the legacy Consumer
 - [ ] Using the high-level KafkaConsumer
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by DapperTayra** [comment]
I see "Assertion failed: (r == 0), function rwlock_wrlock, file tinycthread.c, line 1000." too. 
Whenever a consumer is destroyed. Both with 0.9.2 and 0.9.3, on macOS 10.12.3.

**Comment by edenhill** [comment]
@DapperTayra Is this reproducible with one of the examples/ tools or a short snippet? I have not been able to

**Comment by edenhill** [comment]
Is this happening frequently?

**Comment by DapperTayra** [comment]
Sorry, we were not able to extract a snippet from our code to reproduce it with. Happens every time that we start our software on macOS, deterministically. On then linux platform, I personally haven't witnessed this behaviour yet, and that is what we normally develop for.

**Comment by edenhill** [comment]
Every time? Interesting. What osx version are you on?

**Comment by DapperTayra** [comment]
We are on macOS 10.12.3.

**Comment by edoardocomar** [comment]
Hi @edenhill I just rerun all node-librdkafka e2e tests 4 times after rebuilding it on `librdkafka`  released 0.9.3.x and it never occurred, I am not worried about this issue any longer.

**Comment by edoardocomar** [comment]
and BTW I didn't get the assert failure even by pointing to the current master (though node-librdkafka will need to be updated for all tests to pass).

I am happy for you to close this issue

**Comment by edenhill** [comment]
Okay, thanks everyone, closing as fixed.
0.9.4 will be released shortly.

**Comment by austinheap** [comment]
Was a root cause ever figured out for this by chance? I'm getting the same error on the latest version of macOS Sierra (10.12.5) with librdkafka v0.9.5.

**Comment by scav** [comment]
Seeing the same issue here. macOS 10.12.5 and 0.9.5 as well, getting line 1011 now as well.

**Comment by edenhill** [comment]
@austinheap @scav 

 * Is this reproducible with any of the librdkafka example tools?
 * Steps to reproduce?
 * Can you provide the full backtrace from a crash (in gdb: `bt full`)

Thanks

**Comment by austinheap** [comment]
Hey @edenhill, thanks for the quick response and all your work on this project. When I run the test suite in sequential mode, it eventually fails with the following:

```
[<MAIN>                      /125.433s] ALL-TESTS: duration 125432.977ms
[<MAIN>                      /125.433s] 24 thread(s) in use by librdkafka, waiting...
[<MAIN>                      /126.433s] 24 thread(s) in use by librdkafka
[<MAIN>                      /126.433s] TEST FAILURE
### Test "<MAIN>" failed at test.c:591:test_wait_exit(): ###
24 thread(s) still active in librdkafka
### Test random seed was 2114777428 ###
Assertion failed: (0), function test_wait_exit, file test.c, line 591.
./run-test.sh: line 58: 34214 Abort trap: 6           $TEST $ARGS
make: *** [run_par] Error 1
```

I'll try running the example tools, extracting a repro from our code, and get you the `bt full` by this weekend. Thanks!

**Comment by edenhill** [comment]
Thanks.

That snippet is not the actual failure, you should look for an earlier FAIL printout.
The assert in the snippet is the test harness crashing to provide a core-file to diagnose, but the actual error has already occurred earlier, and since the original issue here was an assert inside librdkafka I don't believe this to be the same issue.

**Comment by edenhill** [comment]
Are people still seeing this with v0.9.5 or master?

**Comment by edoardocomar** [comment]
I've rerun a few times the node e2e suite, using both librdkafka 0.95 and master and haven't seen the assertion

**Comment by edenhill** [comment]
Thank you @edoardocomar, I'll close this then. Reopen if you see it reoccurring.

**Comment by AlexeyRaga** [comment]
@edenhill I can reproduce this issue consistently when calling `rd_kafka_assignment`.
I am getting `Assertion failed: (r == 0), function rwlock_wrlock, file tinycthread.c, line 1011.` every time.

An interesting fact is that if I call `rd_kafka_subscription` instead, then this failure doesn't happen.
Since changing from `rd_kafka_assignment` to `rd_kafka_subscription` is the only change I have to make (both functions have the same signatures), I suspect that the issue is not in my code, but somewhere in `librdkafka`.

I could only reproduce it on MacOS (I use 10.12.5), but it is 100% reproducible.
Linux build doesn't have this problem.

Please reopen if you think that it is the same issue, or let me know if I need to fail another one.

**Comment by edenhill** [comment]
@AlexeyRaga Great! Do you have an example program to reproduce this?

**Comment by AlexeyRaga** [comment]
@edenhill I am using `1f7417d4796e036b8c19f17373f8290ff5c7561f` version of `librdkafka` which is `master` at the time of writing.

I have code and test to reproduce it, but it is in Haskell so I don't know how much use it has for you.
Basically both `assignment` and `subscription` functions have exactly the same Haskell treatment (because they have the same signatures):

**assignment**:
https://github.com/AlexeyRaga/hw-kafka-client/blob/assignment/src/Kafka/Internal/RdKafka.chs#L528

**subscription**:
https://github.com/AlexeyRaga/hw-kafka-client/blob/assignment/src/Kafka/Internal/RdKafka.chs#L495

Their Haskell wrappers are here:
https://github.com/AlexeyRaga/hw-kafka-client/blob/assignment/src/Kafka/Consumer.hs#L128-L138

And the unit test that consistently fails in MacOS is this one:
https://github.com/AlexeyRaga/hw-kafka-client/blob/assignment/tests/Kafka/IntegrationSpec.hs#L60

I don't know enough C to make a "native C" example

**Comment by edenhill** [comment]
Is this reproducible on 0.11.3?
If so, can you provide a docker-image that reproduces this with your Haskell thing?

**Comment by AlexeyRaga** [comment]
@edenhill I will check against 0.11.3 and will let you know. Give me a couple of days.

**Comment by AlexeyRaga** [comment]
Actually I cannot reproduce it with 0.11.3 or with `master` of `librdkafka`.
Thanks for the attention!

**Comment by thijsc** [comment]
I'm seeing this happen regularly on OSX with 0.11.4. Happens almost every time I run the test suite for https://github.com/appsignal/rdkafka-ruby

Since it's OSX I'm not sure how to provide something reproducible.

**Comment by thijsc** [comment]
It consistently happens in this test: https://github.com/appsignal/rdkafka-ruby/pull/31/files#diff-7620e14e1e30379dc45300478247a66eR228

**Comment by edenhill** [comment]
Can you provide instructions for how to reproduce it with rdkafka-ruby on osx?

**Comment by thijsc** [comment]
Use the `store_offset` branch. Make sure you're running Ruby 2.1 or higher. Then run:

```
bundle
cd ext && bundle exec rake && cd ..
bundle exec rake create_topics
```

The following command runs the test. I get the assertion failure every time I run this:

```
➜  rdkafka-ruby git:(store_offset) bundle exec rspec spec/rdkafka/consumer_spec.rb:227
Run options: include {:locations=>{"./spec/rdkafka/consumer_spec.rb"=>[227]}}

Rdkafka::Consumer
  #commit, #committed and #store_offset
    with enable.auto.offset.store set to false
      #store_offset
Assertion failed: (r == 0), function rwlock_rdlock, file tinycthread.c, line 1013.
[1]    72314 abort      bundle exec rspec spec/rdkafka/consumer_spec.rb:227
```

This is a new feature I'm working on, so maybe I messed something up in the integration. I have seen the failure intermittently in other working parts of the gem too.

**Comment by edenhill** [comment]
Reprod, thank you!

Is it possible to use the system installed librdkafka instead of the one that is download and built by bundle?

**Comment by thijsc** [comment]
I think you can achieve that by changing this line: https://github.com/appsignal/rdkafka-ruby/blob/master/lib/rdkafka/bindings.rb#L17

To:

```ruby
ffi_lib 'librdkafka'
```

**Comment by edenhill** [comment]
It looks like the topic rkt you are passing to rd_kafka_offset_store() has been destroyed (refcnt 0), probably due to bad reference handling.
Check your code and make sure you the number of topic_new() and topic_destroy() are symetrical and that you don't use an rkt after topic_destroy()

**Comment by edenhill** [comment]
I dont believe that is possible since the `rkt` has been freed, we're just lucky it hits an assertion and not crashes on invalid memory access.

**Comment by thijsc** [comment]
Ah right. Well I guess in a sense that would have been more informative :-). I will debug this and see if I can add some checks on this.

**Comment by AlexeyRaga** [comment]
Funny enough I have got the  same `Assertion failed: (r == 0), function rwlock_rdlock, file tinycthread.c` on MacOS using `rd_kafka_offset_store` in my Haskell bindings.
Turns out that _not_ destroying after `rd_kafka_topic_partition_list_new` in this case helped with the error.
I don't know  why, everywhere else I  destroy it  after calling  to `librdkafka`, including when committing offsets, and  semantics look similar.
But it looks  like that for storing offsets I must not destroy the list.

**Comment by thijsc** [comment]
Interesting. I do test the various ways of storing an offset here, so seems related.

**Comment by edenhill** [comment]
You need to destroy those lists when you're done with them.

**Comment by AlexeyRaga** [comment]
Good! Then there must be a bug in `store_offsets` because if I destroy the list on MacOS then it errors out with that `Assertion failed: (r == 0)` at the time when I try to destroy the consumer.

**Comment by edenhill** [comment]
@AlexeyRaga If you could provide a minimal reproducible test case and instructions how to run it I'll dig further

**Comment by edenhill** [comment]
I don't know how to run the Haskell code, so I will need thorough instructions.

I'm suspecting the Haskell bindings have the same problems as the Ruby ones;  rd_kafka_topic_t being destroyed prematurely due to invalid reference handling.

**Comment by thijsc** [comment]
I actually don't use `rd_kafka_topic_t` at all in the code, except for in one test here:

https://github.com/appsignal/rdkafka-ruby/blob/master/spec/rdkafka/consumer/message_spec.rb

If you run the tests scoped on file as above this whole code will never be run. Also it doesn't clean up at all.

**Comment by edenhill** [comment]
Can you try running the application with valgrind, it should say where the topic is being destroyed

**Comment by thijsc** [comment]
Sorry not super familiar with using valgrind, which options do you use for that?

**Comment by edenhill** [comment]
`valgrind ./your-program program-args ..`  should be sufficient

**Comment by edenhill** [comment]
Look at any place where your code handles rd_kafka_topic_t instances, for example double freeing a message_t object.

**Comment by thijsc** [comment]
Right, so you also mean topics that are created by proxy. Which types could do that?

**Comment by edenhill** [comment]
Any pointer type, or public struct that contains pointer types, must not be destroyed multiple times.
E.g., message_t, topic_partition_t, ..

**Comment by thijsc** [comment]
Ok, will do a review again. Why would this then only fail on OSX? Shouldn't it crash or something like that on Linux too? This test suite on Linux with Travis is doing fine.

**Comment by edenhill** [comment]
Accessing freed memory is undefined behaviour.

**Comment by thijsc** [comment]
I agree with you on that :-). But still you'd expect some crash or something somewhere if you run the test suite a 100 times no?

**Comment by thijsc** [comment]
I did a review of all the locations where native things are being destroyed. So far I cannot identify any double destroy. In most cases the destroy is called by an auto pointer, that will destroy the underlying native objects once the Ruby object is garbage collected.

So at this moment I don't see how a double destroy could cause this assertion error.

**Comment by thijsc** [comment]
After commenting everything I isolated it to one specific pointer destroy. Seems like the `ffi` gem is doing something I'm not expecting there. It might be a double free after all.

**Comment by thijsc** [comment]
I'm still struggling to understand what's going on here. Tried various hooks to clean the topic partition list. I can only avoid this issue by not cleaning it at all.

Looking at the order of things I see that the topic partition list is fully functional during the duration of the program. That seems to imply it's not cleaned too soon. Is there any chance this 

To me it still seems I am lacking knowledge on the proper pattern on how to pass in a pointer to a pointer as the rdkafka API requires.

**Comment by edenhill** [comment]
The termination sequence is rather straight forward: https://github.com/edenhill/librdkafka/wiki/Proper-termination-sequence

Make sure to destroy any object that was retrieved from an rd_kafka_t instance before the rd_kafka_t instance is destroyed.

**Comment by thijsc** [comment]
So you’re saying that terminating in the wrong order could cause this as well? Or does your earlier advice on checking double frees still apply too?

**Comment by edenhill** [comment]
I'm not sure what is going on, but using an rdkafka related object after the corresponding rd_kafka_t instance has been destroyed will definitely lead to problems.

Double free could also be an issue.

**Comment by thijsc** [comment]
This did turn out to be caused by termination order. I decided to just copy all the topic partition lists content into Ruby objects. The return tpl's are destroyed immediately now. That fixes all the issues.

If anybody finds this who's working on another language integration: When integrating this library with a garbage collected language you can save yourself a lot of hassle by just copying and destroying everything. With a GC it's too hard to make sure that the termination order is correct.

**Comment by thijsc** [comment]
I just ran into this error again in a completely different situation. It happens whenever I call `rd_kafka_offset_store` with a pointer/partition/offset I know to be correct in 0.11.5. It's being run in tests here: https://github.com/appsignal/rdkafka-ruby/pull/31/files#diff-7620e14e1e30379dc45300478247a66eR229

On thing I noticed is that the assertion fails immediately, as opposed to randomly a while later when GC happens to run. What could be causing this?

**Comment by edenhill** [comment]
It is hard for me to know what is going on inside the ruby client.
I suggest you add some debug code to track the destruction of all topic_t, topic_partition_list_t, rd_kafka_message_t objects that are being handled by the ruby client, might be as simple as printing the pointer when you call destroy, e.g.: `"Destroy topic_t %p\n"`.
Also do the same thing for acquisition of these objects (since pointers can be reused for a new object).

This allows you to visually inspect the lifetime of objects and check if they're being used in post-mortemly in various APIs, such as store_offsets.

**Comment by thijsc** [comment]
This doesn't seem to be caused by termination. Completely disabling the destroy of the client does not fix it. Also I can call `commit` right before and that's fine. It looks to me like something else, not sure what it could be.

**Comment by thijsc** [comment]
What's also different is that the assert failure happens immediately 100% of the time, instead of most of the time a bit later.

**Comment by thijsc** [comment]
Nevermind, that last one was an unrelated user error.

**Comment by edenhill** [comment]
most likely high-level binding issue, closing.
