### ISSUE TITLE
When does the rebalance callback see the error RD_KAFKA_RESP_ERR__REVOKE_PARTITIONS, Can someone please give an example?

### ISSUE THREAD

**Issue by archanapujar** [edenhill/librdkafka#1026]

**Comment by edenhill** [comment]
rebalance_cb(REVOKE_PARTITIONS, partitions) is triggered when the client's current assignment is revoked due to group rebalance, unsubscribe(), group timeout or termination.
It is the application's responsibility to call assign() with NULL partitions to stop consuming and synchronize state with the internal partition fetcher.
