### ISSUE TITLE
rd_kafka_consume_batch blocks forever

### ISSUE THREAD

**Issue by sathibault** [edenhill/librdkafka#1035]
Description
===========

I'm calling rd_kafka_consume_batch in a loop with timeout parameter of 500.  It runs for days and then just hangs.  The call to rd_kafka_consume_batch never returns.  Any ideas what might cause this?

Checklist
=========
Please provide the following information:

 - [x] librdkafka version (release number or git tag): 0.8.3
 - [x] Apache Kafka version: 0.8.2.1
 - [ ] librdkafka client configuration:
 - [x] Operating system: Ubuntu 14.04
 - [x] Using the legacy Consumer
 - [ ] Using the high-level KafkaConsumer
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
Ooh, librdkafka 0.8.3 is 3 years old, there's been an enormous number of changes since then.
I suggest you upgrade to the latest release, 0.9.3, and see if the issue has been fixed.

You might also want to look into the new high-level consumer that was added in 0.9,
have a look at rd_kafka_subscribe() with friends.
