### ISSUE TITLE
Update Debian packages to v0.9.4

### ISSUE THREAD

**Issue by mcandre** [edenhill/librdkafka#1048]
Please help the Debian (sid) contributors update their librdkafka, so that Debian users can enjoy improvements in Kafka stuff.

**Comment by edenhill** [comment]
Debian packages are no longer maintained within this repo but from a Debian Kafka package team at https://alioth.debian.org/projects/pkg-kafka/

**Comment by ctrochalakis** [comment]
@mcandre You can add the packaging repo as a second remote on top of librdkafka (https://anonscm.debian.org/cgit/pkg-kafka/librdkafka.git).

When 0.9.4 is out we will upload it to `experimental` (since Debian is currently freezed for `stretch`) and eventually once `stretch` is released, the package will end up to `stretch-backports`.
