### ISSUE TITLE
What does MSG_TIMED_OUT mean?

### ISSUE THREAD

**Issue by johnrgregg3** [edenhill/librdkafka#1066]
Description
===========

I am running librdkafka 0.9.1, in the python confluent client over ubuntu. I am a kafka producer. Sometimes in my on_delivery callback, I get an error MSG_TIMED_OUT. Does this mean that the local kafka producer failed to send a message to the broker cluster? If so, does this mean that the underlying library will now give up and delete the message, so it is effectively lost? Under what circumstances might I see MSG_TIMED_OUT? Would it usually (or always) correspond to an ALL_BROKERS_DOWN condition? It seems that I also get an awful lot of TRANSPORT errors as well, but I don't have any detail about why.

How to reproduce
================

Checklist
=========
Please provide the following information:

 - [x] librdkafka version (release number or git tag): 0.9.1
 - [ ] Apache Kafka version: 
 - [ ] librdkafka client configuration:
 - [x] Operating system: Ubuntu
 - [ ] Using the legacy Consumer
 - [ ] Using the high-level KafkaConsumer
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
Your delivery report handler will be called exactly once per message, either:
 1. when message has been succesfully delivered to broker (no error)
 2. when librdkafka eventually gives up trying to send the message, constrained by timeouts, retries, etc. (error is set)
 3. when broker directly or indirectly permanently rejects the message, e.g. non-existent topic, insufficient replicas, etc. (error is set)

Thus, when you get the delivery handler you can be sure that librdkafka will not do anything more to that message and it is back in your application's control.
This also means that no message is ever lost: it is either succesfully produced, or returned to the application on failure.

The MSG_TIMED_OUT (which in later version was changed to TIMED_OUT_QUEUE) indicates number 2.
You will not see TRANSPORT errors returned in delivery handlers because those type of intermittent errors are abstracted by the retry-until-timeout funcionality.

**Comment by johnrgregg3** [comment]
So what might cause MSG_TIMED_OUT? Network connectivity to the broker or lack thereof? If that were the case, I would get an ALL_BROKERS_DOWN error in my error_cb, right?
And a non-existent topic would not be a problem if the broker were configured to autocreate an unrecognized topic that someone produces to, right?

**Comment by edenhill** [comment]
Yes, your assumptions are right.

So MSG_TIMED_OUT abstracts a wider range of actual errors all boiling down to the fact that the producer is unable to succesfully produce the message the broker.
The cause is typically that the leader for the given partition is not available, either because leader election failed in the cluster (e.g. no eligible replicas available), or the connection to the presumed leader cannot be made (e.g., networking problems, broker is actually down, etc.)

**Comment by johnrgregg3** [comment]
I'm trying to get clear on an actual sequence of events that could lead to multiple TRANSPORT errors followed by a MSG_TIMED_OUT, without an ALL_BROKERS_DOWN. You mentioned leader election failing. Does this mean the brokers in a cluster were able to talk to each other at first, but then one dropped out? Or that maybe one was elected leader, then it died? In that case, however, wouldn't the remaining brokers in the cluster elect a new leader, and the client would more or less automatically start using the new leader? Or could this happen if there were three brokers configured to be in the cluster, but only one or two of them ever came up at all? But even in that case, wouldn't kafka do its best, and still the client would be able to publish?

**Comment by edenhill** [comment]
Your assumptions are correct again (you're getting good at this Kafka thing!).

> Or could this happen if there were three brokers configured to be in the cluster, but only one or two of them ever came up at all? But even in that case, wouldn't kafka do its best, and still the client would be able to publish?

If there is no in-sync replace (ISR) a new leader will not be elected, unless you set `unclean.leader.election.enable` on the broker.
See here for more info:
http://kafka.apache.org/documentation.html#topic-config
http://kafka.apache.org/documentation.html#design_replicatedlog

**Comment by johnrgregg3** [comment]
Well, I think I have ISRs OK, although now I'm beginning to doubt my whole setup. I _think_ I have three brokers acting as a cluster. However, I only have default.replication.factor of 1. On each broker, if I do this:

kafka-topics.sh --describe --zookeeper <all three IP addresses of the brokers, comma-separated>

I get a listing of all partitions of all topics. For each, it tells me the leader, the replicas, and the ISR. However, these are not identified by IP address, but by a number [1,2,3]. I would expect all the numbers to agree on each, but they do not. That is, on broker1, topicA, partition 13 might say leader=3, replicas=3, isr=3, but on broker2, topicA, partition 13 might say leader=1, replicas=1, isr=1. Is it the case that maybe my brokers aren't really cooperating as a single cluster after all? Does this sound sane?

I realize now that it was probably a mistake (although not one I can fix soon) to make my replication factor 1. Might that be a cause or a contributing factor for my TRANSPORT/MSG_TIMED_OUT errors? If there is only one replica, i.e. the leader himself, and he is momentarily down, the producer won't be able to produce to the topic/partition, and he will get a TRANSPORT/MSG_TIMED_OUT, but because the other brokers are up and running, even though the producer can't produce to them on the topic/partition, it also won't ever get an ALL_BROKERS_DOWN message, as long as there is some connectivity to at least one of them. So it's a perverse case for the producer: some brokers are up, but the only one I can make use of is down.

Does this sound plausible?

**Comment by johnrgregg3** [comment]
I think my zookeeper and/or kafka configuration on the broker cluster was messed up, but I have a simple question, referring back to the title of this issue. What timeout does MSG_TIMED_OUT refer to? Is it message.timeout.ms or socket.timeout.ms? Which one should I increase to try to work around this?

**Comment by edenhill** [comment]
message.timeout.ms

**Comment by johnrgregg3** [comment]
And if I'm reading correctly, it defaults to 300000, i.e. 5 minutes?

**Comment by edenhill** [comment]
yes sir

**Comment by edenhill** [comment]
Hey John, did you get the answers you needed? Can I close this?

**Comment by johnrgregg3** [comment]
I still have investigations to do on my end, but you have answered everything I asked, at length and clearly. Thank you.
