### ISSUE TITLE
Differences with Java API probably leading to lower performance (C++?)

### ISSUE THREAD

**Issue by concav** [edenhill/librdkafka#1093]
Description
===========
Comparing single consumer performance Java versus CPP API showed CPP consumer achieving at best ~43% and in many cases <40% of  Java consumer throughput. Among several factors potentially contributing to this difference is the MO of the consume/poll methods. With the CPP API each call to consume/poll returns a *single record*. With the Java API each call to poll returns a map of *all unconsumed records* for each subscribed topic. In cases where records are produced in bursts of many, the CPP consumption approach results in numerous consume/poll calls (as many as there are records) whereas that Java approach can get away with substantially fewer calls (as few as one per production burst). Among other possible efficiencies this approach likely cuts down substantially on the amount of mutex locking that has to be done to access the records. Are there any thoughts about doing something similarly efficient for CPP?

Checklist
=========
Please provide the following information:

 - [x] librdkafka version (release number or git tag):0.9.1
 - [x] Apache Kafka version:2.11-0.10.1.0 
 - [ ] librdkafka client configuration:
 - [x] Operating system:Ubuntu 16.04.2 LTS
 - [ ] Using the legacy Consumer
 - [x] Using the high-level KafkaConsumer
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
Ouch, those numbers look horrible.
Can you provide some feedback on how you tested this?
Number of brokers, number of topics & partitions consumed, message sizes, prepopulated topics or actively produced, etc, etc..?


Your API points are correct, each librdkafka consume() or poll() call will require one mutex lock cycle per message.
However, grabbing an uncontended mutex (which the message queue mutexes are thanks to the batching nature of the writing side) is a very cheap operation, so I'm not sure this would be the cause of the performance issues you are seeing.

Having said that, I do agree that a more batch-like API does make sense, and there's been one in librdkafka for years (consume_batch() as well as consume_callback()) for the legacy consumer.
They haven't made their way into the high-level consumer yet though, mainly due to very low demand for such functionality.

But I would be happy to add such APIs if there is an actual benefit to them, but this needs to be measured and verified first.

Related:
As it currently stands the consumer fetches batches (messagesets) of messages from the consumer, splits them up into individual messages and enqueues each individual message on the consumer queue. This approach makes a lot of stuff easier downstream since there is no intra-message coupling - e.g., how do you stop reading in the middle of a batch, etc.
But I've been thinking of providing a run mode (through configuration) where the batch integrity is contained all the way to the application, which would also cut down on the number of allocations (fewer per message), queue entries, mutex grabs, etc.
This mode would probably make use of the new rd_kafka_event_t API and accessors such as rd_kafka_event_message_next() and rd_kafka_event_message_array().

This approach comes at the price of increased complexity on the application side though.

**Comment by concav** [comment]
Thank you for your detailed reply, much appreciated. The test setup was as follows: cluster of 3 brokers with 8 GB each, 1 topic with 1 partition and 1 replica, pre-populated prior to being consumed by a single consumer, message size in the range 50-3000 bytes with a separate test run for each size.  I also need to correct the performance numbers I quoted earlier, I made a mistake, my apologies. The correct numbers are: for message size ~100B CPP consumer throughput is 78% of Java, for ~230B 62%, for ~800B 53%. Part of this performance difference can be attributed to the efficiency of Java vs CPP avro serialization/deserialization. However, one thing the leads me to believe that single-record retrieval is inefficient is that callgrind profiling of the CPP API is showing ~1,430 mutex operations per record.

**Comment by edenhill** [comment]
So your app is using avro-cpp to deserialize messages?
Could you try to run it without Avro to see what numbers you get?
1430 mutex operations per record sounds an awful lot, I would think it should be closer to a handful or two.

**Comment by concav** [comment]
Yes, have tried a simpler test without avro on a batch of 100 records averaging around 100B size. The Java consumer retrieves (and lightly processes) all 100 in less that 2 ms, whereas the CPP consumer takes ~1.25 seconds. These durations exclude startup/initialization and are measured starting from the first consume/poll call until all records are consumed. Agreed that 1430 mutex ops per record is boggling but judging by this simple test the number is likely to be correct.

**Comment by edenhill** [comment]
Do you get the same poor performance using the examples/rdkafka_performance tool?

**Comment by concav** [comment]
Have not tried this tool yet.

**Comment by edenhill** [comment]
There are two modes, low-level consumer consuming one partition, or high-level producer subscribing to one or more topics.

low-level:
`rdkafka_performance -b <brokers> -C -t <topic> -p <partition> -o beginning -e`

high-level:
`rdkafka_performance -b <brokers> -G <uniquegroupid> -t <topic> -o beginning -e`

It is probably a good idea to run it a couple of times to prime the broker disk caches.

**Comment by concav** [comment]
Thank you, will do.

**Comment by edenhill** [comment]
@concav any luck?

**Comment by concav** [comment]
Sorry for the slow response - busy times. examples/rdkafka_performance reported much better consumer performance than my test (both in high-level mode). The difference between the two tests is that the former uses the C API while the latter uses the C++ API. Going deeper, the latter wraps each received message pointer in a MessageImpl object (rdkafkacpp_int.h). So one f these is created/allocated and initialized (uses memset in constructor) upon every reception. Moreover, several of MessageImpl's methods use static_cast<>, which also results in creation/allocation of new memory constructs. The key() method also spawns an fresh std::string object, which involves copying in addition to allocation. When profiling my test with callgrind I did see tons of memcopy, malloc and other heap operations. One must know to use key_pointer() instead of key() and/or to directly access the underlying *rkmessage_ to skip all this, but cannot avoid the MessageImpl allocation/initialization performance penalty. These appear to be the main reasons for the poor performance I saw with CPP high-level consumer.

**Comment by edenhill** [comment]
Interesting.
I guess this warrants writing an rdkafka_performance counterpart in C++

**Comment by concav** [comment]
Yes, that would be useful too.

**Comment by WZRPW** [comment]
> Interesting. I guess this warrants writing an rdkafka_performance counterpart in C++

hello, wonder if you've got a chance to write a performance test in C++?
Looks like rd_consume_batch() does not have the C++ version or equivalent.

**Comment by WZRPW** [comment]
> Sorry for the slow response - busy times. examples/rdkafka_performance reported much better consumer performance than my test (both in high-level mode). The difference between the two tests is that the former uses the C API while the latter uses the C++ API. Going deeper, the latter wraps each received message pointer in a MessageImpl object (rdkafkacpp_int.h). So one f these is created/allocated and initialized (uses memset in constructor) upon every reception. Moreover, several of MessageImpl's methods use static_cast<>, which also results in creation/allocation of new memory constructs. The key() method also spawns an fresh std::string object, which involves copying in addition to allocation. When profiling my test with callgrind I did see tons of memcopy, malloc and other heap operations. One must know to use key_pointer() instead of key() and/or to directly access the underlying *rkmessage_ to skip all this, but cannot avoid the MessageImpl allocation/initialization performance penalty. These appear to be the main reasons for the poor performance I saw with CPP high-level consumer.

I wonder if you still remember the performance improvement (%) switching from simple-consumption to the performed way?
