### ISSUE TITLE
Add producing batched messages

### ISSUE THREAD

**Issue by Gvain** [edenhill/librdkafka#112]
To improve throughput, i think we should add producing batched messages as rd_kafka_consume_batch() do.
And also producing batched messages is supported by JAVA API.

**Comment by kparadkar** [comment]
Do you have any performance numbers on use of rd_kafka_produce_batch vs rd_kafka_produce? Does it give significant increment in the throughput?

**Comment by edenhill** [comment]
@kparadkar Expirements have shown that there isn't typically much to gain from using the produce_batch() API.
The improvements it provides over the standard produce() API is mainly when you are producing a large number of messages to the same partition since it will cut down on the number of lock acquisitions from one per message to one per batch.

But, as is always the case with performance measurements, you will need to do your own using your own environment and usage.

**Comment by archanapujar** [comment]
How does rd_kafka_produce_batch() handle NULL topic handle. Will it error out with something like EINVAL?

**Comment by edenhill** [comment]
@archanapujar NULL topic handle is not supported and the produce_batch() call will crash.
It is up to the application to provide valid function arguments.

**Comment by archanapujar** [comment]
@edenhill Thanks for the quick response! Does this behavior hold good for all the supported apis?

**Comment by edenhill** [comment]
Generally yes
