### ISSUE TITLE
After rebalance, KafkaConsumer waits for commit indefinitely until next rebalance event.

### ISSUE THREAD

**Issue by webmakersteve** [edenhill/librdkafka#1142]
Description
===========
We have two processes that run two C++ KafkaConsumers. Each of these consumers has a separate `client_id`. Each process has a `groupa` and `groupb`. We have auto commits disabled, as we manage them ourselves. 

When shutting down one process, the other process rebalances. On occasion (every 10 seconds), the process commits the offsets for each topic partition that have been marked as processed. The commit method being used is `commitSync`. 

The consumer will stop fetching data (we enabled debug logging for consumer groups, topics, and fetches to ensure fetches were not going out) even though consume was getting called constantly with a 1 second timeout. The logs showed the following at some point during the rebalance:

```
[thrd:main]: Group \"telem-processor-es-debug-b-general-server\": not starting
fetchers for 89 assigned partition(s) in join-state assigned (usable_offsets=no,
v6, line 2206): waiting for 1 commit(s)
```

After restarting another service that had a consumer in the group, the next rebalance would often times get the service responsive again, but it would be stuck until that point.

When we stopped managing commits ourselves and instead used auto commit, the issue disappeared. 

How to reproduce
================
See above. Do not currently have an isolated test case but would be happy to help.

Checklist
=========
Please provide the following information:

 - [x] librdkafka version (release number or git tag): 0.9.4
 - [x] Apache Kafka version: 0.9
 - [x] librdkafka client configuration:
`enable.auto.commit: false`
 - [ ] Operating system: CentOS
 - [x] Using the high-level KafkaConsumer
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka

[thrd:main]: Group \"group\": not starting fetchers for 89 assigned partition(s) in join-state assigned (usable_offsets=no, v6, line 2206): waiting for 1 commit(s)

 - [ ] Provide broker log excerpts
 - [x] Critical issue

**Comment by webmakersteve** [comment]
It looks like this is the relevant code:
https://github.com/edenhill/librdkafka/blob/master/src/rdkafka_cgrp.c#L1551-L1565

**Comment by InfinitiesLoop** [comment]
Relevant commit:
https://github.com/edenhill/librdkafka/commit/474718752832ed1deca1b861c3ded39ee9e8aeda

**Comment by edenhill** [comment]
@InfinitiesLoop Did you get the sha from bisection or reading the code? :)

**Comment by webmakersteve** [comment]
We looked for the log line in the code and then used git blame to get the sha where that block was introduced. Hope that helps

**Comment by InfinitiesLoop** [comment]
Right, what @webmakersteve said. It would be difficult to do a bisect as it requires a complex set up. We think the issue reproduces with these conditions:

1. Two consumer processes on the same consumer group so you can cause rebalances.
2. Each consumer process reads from two different sets of topics from the same brokers (using the same consumer group).
3. Consumers disable auto commit, and commit once every 5 seconds with commitSync (for all topics).
4. Restart one consumer, causing a rebalance. Consumer B sometimes (very often though) will log that debug line about a pending commit, and forever stop consuming from the topic. The log line is followed by a return statement, which makes it avoid setting up the fetcher for the topic. We tried and failed to understand what would end up causing it to check again after the commit completes. Switching to use commitAsync seemed to have worked around the problem, but for all we know it only made it less likely.

Our processes host multiple instances of node-rdkafka and consume from separate sets of topics from the same brokers. We had 5 separate consumers (using the same consumer group name) in each of the two processors when we noticed it. We were able to reproduce it when we had only 2 consumers in each processor, where the group that stopped reading would alternate from one to another (although sometimes both, too). When we had only one consumer in each processor we couldn't reproduce it after 5 or 6 tries. So perhaps it's related to there being multiple consumers in the same process. We tested a workaround by giving each consumer a different consumer group (since they aren't reading from the same topics anyway), but it had no effect.

I hope all of that is helpful. I wish a simple reproduction test could be provided, but it would be pretty time consuming to try and come up with a test that coordinates all this, so we are hoping all this information leads to an 'ah ha!' moment with you :)

**Comment by webmakersteve** [comment]
I'm not certain, but it looks like using `commitAsync` made the problem happen less, but there is still a chance of such a collision. Will investigate further

**Comment by ronvenna** [comment]
@InfinitiesLoop Were you able to reproduce this issue where each consumer process reads from two different sets of topics from the same broker, however the consumer group id is different?

**Comment by andreycha** [comment]
@webmakersteve this one might fix your issue, keep an eye on the next release: https://github.com/edenhill/librdkafka/pull/1621

**Comment by kstaken** [comment]
We're also seeing this issue. Testing on 0.11.4 still shows it so I don't think #1621 resolves it. We're using node-rdkafka with a single consumer / group / topic per process.

**Comment by ronvenna** [comment]
@kstaken we ended up just going with a completely different client because of this issue.
