### ISSUE TITLE
rd_kafka_conf_set_dr_msg_cb vs rd_kafka_conf_set_error_cb

### ISSUE THREAD

**Issue by davidbirdsong** [edenhill/librdkafka#1143]
This is another clarification request.

I'm attempting a low allocation producer, and so I rely heavily on my message callback specified by: 
`rd_kafka_conf_set_dr_msg_cb` to indicate when librdkafka is done with a  buffer that I loaned it.  I'm seeing cases where my callback specified by`rd_kafka_conf_set_error_cb` for errors like:
```
RROR 2017-03-25T16:04:53.895271Z 14510 spigot.producer      Local: Broker transport failure
%4|1490458555.932|METADATA|rdkafka#producer-1| [thrd:main]: sjc1-b4-20.prod.imgix.com:8092/100: Metadata request failed: Local: Timed out in queue (62885ms)
%4|1490459455.124|METADATA|rdkafka#producer-1| [thrd:main]: sjc1-b3-7.prod.imgix.com:8092/200: Metadata request failed: Local: Timed out in queue (62077ms)
%4|1490459755.376|METADATA|rdkafka#producer-1| [thrd:main]: sjc1-b4-20:8092/bootstrap: Metadata request failed: Local: Timed out in queue (62329ms)
ERROR 2017-03-25T16:40:54.575543Z 14510 spigot.producer      Local: Message timed out
ERROR 2017-03-25T16:40:54.575606Z 14510 spigot.producer      Local: Broker transport failure
%4|1490460055.225|METADATA|rdkafka#producer-1| [thrd:main]: sjc1-b3-7.prod.imgix.com:8092/200: Metadata request failed: Local: Timed out in queue (1999ms)
%4|1490460081.208|METADATA|rdkafka#producer-1| [thrd:main]: sjc1-b3-7.prod.imgix.com:8092/200: Metadata request failed: Local: Timed out in queue (65290ms)
ERROR 2017-03-25T16:41:34.598964Z 14510 spigot.producer      Local: Broker transport failure
ERROR 2017-03-25T16:41:34.599016Z 14510 spigot.producer      Local: Broker transport failure
ERROR 2017-03-25T16:41:34.599036Z 14510 spigot.producer      Local: Broker transport failure
ERROR 2017-03-25T16:41:34.599058Z 14510 spigot.producer      Local: Broker transport failure
ERROR 2017-03-25T16:41:34.599080Z 14510 spigot.producer      Local: Broker transport failure
```

You can see my app logging the errors in addition to librdkafka w/ full access to stderr.

My question is: in the case of errors that fire over the error callback:
- What should I do with the buffers on loan to librdkafka? 
- Should I just run through all buffers on loan and free them?
- Will the message delivery callback fire later after the error callback?

If the notification of a Broker transport error severe enough to supersede any message-level callbacks? If, in my error callback, I run through all buffers on loan and free them, should I be wary of a message callback firing later with a reference to a now-stale buffer?

**Comment by edenhill** [comment]
You will get exactly one dr_msg_cb callback per message produced, allowing you to clean up your per-message resources.
The error_cb works on a higher level and will not report message specific problems, librdkafka will try its best to automatically recover from errors so you typically don't need to take any action on an error_cb, they are mostly informative.

Messages will fail on permanent errors (e.g., topic doesnt exist and can't be created) directly, but for temporary errors (e.g., no current leader for partition) it will try re-producing the message for message.timeout.ms (default 5 minutes). So even if you get an error_cb saying that all brokers went down it will take up to 5 minutes for the actual messages to fail.

Since you get exactly one dr_msg_cb per message accepted by produce() you must NOT free your buffers from error_cb since they are still in use by librdkafka until the dr_msg_cb is triggered.
