### ISSUE TITLE
initialization & connection

### ISSUE THREAD

**Issue by dmitryme** [edenhill/librdkafka#1173]
Hello,
I need to connect to broker by schedule, so I am trying to split work with librdkafka to initialization and connection procedures (initialization at process start, connection by schedule).
And my questions are:
- is it possible?
- on which API call librdkafka makes a connection to broker?

**Comment by edenhill** [comment]
librdkafka will connect to brokers as soon as its given at least (through bootstrap.servers configuration property or brokers_add() API).

There is no way to tell it to temporarily close its broker connections.

Unless your schedule has a short interval (less than a minute?) I suggest you create the rdkafka client instance when you need it and destroy it when done, rather than at process startup.

**Comment by dmitryme** [comment]
Thank you!
