### ISSUE TITLE
Allow SSL configuration to be set by environment variables

### ISSUE THREAD

**Issue by justindowning** [edenhill/librdkafka#1231]
Description
===========
Hello! I wanted to open up a discussion about updating the way SSL configuration is handled. Currently, `ssl.key.location`, `ssl.certificate.location`, `ssl.ca.location` only accept paths to files storing these variables. It would be nice if we could also use environment variables to authenticate to Kafka brokers.

I see two potential solutions:
1. allow the existing parameters to accept the contents via an environment variable _or_ a path to a file containing the contents
2. introduce new parameters (eg: `ssl.key.contents`, etc) that users can set with an environment variable or string of the value needed to create the SSL connection.

How to reproduce
================

N/A

Checklist
=========
Please provide the following information:

 - [ ] librdkafka version (release number or git tag):
 - [x] Apache Kafka version: 0.10.x.x
 - [ ] librdkafka client configuration:
 - [ ] Operating system:
 - [ ] Using the legacy Consumer
 - [ ] Using the high-level KafkaConsumer
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
I dont think librdkafka should read environment variables since that could be considered a security concern for applications that wants to limit the way librdkafka is configured (e.g., through a config file interface).

For providing content rather than file paths to relevant config properties: That'd be possible by defining a new set of properties and using the corresponding openssl APIs for them, but it seems like a pretty narrow  use-case and the workaround is  straight-forward (create temporary files), so will mark this as wontfix for the time being.
