### ISSUE TITLE
Consumer not consuming older messages in kafka topics 

### ISSUE THREAD

**Issue by chetandev** [edenhill/librdkafka#1233]
Description
===========

I ran producer to fill topic with 100 messages , after that  I ran consumer with default settings 
, it did not consume any messages . 
Then i published a fresh message(while the consumer running) , it was consuming fresh messages 

How to reproduce
================

Checklist
=========
Please provide the following information:

 - [0.9.4 ] librdkafka version (release number or git tag):
 - [kafka_2.11-0.10.2.0] Apache Kafka version: 
 - [ ] librdkafka client configuration:
 - [rehl ] Operating system:
 - [ ] Using the legacy Consumer
 - [ ] Using the high-level KafkaConsumer
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by mfontanini** [comment]
You need to configure `auto.offset.reset` (check [CONFIGURATION.md](https://github.com/edenhill/librdkafka/blob/master/CONFIGURATION.md)) to be `smallest` / `earliest` if you want your consumer to start from the first messages in the topic when there's no committed offset for it. Otherwise it will always start from the latest offset in each partition.

**Comment by edenhill** [comment]
What @mfontanini said.
Corresponding FAQ entry: https://github.com/edenhill/librdkafka/wiki/FAQ#why-am-i-not-seeing-any-messages
