### ISSUE TITLE
Batch consume using high-level C consumer

### ISSUE THREAD

**Issue by arnath** [edenhill/librdkafka#1271]
There doesn't seem to be a way to consume a batch of messages using the high-level C consumer. There is the rd_kafka_consume_batch function but this uses the simple consumer. Is there a way to do this or can this be added?

**Comment by edenhill** [comment]
You could perhaps get the same functionality by getting the consumer queue with and then using rd_kafka_consume_batch_queue().

I haven't tried this myself but it could work..
Otherwise I suggest simply iterating with the single message API until you get the batch size you desire, since the messages are already queued internally there is very little difference in doing that to using a batch API.

**Comment by indsak** [comment]
How can I consume batch of messages in Matlab using librdkafka? I tried setting max.partition.fetch.bytes to required number while initializing consumer from Matlab end and setting message.max.size in broker properties. But Matlab crashes when consumer tries to consume data from the queue using [k,v,msg] = model_C.consume();

Any help on how to consume messages in batch in Matlab?
