### ISSUE TITLE
Producer behavior when Kafka is down

### ISSUE THREAD

**Issue by javierholguera** [edenhill/librdkafka#1309]
This is not an issue, this is a question.

I'd like to confirm the behavior that we can expect from librdkafka when producing to an unstable cluster.

I've already tested the scenario where the cluster is completely down, before even sending the message. For what I've seen, the message sits in the internal queue for `message.timeout.ms` and after that returns with an error.

For the scenario where the message gets sent because the cluster is available but somehow it never returns, are these steps and correct expectations?
1. librdkafka sends the event to the broker
2. librdkafka waits up to `socket.timeout.ms` to get a response from the broker.
3. After that, it retries as many times as `retries` dictates, with `retry.backoff.ms` between retries
4. Finally, once the `retries` are exhausted, it will return an error.

Is this the expected behavior or would it detect that the broker is down / very slow and do something differently?

Thanks.

**Comment by tinux2015** [comment]
need this!!!

**Comment by edenhill** [comment]
## Waiting for active partition leader
The following cases are handled identically in librdkafka:
 * entire cluster is down
 * no leader for partition
 * no active connection to the partition leader

In all these cases the message(s) remain in the partition's queue waiting for an active connection to the partition leader. The client will perform metadata refreshes at regular intervals to check if the leader has changed, and it will also try to reconnect (forever) to any brokers that are down.


## Unresponsive brokers
If the producer sends a ProduceRequest containing the message to the broker it will put the message(s) on the wait-response queue (waitresp). The ProduceRequest's protocol timeout is set to the timeout of the first message in the ProduceRequest batch, i.e., the oldest message.
(The message timeout is based on `message.timeout.ms` and the timeout scanner runs roughly once per second (sub-second timeouts are thus meaningless)).
If no response is received from the broker within that request timeout the request fails and the message(s) in the request are failed, the delivery report will propagate the `RD_KAFKA_RESP_ERR__TIMED_OUT` error. No retries will be made at this point since the `message.timeout.ms` has been reached.
On the other hand, if the connection is closed before a response is received and before the timeout hits, then metadata is refreshed (to find out if there is a new partition leader that will take over from the down broker) and the messages are put back on the partition queue for a future retransmission. 
Do note though that this retransmission does not increment the retry count; retries are incremented for temporary server-side errors, not connection losses (which might just be a sign of network instability).

## Temporary server-side errors
For temporary errors returned by the broker, such as`ERR_REQUEST_TIMED_OUT`, the request is retried in its entirety and the retry counter is incremented by one.

**Comment by jonefeewang** [comment]
@edenhill   how to stop librdkafka trying to connect a down broker(if it is taken out of cluster intensionly) ?

**Comment by edenhill** [comment]
That is currently not possible, but there is work being done in PR #1659  to provide sparse connections.
We're planning to including this PR in a release later this year.
