### ISSUE TITLE
clarifications about consumer

### ISSUE THREAD

**Issue by silviucpp** [edenhill/librdkafka#1323]
Hello,

I started working on a erlang binding for librdkafka (https://github.com/silviucpp/erlkaf) and I have few questions on the consumer side.

Because of the way erlang is designed, where you shouldn't call any functions that are blocking the native threads from erlang side and also it's better to not abuse the calling of native functions I was thinking to the following approach for consumer side:

1. Disable automatically commit of the offset in librdkafka (enable.auto.commit= false)
2. Pull the messages in batches of x from librdkafka and send them async to erlang side.
3. Once a message is processed successfully just use (rd_kafka_offset_store)
4. Once I don't have any messages unprocessed in erlang go to step 2.

5. Also I would like to have each topic and partition in it's own erlang processes to be able to process them in paralel as time is no point in waiting each other.

Questions:

1) For step 3 . librdkafka will commit those by respecting auto.commit.interval.ms setting ?
2) In order to do what I described to point 5 I will need to know if there is something in librdkafka that I can use to poll a consumer group queue for specific messages
in a topic and partition.
3) Also I have a question for the following scenario:

	a)consumer pulls message offset 100 from topic A partition 1
	b)the message 100 takes long time to process so the offset is not stopped yet using rd_kafka_offset_store
	c)an rebalance event takes place and partition is reassigned to another consumer
	d)the event finish the processing.. 
	
3.1) what will happened to step d ? when will try to store the offset 
3.2) the new consumer will start from message 100 because was not committed yet ?
3.3) If the above is true how I can avoid

Kind regards,
Silviu

**Comment by edenhill** [comment]
Nice project :)

Your design generally sounds good, and for question 1, yes, it will commit the manually stored offsets.

The problem (which you have identified) with pulling messages out of librdkafka before processing them is that if your bindings pull out 1000 messages from Kafka and queue them in Erlang, and a consumer rebalance happens which changes the assignment of the group - removing the partitions of those messages from this consumer - then librdkafka will purge all its message queues to make sure the application does not get any outdated messages for partitions it no longer owns. But the 1000 messages already pulled out will not be purged and the application will process them despite the assignment having changed.

One solution, if erlang allows it (we have the same problem in Go, and Go channels can't be purged), is to listen to assigned/revoked events (register a rebalance_cb) and manually purge the erlang queue as soon as the partitions are revoked.

Also note that the high-level consumer will interleave messages from different partitions on the same queue which is later served by consumer_poll().
Will you separate them per partition into different erlang queues?

Question 3: librdkafka will always allow an offset_store(), but it will not commit offsets for partitions that it no longer owns (after the assignment changed). You have a chance to commit final offsets in the rebalance_cb when partitions are revoked, but after that you shouldn't since it may interfere with other clients.

**Comment by silviucpp** [comment]
Hello,

Thanks a lot for clarifications.

Regarding `rebalance_cb` yes I can listen to it and purge the queue from erlang process. Only problem I see here is that the only way I can interact from native code to erlang code is in async manner. I can send from native code an async message to erlang but I can't stop the rebalance_cb to exit before my message is processed in erlang and messages are purged and last offsets are committed. Might be a delay here of milliseconds..

Also I was thinking this days how to pull from librdkafka the messages for a specific topic and partition. I saw the queue api and I want to ask if it's correct in the rebalance callback on the assign message to get the queue for each partition and to assign it to an erlang process. And each erlang process will poll it's own queue. This way I can have a fair polling where partitions are not blocking each other (let's say consumer form partition 1 is slower then the one form partition 2 - we don't want the to affect each other). Also In order to make poll much better In erlang 20 I can use rd_kafka_queue_io_event_enable in order to be notified when I have messages in the queue.

A question I have here is:

If I redirect all partitions queue to my own queues do I still have to call rd_kafka_consumer_poll on the main poll ? I guess yes

Silviu

**Comment by edenhill** [comment]
I met the same kind of problems with the [golang](https://github.com/confluentinc/confluent-kafka-go/) bindings and I added the non-callbacky events API for that purpose.
https://github.com/edenhill/librdkafka/blob/master/src/rdkafka.h#L3112

The rebalance_cb or rebalance event is allowed to take some time to do its work, as long as that time is well below the `session.timeout.ms`.

Yes, you can use the queue forwarding API to redirect your assignment to specific queues.

Yes, you will still need to call consumer_poll() (or queue_poll() if you use the event API) to serve the general consumer events that are not partition-centric, such as rebalances.

**Comment by silviucpp** [comment]
@edenhill in case of `RD_KAFKA_RESP_ERR__REVOKE_PARTITIONS` on the rebalance callback if I post the revoke message to erlang (the app will exit the rebalance function in the meantime) and once the revoke message is processed and all offsets committed I use rd_kafka_assign(rk, NULL); (outside rebalance callback) do you see any problem ?

**Comment by edenhill** [comment]
That should be fine.
The contract is that the application must call assign() after the rebalance
callback or event has been triggered within the session timeout , but not
necesarily from the callback itself.

Den 18 jul 2017 12:45 skrev "Silviu Caragea" <notifications@github.com>:

**Comment by silviucpp** [comment]
Hello @edenhill  one more question,

In rebalance callback when partitions are assigned after calling :

rd_kafka_assign(rk, partitions);

I call
```c
rd_kafka_queue_t* partition_queue = rd_kafka_queue_get_partition(rk, topic.c_str(), partition);  rd_kafka_queue_forward(partition_queue, NULL);
```
But somehow I gues on the same callback on revoke I need to do something to cancel the forward beside 
```c
rd_kafka_queue_destroy(partition_queue );
```
Because on the next assigned the code is crashing..

**Comment by silviucpp** [comment]
Please ignore it . my bad code was crashing from another reason not related to librdkafka

**Comment by silviucpp** [comment]
Hello,

I was testing the termination sequence and in case the cluster is up there is no problem but in the following scenario `rd_kafka_queue_destroy` blocks for `session.timout` period

1. Create the objects and start consuming 
2. Cut off the internet between client and cluster
3. Stop the consumer (rd_kafka_queue_destroy) blocks

This is by design ?

Silviu

**Comment by edenhill** [comment]
That is by design, the same thing would happen from rd_kafka_consumer_close() if you wouldn't have forwarded the queues.
It is blocking on trying to commit the final offsets.

**Comment by silviucpp** [comment]
Can't we have a timeout somehow ? independent from `session.timeout`
