### ISSUE TITLE
Posting message to the already created topic

### ISSUE THREAD

**Issue by guruprasadkk** [edenhill/librdkafka#1324]
Hi Edenhill,

    I have a requirement where I need to post a message to already created topic. Some other component will create the topic and they will pass the topic name to my component and I need to post the message to it. But to post the message I need to the topic object if I use the below 2nd API.

So should I use below API
  virtual ErrorCode produce (const std::string topic_name, int32_t partition,
                             int msgflags,
                             void *payload, size_t len,
                             const void *key, size_t key_len,
                             int64_t timestamp,
                             void *msg_opaque) = 0;

instead of 
  virtual ErrorCode produce (Topic *topic, int32_t partition,
                             int msgflags,
                             void *payload, size_t len,
                             const std::string *key,
                             void *msg_opaque) = 0;

Please advise. If first API is the one I should use, If i pass the name of the topic which is already existing what will happen? will it try to create new or it will use the existing topic when it finds there is already a topic created with the same name.

**Comment by edenhill** [comment]
librdkafka is generally moving away (as in providing alternatives) from the Topic object centric approach, since it is a bit of a hassle for the application to maintain the Topic object.
So you should be fine with using the first API using a string topic_name, and librdkafka will maintain the topic objects underneath.

**Comment by guruprasadkk** [comment]
Thank you. But it did not answer my question completely. If I use first API using a string topic_name with the already existing topic then internally will it try to use the topic if it is already existing or will it deletes and creates new topic?

**Comment by edenhill** [comment]
It will use the internally cached topic object.

**Comment by guruprasadkk** [comment]
Thank you. One more follow up question. If I want to get the no of partitions for that topic I know I can call metadata() API. It is working fine. But just for passing topic object to the metadata API. I am calling 
RdKafka::Topic::create() with the string(for which already topic is created) 
I am calling this API just to get the topic object(because metadata API needs topic object)
Will it internally affects anything to that topic If i repeatedly call RdKafka::Topic::create() API for already created topic or will it ignores and just return me same topic object every time?

**Comment by edenhill** [comment]
The current metadata() API is funky (outright bad) and will be fixed in a future version, but for now you'll need to do as you are already doing.

Topic::create() for a topic already known to the client will only perform a lookup + refcount increase, so it is very cheap (unless you have thousands of known topics).
Just make sure to keep the number `delete`s symetric to the number of Topic::create() so the refcounts are correctly maintained.

**Comment by guruprasadkk** [comment]
Sure. Thank you very much. So if we are going for the production which is the latest stable version I can use. I can see that there is a tag "Maintance release" for 0.9.5
So Can you please suggest me the version we can go ahead for production with?

**Comment by edenhill** [comment]
v0.9.5 is the latest release and the latest release is always recommended.
The next release, 0.11.0, will be released soon.

**Comment by guruprasadkk** [comment]
Ok. Thank you very much.
