### ISSUE TITLE
Does not work with Kafka 0.8.2.1

### ISSUE THREAD

**Issue by reacharaj7** [edenhill/librdkafka#1378]
Description
===========
I tried using this library with Kafka 0.8.2.1. I set the following 2 properties as recommended

                {"api.version.request",false},   
                {"broker.version.fallback","0.8.2.1"}

I am getting Required feature not supported by broker.

How to reproduce
================

Checklist
=========
- I am using the advancedconsumer dotnet from Master branch.
- Kafka Version 0.8.2.1

**Comment by edenhill** [comment]
The high-level consumer (which is the only consumer available in the .NET client) requires Kafka broker v0.9 or later.

**Comment by reacharaj7** [comment]
Thanks for getting back quickly. I am using AdvancedConsumer example. Also if .NET does not support lower version of kafka, are python/go consumer compatible with Kafka 0.8.2.1?

**Comment by edenhill** [comment]
The problem is that older versions of the broker (<0.9) did not support high-level balanced consumer groups, that was a Scala/Java-specific Zookeeper construct at the time.
With 0.9 proper Kafka-based support was added, and that is what all librdkafka-based clients now support.

I don't think there is any client, except the old official Scala clients, that support the old zookeeper-based high-level consumer.

**Comment by emmett9001** [comment]
FWIW [pykafka](https://github.com/parsely/pykafka) does still have support for both zookeeper-based and kafka-based high-level consumers. It calls them `BalancedConsumer` and `ManagedBalancedConsumer`, respectively.
