### ISSUE TITLE
question: memory cost of individual messages

### ISSUE THREAD

**Issue by trapexit** [edenhill/librdkafka#1382]
Description
===========
When a consumer message is destroyed does that mean all the memory is freed(after getting from rd_kafka_consume_queue)? When calling rd_kafka_consume_stop does it free all messages for that topic partition? 

I've a loop which walks backwards in chunks across several topic partitions. If I consume all messages (up to N) I'll see a certain amount of memory used at peak but when filtering those messages (destroying those I don't want and keeping the others for later) I see the memory go up far beyond the unfiltered mode. If I destroy those filtered messages shortly afterwards (before going back in the stream to find more) then the memory usage stays stable.

Are messages referencing other objects keeping the memory from being freed?

Checklist
=========
Please provide the following information:

 - [ ] librdkafka version (release number or git tag): 0.9.5
 - [ ] Operating system: Linux
 - [ ] Using the legacy Consumer
 - [ ] Using the high-level KafkaConsumer

**Comment by edenhill** [comment]
Messages are fetched in batches from the broker (the batch size is determined by the producer) and since librdkafka strives for performance it will avoid copying the message payload unless necessary. To that end a message_t object is allocated for each message, holding its metadata, but the message's payload/value is referenced from a single zero-copy receive buffer, and that buffer is only freed when all message objects pointing to it are destroyed.
However, the `queued.max.messages.kbytes` accounts for the size of the message objects (with referenced memory), when a message is destroyed (but the underlying buffer isn't) that space is decremented from the queued.max.messages.kbytes meter, allowing new messages to be fetched.
That is probably the reason why you are seeing an **increase** in memory usage when you **destroy** messages, which is of course counter-intuitive.

The default settings of librdkafka is optimized for the normal stream case and will aggressively prefetch messages, but if your application is pausing, seeking or processing messages slowly that pre-fetch buffer is not of much use and should be decreased. For this purpose, try adjusting `queued.min.messages` and `fetch.message.max.bytes` downwards.

You may also enable statistics and monitoring the partition's `fetchq` metric.

**Comment by trapexit** [comment]
So when the underlying receive buffer is full a new buffer is created? And the spaces freed in the old buffer aren't reused?

**Comment by edenhill** [comment]
A receive buffer is allocated for each Fetch response from the broker and the messages in that response will reference the buffer (unless they need to be decompressed in which case the original buffer is of no use after decompression).
While the application processes the message from the first Fetch response (referencing receive buffer 1) librdkafka will pre-fetch messages in the background that Fetch response will allocate a new receive buffer that its messages will point to. Rinse, repeat.

**Comment by trapexit** [comment]
Okay. Then that explains it. I keep misc messages from batches and since sections of the buffer aren't reused I'm causing librdkafka to hold onto all the memory ever allocated. 

I guess I'll have to copy the data out and destroy them.

Thanks.
