### ISSUE TITLE
Installation pain points

### ISSUE THREAD

**Issue by edenhill** [edenhill/librdkafka#1479]
Share your negative librdkafka installation experience here

**Comment by rjurney** [comment]
I struggled to install confluent-kafka because either it or librdkafka would not build on Ubuntu. The apt-get package is too old to work with confluent-kafka, and I got errors building from source. Or I got errors building confluent-kafka.

The way out of this mess was to use the confluent oss package from their apt-get repository. Once I added their repo, I could install confluent-platform-oss-2.11 and then librdkafka-dev as well. I found the way to do this here: https://docs.confluent.io/current/installation.html#installation-apt

A gist of my solution for Docker running Ubuntu is here: https://gist.github.com/rjurney/f8c88c9ec6568a5762814f0d81656bae

If it would really help, I could go back and try building librdkafka on Ubuntu and send you the errors.

**Comment by Jay-DZ** [comment]
I get the following error:
dpkg-shlibdeps: error: no dependency information found for

I'm not an expert but I've been struggling for 5 days, just because of instalation. Tried the packages available in ubuntu. Tried to build it from source but still can set it up. I'm using it inside another project: Kurento, and this has been an headache.

Does anyone experienced something similar?

**Comment by rolandyoung** [comment]
When we build librdkafka, we need to link with a specific build of openssl, whose location we provide by setting the CFLAGS and LIBS environment variables.

To get the configure step to work, we need to patch one of the mklove files to respect this variable; we do so by running this Perl one-liner:
`perl -i -pe 's/\$libs/\$LIBS \$libs/ if /if ! mkl_compile_check/' mklove/modules/configure.base`

**Comment by edenhill** [comment]
@rolandyoung I think you should use LDFLAGS instead - it used during configure, while LIBS is just the result of configure (and used the  Makefile phase).

Thus:
`CFLAGS=-I/alt/openssl/path/include LDFLAGS=-L/alt/openssl/path/lib ./configure `
