### ISSUE TITLE
Close Producer In C++ API

### ISSUE THREAD

**Issue by eli-jordan** [edenhill/librdkafka#1499]
Description
===========

This is really a question.

What is the right way to close an instance of `Producer` in the C++ API.
In the C API, it seems `rd_kafka_destroy` it the right API
Also `KafkaConsumer.close` seems like the API for the consumer in the C++ API
But I don't see an equivalent for the C++ Producer.

**Comment by edenhill** [comment]
You simply delete the Producer object when you are done with it, make sure to call flush() first to make sure any queued or in-flight messages are fully delivered.

**Comment by cantappa** [comment]
Although this issue is already closed I still got a question regarding that issue:
In my scenario somehow it does not seem to suffice to just delete the RdKafka::Producer object.
For test reasons I created a new producer for every message I sent and close that producer afterwards (call flush() first, delete RdKafka::Producer, delete the RdKafka::Topic object that was created, delete RdKafka::Conf objects I created and also make my own cleanup). However, the number of running threads increases with every produce call I make. Am I overlooking something here? My application does not open new threads by itself.

**Comment by edenhill** [comment]
@cantappa Make sure to delete any objects related to the Producer instance before deleting the Producer, such as Topics, Messages, etc. Otherwise there will be references to internal objects that might keep the instance alive in the background.

**Comment by edenhill** [comment]
https://github.com/edenhill/librdkafka/wiki/Proper-termination-sequence
