### ISSUE TITLE
Log JSON data not sending null attributes

### ISSUE THREAD

**Issue by dlewis2017** [edenhill/librdkafka#1521]
Description
===========
I asked to be on the bro mailing list a couple weeks ago but I still haven't heard back, so that is why I am asking the following question here:
Is there a global configurations property (https://github.com/edenhill/librdkafka/blob/master/CONFIGURATION.md) that I can set so that Bro sends all data to a Kafka topic, even if a piece of the information has a null value. If not a configuration, are there other approaches I can take?

As of now, running the below code with given configurations will send Conn bro logs in JSON format to a Kafka topic. However, if a value is not present for a given attribute, the attribute and value pair will not show at all. So if one JSON message has 21 attributes, another could be sending 20 attributes because one of the attributes has a value that is null.

-Thank you

How to reproduce
================
Add below code segment to local.bro:

```
#Defintions
@load Bro/Kafka/logs-to-kafka.bro
redef Kafka::topic_name = "";
redef Kafka::kafka_conf = table(
    ["metadata.broker.list"] = "10.194.30.232:135", #host:port
    ["debug"] = "generic, broker, topic, msg", #debugging lines
    ["queue.buffering.max.messages"] = "1000", #send in batches of this number
    ["queue.buffering.max.ms"] = "3000" #wait this many ms until sending to topic
);

#init function to name kafka topic (path), set KAFKAWRITER, and receive only LOG files
event bro_init()
{
        Log::add_filter(Conn::LOG, [
                $name = "kafka-conn",
                $writer = Log::WRITER_KAFKAWRITER,
                $path = "conn-logs-batches"
        ]);
}
```

And then run `sudo bro -i eth0 /location/of/local.bro` while traffic is running on the given port you choose

Checklist
=========
Please provide the following information:

 - [X] librdkafka version (release number or git tag): 0.9.4
 - [X] Apache Kafka version: Confluent Kafka 2.11
 - [X] librdkafka client configuration: Bro 2.5.1
 - [X] Operating system: RedHat Linux
 - [ ] Using the legacy Consumer
 - [ ] Using the high-level KafkaConsumer
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by rolandyoung** [comment]
It sounds as if you need information about how to configure Bro, which cannot be provided here.

Bro is not part of this library, in fact it is almost the opposite: this library is used to build a part of the Bro project.

Because Bro uses the librdkafka library to connect to Kafka, the Bro configuration will control how Bro does this, but nothing in the librdkafka configuration will control the content of the messages generated by Bro.

There appear to be a large number of questions and answers about Bro on Stack Overflow (about 20 times as many as for librdkafka). Perhaps you should try asking there.
