### ISSUE TITLE
Messages time out when Kafka logs roll over

### ISSUE THREAD

**Issue by blandings** [edenhill/librdkafka#1537]
Description
===========
Messages time out regularly on our cluster with the following log message in the delivery report callback:

 "Kafka Error: -192: Local: Message timed out"

First, we checked for network saturation, but that was not the case. The network is not saturated. 

Second, I checked for the message.timeout.ms property. I am not setting this, therefore, it must take the default 300000 ms.

Third, we have observed that messages time out when Kafka is rolling over it's logs. In syslog, we see these logs around the same time that messages begin timing out for multiple producers:

---
Nov 18 06:37:13 cuttlefishprt001 kafka[546]: [2017-11-18 06:37:13,947] INFO Scheduling log segment 37062116 for log 150_7871738103663525275_14-1 for deletion. (kafka.log.Log)
Nov 18 06:37:13 cuttlefishprt001 kafka[546]: [2017-11-18 06:37:13,948] INFO Scheduling log segment 36987664 for log 150_7871738103663525275_14-0 for deletion. (kafka.log.Log)
Nov 18 06:37:58 cuttlefishprt001 systemd[1]: Started Session 29178 of user root.
Nov 18 06:38:13 cuttlefishprt001 kafka[546]: [2017-11-18 06:38:13,948] INFO Deleting segment 37062116 from log 150_7871738103663525275_14-1. (kafka.log.Log)
Nov 18 06:38:13 cuttlefishprt001 kafka[546]: [2017-11-18 06:38:13,948] INFO Deleting segment 36987664 from log 150_7871738103663525275_14_0. (kafka.log.Log)
Nov 18 06:38:13 cuttlefishprt001 kafka[546]: [2017-11-18 06:38:13,962] INFO Deleting index /opt/kafka/kafka-logs/150_7871738103663525275_14_0/00000000000036987664.index.deleted (kafka.log.OffsetIndex)
Nov 18 06:38:13 cuttlefishprt001 kafka[546]: [2017-11-18 06:38:13,962] INFO Deleting index /opt/kafka/kafka-logs/150_7871738103663525275_14-0/00000000000036987664.time
....

Is there a correlation here? 

For the producer,

message.send.max.retries = 3
ack = all 
queue.buffering.max.ms = 1 (we can change this if required)

Could you help explain what might be happening? How might we solve this? 

How to reproduce
================
Have the Kafka logs rollover while running a producer sending events at high volume.

Checklist
=========
Please provide the following information:

 - [ ] librdkafka version (release number or git tag):11
 - [ ] Apache Kafka version: 0.1
 - [ ] librdkafka client configuration:
message.send.max.retries = 3
ack = all 
queue.buffering.max.ms = 1
 - [ ] Operating system: Redhat 7.2 (Maipo)
 - [ ] Using the legacy Consumer - No
 - [ ] Using the high-level KafkaConsumer : No
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [x] Critical issue - Y

**Comment by blandings** [comment]
For Kafka, we use the following settings:

maximum partition size  300 MB 
maximum segment size of 50 MB.

**Comment by edenhill** [comment]
Can you reproduce this with `debug=msg,protocol` ?

**Comment by blandings** [comment]
Yes, we will do that today and get back to you.

**Comment by blandings** [comment]
The logs are too chatty. What level logs should we get?

**Comment by blandings** [comment]
With log levels at debug, we do not hit the issue - perhaps because the producers have slowed down. Is there anything we can do about filtering the logs of interest?

**Comment by edenhill** [comment]
And Kafka version.
Neither "11" or "0.1" are valid versions

**Comment by blandings** [comment]
Sorry, I meant: RDKAFKA_VERSION_STR=	0.11.1

**Comment by blandings** [comment]
And for Kafka: kafka_2.11-0.10.1.1

**Comment by blandings** [comment]
[timeout.log](https://github.com/edenhill/librdkafka/files/1512387/timeout.log)

During the same time period we get " Kafka Error: -192: Local: Message timed out:" errors from the producer message callback function.

Does this help? I can provide more logs. Let me know if you need Kafka server-logs, cleaner-logs, controller-logs?

**Comment by blandings** [comment]
Logs uploaded in previous comment

**Comment by blandings** [comment]
Is it possible for someone to triage this? We have provided logs.

**Comment by edenhill** [comment]
The use of `queue.buffering.max.ms = 1`  reduces the batches to just a couple of messages, which in turn generates extra overhead due to worse data/batch-header ratio.
This, in addition to using `acks=all` which incurs a higher per-batch delay on the broker, results in the effective message rate dropping so low that when there is a surge in broker delay due to log rotation the messages in the client queue waiting to be delivered times out.

Solution: increase queue.buffering.max.ms to something like 50-100ms

**Comment by blandings** [comment]
Thank you. I have made those changes.

However, this is a mitigation only - correct? Under high load, it is still possible to hit this scenario.

How might we size up a configuration that would endure load? There are several moving components here:

1. # brokers - would having more brokers help? How would we size this? For instance, with 800K messages/second - would 3 brokers suffice?
2. More replicas? So while a broker is recycling logs, another broker with an insync replica could acknowledge receipt?
3. Given that this issue could still be hit, what we really need is a way to get acknowledgments for batches of messages so we can persist messages at the producer end and retry again.

**Comment by edenhill** [comment]
> However, this is a mitigation only - correct? Under high load, it is still possible to hit this scenario.

No, it is not really a mitigation, it is just how this works.
For a given client connection the broker will only serve one ProduceRequest at the time, with acks=all and replicas>1 that also means the broker will need to wait for replicas to receive and store the messages in the request, which adds an additional layer of latency. Let's say a full ProduceRequest/Response takes 10ms.
If you have a low queue.buffering.max.ms so that the producer only batches a few messages for each ProduceRequest you will have a large number of ProduceRequests in-flight to the broker, each taking 10ms to handle.
As an example; if you are produce():ing 1000 messages per second, and you get on average 2 messages per request, then the actual broker thruput rate will be 2*(1000/10) = 200 messages/second.
Clearly, with an input rate of 1000 and a delivery rate of 200, there will be a backlog queue building up and after some time this queue will be so large/long that messages will begin timing out in the queue even before they get to be sent to the broker.

If instead, with the same numbers, you increase queue.buffering.max.ms to 100ms, the producer will batch ~100 messages per ProduceRequest, which gives a broker throughput rate of 100*(1000/10) = 10000 messages/second, which is far more than the 1000 msgs/s input rate - and there will not be a queue backlog build-up in this case.


These numbers are simplified and exaggerated, for the sake of simplicity.
