### ISSUE TITLE
rd_kafka_brokers_add() required?

### ISSUE THREAD

**Issue by rgerhards** [edenhill/librdkafka#1545]
Description
===========
Sorry, I did not 100% sure find out from the doc: it is absolutely required to call ```rd_kafka_brokers_add()``` at least one broker? I have read that metadata ```bootstrap.brokers``` is also used as a base, but I could not find if there is a config file that comes with librdkafka where this can be set **without** explicitly being programmed in code. Sorry if I am overlooking the obvious.

**Comment by edenhill** [comment]
`rd_kafka_brokers_add()` is a legacy API that should be deprecated.
The recommended approach is to provide the bootstrap broker(s) as a CSV string in config as `bootstrap.brokers`.

librdkafka strives to make all configuration properties string key=value based so that an embedding application or library does not need to add a configuration layer itself but can simply pass-thru configuration properties as is.

As for a config file reader; this is not supported, and is up to the application / high-level library to implement.
Example here:
https://github.com/edenhill/librdkafka/blob/master/tests/test.c#L484

**Comment by rgerhards** [comment]
Thanks for the quick answer! This is very helpful. I'll adjust our code accordingly.

Question: do you think it would make sense to have a "standard" config file reader inside librdkafka? I am asking because I would potentially be willing to turn the sample code into a PR for such. But not sure if that would be counter your intent...

**Comment by edenhill** [comment]
@rgerhards I've thought about this and it would be a welcome convenience in some cases, but I've refrained from adding it due to:
 * configuration handling and formats are application specific
 * it needs to support some way of letting application configuration through, otherwise it would promote scattered configuration files (one for the app, one for the kafka client, etc) which I strongly oppose. The Java JAAS config file is a great(bad) example.
 * it is unlikely that a simple interface would survive the first couple of iterations of an application before they would outgrow it, which means it would be of little value, or need to be complex to support different variations.
 * more code to maintain in something that is clearly the application domain.

**Comment by rgerhards** [comment]
thx for considering!
