### ISSUE TITLE
Question: batch.num.messages & queue.buffering.max.ms

### ISSUE THREAD

**Issue by michallevin** [edenhill/librdkafka#1566]
batch.num.messages default is 10000
queue.buffering.max.ms default is 0

Does this mean that by default no batching is done?

**Comment by edenhill** [comment]
Almost, it means it will wait 0 ms for messages to accumulate before serializing a batch and enqueueing it for transmission.
If the time it takes to do the serialization (and other broker-thread tasks) is higher than the time it takes the application to produce() a message, then it is likely that more than one message will be accumulated for the next wait-less serializing batch run.
So it depends, but most likely you will see 1 or only a few messages per batch with this setting, which also means that you will not get optimal performance due to the increased overhead ratio of sending single or few messages at the time.

I suggest you find a reasonable trade-off value for latency/thruput somewhere between 0-100ms.
Even inreasing the timeout by a few milliseconds will do much (depending on your produce pattern).
