### ISSUE TITLE
KafkaConsumer is not receiving callbacks

### ISSUE THREAD

**Issue by noahdav** [edenhill/librdkafka#1620]
Description
===========
When using the KafkaConsumer the callback that is registered for consume_cb is not called.  I am seeing the same behavior using the rdkafka_consumer_example_cpp.  When I specify the -f ccb option I am not seeing any messages in the consumer.  However when I do not specify this flag the messages are delivered as expected.

I see that issue 1137 discuses this and says that the consume_cb is not supported for KafkaConsumer. 
https://github.com/edenhill/librdkafka/issues/1137

If this is the case how do I consume async messages using the KafkaConsumer?  Is there plans to add this feature or is there a reason that this is not working?  Does it work with the Consumer class?  I see that the consumer class is marked as legacy so is this feature going to make it into the KafaConsumer?

How to reproduce
================
rdkafka_consumer_example_cpp -g test-consumer-group -b localhost:9092 -f ccb test

No messages are received.

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): v0.11.3
 - [ ] Apache Kafka version: 2.11-1.1.0`<REPLACE with e.g., 0.10.2.3>`
 - [ ] librdkafka client configuration: `<REPLACE with e.g., message.timeout.ms=123, auto.reset.offset=earliest, ..>`
 - [ ] Operating system: `<REPLACE with e.g., Centos 5 (x64)>`
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
You are right that the consume_cb is not supported in the new KafkaConsumer, the main reason for this decision was to make KafkaConsumer as similar to the Java counterpart as possible, and that the consume callback really doesn't add much (small performance improvement).

As for the async nature; it is not truly async since the application will still need to call a poll function to trigger these callbacks. This means it is equivalent to you calling poll() repeatedly and handling each message until the queue is empty.

**Comment by noahdav** [comment]
Sounds reasonable enough.  Thanks for the clarification.
