### ISSUE TITLE
Getting rd_kafka_t from rd_kafka_queue_t

### ISSUE THREAD

**Issue by loskutov** [edenhill/librdkafka#1707]
Description
===========
After an `rd_kafka_queue_t` is created, the corresponding `rd_kafka_t *` is saved into its `rkqu_rk` field. However the structure declaration is marked as `/* Public interface */`, the structure seems to be a private implementation detail. A way to get back `rd_kafka_t *` from a created `rd_kafka_queue_t` using the public interface seems to be lacking then.

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): 0.11.3
 - [ ] Apache Kafka version: `<REPLACE with e.g., 0.10.2.3>`
 - [ ] librdkafka client configuration: `<REPLACE with e.g., message.timeout.ms=123, auto.reset.offset=earliest, ..>`
 - [ ] Operating system: `<REPLACE with e.g., Centos 5 (x64)>`
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
The rd_kafka_t pointer is indeed stored internally for the queue, but we want to avoid exposing it in the public API because there are some future plans to make queue_t objects usable for multiple kafka_t instances, and in that case it would not be clear what instance to return.

The workaround is for the application to keep track of the kafka_t handle itself.
