### ISSUE TITLE
Query : Escaping Carriage Return and Line Feed within  messages in a Producer

### ISSUE THREAD

**Issue by dmag1** [edenhill/librdkafka#1735]
Read the FAQ first: https://github.com/edenhill/librdkafka/wiki/FAQ

Description
===========
**This is actually a query**. I am using rdkafka as a producer. However some of my messages would contain carriage return and line feed(CR LF) and due to this Kafka consumer  applications would not work as expected. So as a work around I included replacing CR LF logic under method: _**`rd_kafka_msg`**_ of class : **_`rdkafka_msg.c`_** (I only have control over producer). However with this I observed that drastic reduction of the throughput(from 10Mb/s to 1Kb/s). Is there a suggested way to do this without much performance degrade ?

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.
N/A as this is a query. **I understand Github issues page is not a great place to ask questions. However could not find any mailing list address or IRC channel under FAQ page. If I somehow missed the links of those please update me.**

**Comment by edenhill** [comment]
Kafka and its clients doesn't care or try to interpret the message key or payload, they are considered opaque binary blobs, so it doesn't make sense to do any sort of format handling in the generic client.

What you should do is formalize the message types used in different topics across your organization and preferably create schemas (see confluent schema-registry for how to manage them), and use serializers and deserializer to convert between a native format and serialized format - most clients have serializer/deserializer interfaces than you can plug in to - librdkafka does not because it doesn't make sense in C - but there's [libserdes](https://github.com/confluentinc/libserdes) to help you interact with schema-registry.

**Comment by dmag1** [comment]
Hi edenhill,

Thanks for the update. I will look in to your suggestion.  Does librdkafka have a mailing list or IRC channel for question like these ?

**Comment by edenhill** [comment]
While we use github issues for librdkafka-specific questions, these more general kafka questions might be more suited for the Confluent community slack (either in one of the dedicated channels per technology segment, or #clients for any client related discussions):
https://launchpass.com/confluentcommunity
