### ISSUE TITLE
Failed Messages 

### ISSUE THREAD

**Issue by abhit011** [edenhill/librdkafka#1743]
Its not related to any issue or bug. I have been extensively using librdkafka in my stack and seeking suggestions when Kafka Producer fails to produce message on broker node/nodes, and gets caught in dr_cb() as failure like TimeOut etc ...
 
I need to ask what strategies people use to save those messages .
* Do they Produce to the same Kafka Cluster from there itself , or they there is another Kafka backup cluster which is meant for handling such failed Messages only .?
* Or Saving those failed messages to a different layer ? 

Abhi

**Comment by abhit011** [comment]
Any inputs

**Comment by edenhill** [comment]
This is outside my expertise, we welcome the community to chime in (as alwas), but questions like these are perhaps better asked on the Confluent community slack or the kafka-users mailing list.

**Comment by abhit011** [comment]
Yes I agree with you @edenhill, but the reason of asking here was only with respect to librdkafka , since there must be some fail over strategies which librdkafka users must have been using in their production environment that's why...

**Comment by abhit011** [comment]
Anyone please do share some pointers ?

**Comment by rolandyoung** [comment]
You have to consider what failure scenario you are trying to recover from. Once you have lost connectivity to all the brokers in the cluster, you have probably lost connectivity to everything, or maybe you have misconfigured your Kafka client. In either case, trying to send to some other Kafka resource is probably not going to work.

If you absolutely must preserve the content of messages that could not be posted, you have to log them locally. You should be able to design your log file so that it can be replayed into the original target cluster (either using your client application or an external utility) once the issue has been resolved.
