### ISSUE TITLE
Cert location require certs on disk

### ISSUE THREAD

**Issue by noahdav** [edenhill/librdkafka#1770]
Description
===========
After following the instructions on https://github.com/edenhill/librdkafka/wiki/Using-SSL-with-librdkafka I am able to successfully use SSL.  Since in our case the certs are in the windows cert store we do not want them on disk.  Unfortunately after looking at this it appears that librdkafka only supports having paths to the certificates.  Is there a way to specify only the buffer of the cert which we can load and not the location of the cert files?  This is blocking us since due to security concerns we cannot have the certs on disk.

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): `<REPLACE with e.g., v0.10.5 or a git sha. NOT "latest" or "current">`
 - [ ] Apache Kafka version: `<REPLACE with e.g., 0.10.2.3>`
 - [ ] librdkafka client configuration: `<REPLACE with e.g., message.timeout.ms=123, auto.reset.offset=earliest, ..>`
 - [ ] Operating system: `Windows`
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
Something like this?:
https://github.com/edenhill/librdkafka/pull/1338

**Comment by noahdav** [comment]
Yes this would work for our needs.  Any idea when this merge back to master?

**Comment by pedrojuk** [comment]
I'm trying to get Python clients running on Windows 10 and so would also like this functionality. At the moment I'm copying certificate files which is unacceptable on Windows as @noahdav says.  Any date for this?

**Comment by superdisc** [comment]
(Really sorry if this is not a right location for this comment)

Is there any update on this issue? We are facing quite similar issue.

In our organisation we have implemented Two-Way SSL/TLS (Kind of Example 2 in https://github.com/mhowlett/confluent-kafka-dotnet/tree/security/examples/Security).

We have created a producer application using confluent .Net Kafka client - 0.11.6 and it will be deployed on Micorsoft Azure. We are facing an issue in passing the private key location as with Azure it is not possible to export the private key of certificate once it is installed and due to security reasons, we are not allowed to deploy the private key file along with the application.

Is there any solution to this issue?

Thanks.

**Comment by edenhill** [comment]
With the release of librdkafka v1.0.0 we're now addressing and tending to the queued up community PRs that were pushed for the next release.
This PR will be massaged and merged soon.

**Comment by superdisc** [comment]
Appreciated your quick reply. That's great news.. Would it be possible for you to provide any ETA on that? This will help us to plan accordingly.

**Comment by edenhill** [comment]
PR probably merged within a week.
As for the next release, there are no immediate plans, so probably two months out.

**Comment by superdisc** [comment]
Thanks @edenhill.

**Comment by cowellrj** [comment]
@pedrojuk how are you copying your cert files in Windows 10? I've tried exporting a few root certs through MMC in both DER and base-64 encoded .CER files and then pointing my python consumer to them with ssl.ca.location but I still get "Local: SSL error: (errno: No such file or directory)" from debug and fail to connect. All works fine in Linux but Windows is all new to me and struggling on this. Thanks.
