### ISSUE TITLE
How to produce faster?

### ISSUE THREAD

**Issue by congchp** [edenhill/librdkafka#1795]
Hi.
Description
===========
I use C++ API to produce message. After I call the Producer::produce, I need to call a poll(time_out). If I set the time_out as 0, it doesnt work. So how can we produce faster?

Best wishes.

**Comment by congchp** [comment]
If I set time_out as 0. There will be some message lost.

**Comment by edenhill** [comment]
produce() is asynchronous, sending the message to the broker and waiting for response in a background thread.
If you register a Delivery report callback you will need to call poll() at regular intervals to trigger the delivery reports for produced messages, but since producing easily takes a handful of milliseconds it is highly unlikely that your poll(0) call immediately following produce() will trigger the callback for the message just produce()d.

**Comment by edenhill** [comment]
For applications with a continouous stream of messages to produce the typical program flow is:

```
  while (run) {
       msg = something_to_produce();

       produce(msg);

       poll(0); // serve delivery report callbacks from previous produce() calls, not this one
}

//terminating, wait for outstanding messages to be produced
flush(15*1000);
delete producer;
```

**Comment by edenhill** [comment]
1. correct, but then you won't know if your messages were actually produced or not.
2. If you are sending a finite number of messages and the size of those messages fits in ram then you can set `queue.buffering.max.messages` and `queue.buffering.max.kbytes` accordingly (+20%) and call produce() from your loop, followed by flush() outside the loop to wait for deliveries.

**Comment by congchp** [comment]
yeah. We can use flush().
 But I dont know why messages cant be sent successfully if we dont use flush(). :)

**Comment by edenhill** [comment]
flush() waits for outstanding messages to be delivered.
If you don't call flush() prior to destroying your producer any outstanding messages will be discarded: some of them might be produced, some might not, you just wont know.

**Comment by congchp** [comment]
Thanks very much for patience.
