### ISSUE TITLE
Question about queued.max.messages.kbytes

### ISSUE THREAD

**Issue by XiaoyaoFan** [edenhill/librdkafka#1808]
Description
===========
Hi edenhill,

We are facing a case where when our application processes messages slowly, we want consumer to stop fetching messages from broker, and to re-start fetching when application could continue processing.

I think it could be achieved by setting proper "queued.max.messages.kbytes", then application could just stop calling poll() on consumer, consumer will stop fetching messages from broker when local queued messages' size exceeds "queued.max.messages.kbytes" automatically, and once queued messages' size decreases, consumer will fetch again. Do I understand its usage right?

If my understanding is right, then I still have doubt, when consumer keeps not fetching messages in such case, will consumer still communicate with brokers to signal it's still alive to avoid assigned partitions's revocation? Should our application take actions to maintain consumer's aliveness?

Thanks in advance for your reply.

**Comment by edenhill** [comment]
Your understanding is correct, the fetcher will stop fetching partitions that have reached their threshold, and resume as the queue level drops below the threshold again.

This only affects fetching, other protocol requests, such as heartbeats and group coordination is still being performed in the background.
However, if you've registered a rebalance callback you do need to call poll() at regular intervals to serve the rebalance callback in case the group rebalances. For this case you can pause() partitions you temporarily don't want to consume (due to processing), which will prevent further messages from being returned from consumer_poll() until you call resume() again.
Do note however that pause() will purge the local fetchq, so if it is called often you will increase the network usage since librdkafka will purge the queue on pause(), then pre-fetch up to the queue threshold again when you call resume(). You can work around this by making the queue smaller, but do note that messages are fetched on a messageset/batch level, so it might fetch larger chunks than the queue limit.

**Comment by edenhill** [comment]
Handle::pause and Handle::resume: yes,
for poll() you should use KafkaConsumer::consume() instead

**Comment by XiaoyaoFan** [comment]
Thank you very much! I'll try your suggestion.

**Comment by XiaoyaoFan** [comment]
BTW, is registration of rebalanced callback on a KafkaConsumer which uses direct assign() (not subscribe()) meaningful? If it is registered, will it has chance to be triggered or any error will be thrown?

The reason why I asked is that there is related information in Java KafkaConsumer:
"It is also possible for the consumer to manually assign specific partitions (similar to the older "simple" consumer) using assign(Collection). In this case, dynamic partition assignment and consumer group coordination will be disabled."

**Comment by edenhill** [comment]
As stated in the Java docs, the rebalance callback will only be called if you use subscribe()
