### ISSUE TITLE
high throughput producer solution

### ISSUE THREAD

**Issue by eelyaj** [edenhill/librdkafka#1818]
Hi, edenhill:
I need some advice for producer design.
currently, I got a multi-thread app which contains some process thread and some producer.

solution1:  each producer send message to all partitions according the key.

thread1 ----- producer1 -------- partition1
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; \  &nbsp; &nbsp; &nbsp;  /
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\  &nbsp;   / &nbsp;  
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp; / &nbsp; \ &nbsp; 
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; /  &nbsp; &nbsp; &nbsp;  \ &nbsp; 
thread2 ----- producer2 -------- partition2

solution2:  each thread select producer according the key, and each producer send message to corresponding partition

thread1 ----- producer1 -------- partition1
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; \  &nbsp; &nbsp; &nbsp;  /
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\  &nbsp;   / &nbsp;  
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp; / &nbsp; \ &nbsp; 
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; /  &nbsp; &nbsp; &nbsp;  \ &nbsp; 
thread2 ----- producer2 -------- partition2

for high throughput concern, which one is better.
thanks a lot.

**Comment by edenhill** [comment]
It typically doesn't matter at that level.

High throughput requires proper batching, making sure enough messages accumulate in a batch before sending. The default setting of `linger.ms=0` doesn't really help since it will try to send messages as soon as possible, and this means batching only really kicks in when there is backpressure.
So make sure you get proper batch sizes, and thus thruput, by setting `linger.ms` to a reasonable value for your design. A higher value will give you larger batches at the expense of higher latency.

A good starting point is setting it to 100 ms and then increasing it in increments of 100ms until your thruput flattens out.

**Comment by eelyaj** [comment]
ok, thanks.
