### ISSUE TITLE
Question on Pause/Resume

### ISSUE THREAD

**Issue by accelerated** [edenhill/librdkafka#1849]
Hi @edenhill 

I'm actually trying to get a better understanding of the pause/resume functionality for the producer and consumer side. 
1) First of all is the pause/resume a local functionality or implanted broker-side in Kafka?
2) when I pause a consumer, does the consumer have to have assigned partitions? So for example if I have dynamic subscription and I pause all partitions for a certain topic _before_ the rebalance callback is triggered with a new assignment, what happens then? 
3) How about if a consumer is paused and a partition revocation occurs for this consumer? will it still be paused under the new assignment? 
4) If I keep polling while the consumer is paused, I assume the local queue will still deliver buffered messages, but librdkafka will no longer fetch batches from the broker, correct?
5) If I pause partitions to which a producer writes to, and still produce messages locally or call poll/flush on this producer handle, will the messages still be queued internally but not pushed to the broker? In other words flush is a no-op?
6) are heartbeats still sent for consumers which have all their partitions paused?

I do see some weird behavior with pausing consumers so I just want to make sure I know how how it's implemented. 

BTW what I'm trying to achieve is start a consumer in **paused** mode and only resume it when the application is ready to receive messages. Any suggestions on how to do that? 

Thanks for the help!

**Comment by edenhill** [comment]
Hey!

 1. pause/resume is implemented in the client, it tells the partition fetcher to stop fetching an otherwise active partition.
 2. the code assumes that you are pausing and resuming a set of previously assign()ed partitions. It might work with non-assigned partitions as well but this is not something we guarantee. Since it is basically just a flag on the internal partition structure it should work, given that the partition is known to the client beforehand.
 3. partitions will remain paused after a rebalance and re-assignment.
 4. No, it will not give you any new messages when polling, in fact it will purge the queue of fetched messages, and stop the fetcher.
 5. If you are referring to pause a partition on the producer:  the messages for the given partition will remain queued on the partition queue and they are subject to flush(), i.e., flush() will wait for these messages to be flushed/produced. Since the partition is paused the only thing that can happen is that either your flush() times out, or the message times out due to message.timeout.ms, whichever comes first.
 6. Yes, heartbeats and all other control plane remains operational, it is only the actual fetching or producing fro-to broker that is affected by pause.

You should be fine doing:
```
     case ..ASSIGNED_PARTITIONS:
               assign(my_assignment);
               pause(my_assignment);
              break;
...
```

**Comment by accelerated** [comment]
Thanks for the quick and detailed response.  So if want to pause the consumer but not rely on the assignments, can i do the following which should make the partitions known on the client side?
1) get metadata for a topic
2) pause partitions returned by metadata
3) subscribe client to topic or manually assign partitions
4) resume at some later point in time

Btw, right now i was doing steps 2,3 and 4 and it works, so i'm not even sure how these partitions are known to the client as i do this on startup.

**Comment by edenhill** [comment]
That should work.

If you are referencing a partition before it is known it will be created internally with a DESIRED state.

**Comment by accelerated** [comment]
Thanks! I tested and it works fine!

**Comment by ronalabraham** [comment]
> 4\. No, it will not give you any new messages when polling, in fact it will purge the queue of fetched messages, and stop the fetcher.

Can you please explain what happens when you later resume? Do you do some in-memory bookkeeping to guarantee that you resume reading from the next message in the partition that has yet to be delivered to the application? My guess is yes, but just wanted to confirm.

**Comment by accelerated** [comment]
AFAIK the last committed offset is preserved locally and fetching will resume at that point. Otherwise it can't work. However i'm not sure as to why local fetch buffers are purged...seems unnecessary and will cause more network traffic as the fetcher will need to replenish again when consumption resumes. If you pause/resume often, it would probably degrade performance IMHO. Plus brokers have extra work to do. But maybe i'm mistaken. Purging should be done when getting a partition re-assignent AND the old partition is NOT included in the new assignment or when unsubscribing.

**Comment by ronalabraham** [comment]
@accelerated Thanks. The part about local fetch buffers being purged is why I wanted to confirm the behavior on resume. Anyway, I opened a new issue (https://github.com/edenhill/librdkafka/issues/2052) for my question in the hopes that it will be more visible.

**Comment by edenhill** [comment]
The partition fetchq is purged because pause() is a fencing position that invalidates all messages currently in queue (the fence version is bumped).

**Comment by ryzhyk** [comment]
Thanks for this great discussion, @edenhill and @accelerated, it helped me to understand the semantics of pause and resume much better.

I am looking for a way to pause and later resume the entire consumer so that it remains paused despite rebalancing events.  This discussion suggests that the following should work:

> 1. get metadata for a topic
> 2. pause _all_ partitions returned by metadata (including ones not currently assigned to this consumer)

However, as @edenhill explained, this behavior is not guaranteed by the API, since `pause` is only guaranteed to work for currently assigned partitions.  Another potential issue is that the number of partitions in a Kafka topic can change dynamically, so in the unlikely case that the consumer gets assigned a previously non-existing partition, the new partition will not be marked as paused.

I guess an alternative would be to hook into the rebalance callback and pause all newly assigned partitions from the callback (when the consumer is in a paused state).  Will this work? Is there a simpler way?

PS. I am using `librdkafka` from Rust via the `rdkafka` crate.

**Comment by edenhill** [comment]
You may only pause partitions that are assign()ed, so you would need to do this from a rebalance callback/event.

**Comment by ryzhyk** [comment]
Makes sense, thank you.  Does pausing the partition inside the callback guarantee that no messages from newly assigned partitions will get returned by `poll` before pausing takes effect?

I am new to Kafka, so it's possible that I am not using it as intended, but do you think it would make sense to have consumer-wide pause/unpause methods that apply to all current and future partitions assigned to the consumer?

**Comment by edenhill** [comment]
> Does pausing the partition inside the callback guarantee that no messages from newly assigned partitions will get returned by poll before pausing takes effect?

Calling consumer_poll() after pause() has returned guarantees that no messages for the paused partitions will be seen.
One exception is consume_batch*(), which if called from another thread might have accumulated some messages already prior to the pause, and it will return those, but doing consume*() in any form and pause/resume/seek/assign() from different threads will risk returning outdated messages, for obvious reasons.


> I am new to Kafka, so it's possible that I am not using it as intended, but do you think it would make sense to have consumer-wide pause/unpause methods that apply to all current and future partitions assigned to the consumer?

That does not seem to be a common use-case so not something we'll optimize for.

Using the rebalance callback allows you fine-grained control of which partitions are being assigned and when, so I'd recommend using that.
