### ISSUE TITLE
First messages in a topic missing when setting auto.offset.reset to 'latest'?

### ISSUE THREAD

**Issue by abyx** [edenhill/librdkafka#1852]
Description
===========
Seems like we're missing the first messages in a topic that's created after the consumer has started up with this setup. Asking on `node-librdkafka` suggests that this is the intended behavior, and I wanted to make sure this is so.

How to reproduce
================
See description [here](https://github.com/Blizzard/node-rdkafka/issues/435)

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): `0.11.4`
 - [x] Apache Kafka version: `0.10.0.0`
 - [x] librdkafka client configuration: As described in the topic, `auto.offset.reset = 'latest'`, the rest can be seen in the above gist
 - [x] Operating system: `macOS 10.13.5`

Will provide logs if this isn't the intended behavior

**Comment by edenhill** [comment]
It is, and @webmakersteve's answer explains it well: https://github.com/Blizzard/node-rdkafka/issues/435#issuecomment-397850717

**Comment by abyx** [comment]
Thanks @edenhill and @webmakersteve! So what's the right thing to do if we're subscribing to a pattern, e.g. `/notifications.*/`, want the `latest` in general but don't want to miss the first few messages when a new topic is created?

Is that just not doable with `latest`?

**Comment by edenhill** [comment]
It is a timing issue, subscribe() is asynchronous (due to group rebalancing) so you don't really know when it starts to actually consume a partition, which means the notion of "latest" may change between the time you call subscribe() and the time the partition is actually being fetched - namely that messages may be produced in that time.

It sounds to me that you want to read from the beginning of the partition, so I would suggest that you set `auto.offset.reset=earliest`.

**Comment by abyx** [comment]
@edenhill I see. Thank you for the fast reply and all your work :)
