### ISSUE TITLE
C++ Headers Support

### ISSUE THREAD

**Issue by alexander-alvarez** [edenhill/librdkafka#1861]
Reference: https://cwiki.apache.org/confluence/display/KAFKA/KIP-82+-+Add+Record+Headers
C header support was added to this library in https://github.com/edenhill/librdkafka/pull/1480

How much work would it be to add C++ support? I know little about the codebase (I'm coming from higher level languages), but more than happy to try to get the ball rolling if someone can point me in the right direction.

**Comment by edenhill** [comment]
I think we'll want to mimic the Java client's [Headers](https://docs.confluent.io/current/clients/javadocs/org/apache/kafka/common/header/Headers.html) class and having it backed by the C headers_t object (rather than a std::vec or similar) for efficiency.

PRs are always welcome :) How about starting off with a just implementing the public classes in rdkafkacpp.h and see how it interacts with the Message object?

**Comment by ismriv** [comment]
@edenhill is this feature request in the roadmap at Confluent, or waiting for third-party contributions? Since the C++ library is [listed as officially supported by the Confluent Platform](https://docs.confluent.io/current/clients/index.html), I was hoping that support for headers would be added to it at some point.

Currently, the equivalent feature request for [node-rdkafka](https://github.com/Blizzard/node-rdkafka/issues/414) is blocked by not having support for message headers in the underlying bindings.

**Comment by davidtrihy** [comment]
@edenhill I have opened a PR to get some feedback on changes related to this issue, I'm just looking for early feedback!

**Comment by davidtrihy** [comment]
I closed my old PR and created a new one just to have a clear history https://github.com/edenhill/librdkafka/pull/1959 this has all the changes I think that are needed but feedback on certain issues is needed.
