### ISSUE TITLE
can rd_kafka_consume be invoked in multi-thread and how many rd_kafka_t* object can be created?

### ISSUE THREAD

**Issue by yorksen** [edenhill/librdkafka#1874]
**Question One:**
 Whether it's thread-safe to use different threads to consume topics which are created via same rd_kafka_t* object?

**Question Two:**
When I try to create about 100 rd_kafka_t objects with rd_kafka_new(50 is ok, I tried), I got errors like this:
%3|1530937880.641|FAIL|rdkafka#producer-201| [thrd:SZX1000449934:9092/bootstrap]: SZX1000449934:9092/bootstrap: Failed to resolve 'SZX1000449934:9092': Too many open files.

It's strange because the 'ulimit -a' of my environment is:
.......
open files                      (-n) 1024
.......
How to config the limit ?

**Comment by edenhill** [comment]
Q1: Yes, the librdkafka API is thread-safe unless otherwise noted.

Q2: One socket and one pipe is created for each broker in the cluster. See https://github.com/edenhill/librdkafka/wiki/FAQ#number-of-broker-tcp-connections

Unless you need different configuration for your producers there is no point in creating more than one producer,.
