### ISSUE TITLE
How to get the configuration parameters from rd_kafka_t

### ISSUE THREAD

**Issue by drorgu** [edenhill/librdkafka#1883]
Hi, 
Can I get the configuration parameters from rd_kafka_t (after rd_kafka_new was called).
I know that I can get configuration parameters from rd_kafka_conf_t by using rd_kafka_conf_get but  the rd_kafka_conf_t instance cannot be referenced after rd_kafka_new was called (as it's destroyed by rd_kafka_new). 
Thanks,
Dror

**Comment by edenhill** [comment]
You can't get the configuration from an rd_kafka_t instance, but its configuration will be identical to the configuration object you pass to rd_kafka_new(), so you can just keep a copy of that object instead.

**Comment by drorgu** [comment]
OK, thanks for the quick response. I also thought about this copying solution, so I'll probably do it.

I have another related question:
In my configuration files I have two sections: 
1. KafkaProducerGlobalConfig
2. KafkaProducerDefaultTopicConfig
They both contains pairs of kay and value.
For both these two configurations I use the respective get and set methods. So each time I create a new producer instance the "KafkaProducerGlobalConfig" key values are set and each time I create a new topic the "KafkaProducerDefaultTopicConfig" key values are set.

(btw, I only use the producer at this stage).

But now I see that there is a function: rd_kafka_conf_set_default_topic_conf.
I tried to use this function but have no clue if the topic (rd_kafka_topic_t) is set with the relevant configuration. rd_kafka_topic_new receives as parameters both rd_kafka_t and rd_kafka_topic_conf_t so it should be able to read what was sent in rd_kafka_conf_set_default_topic_conf through rd_kafka_t. But I have no way to verify it - I can't create a copy of the rd_kafka_topic_conf_t doesn't have this configuration values and I can't receive the topic configuration values from rd_kafka_topic_t.

(on the other hand, based on the comments in code above rd_kafka_conf_set_default_topic_conf, I am not sure if rd_kafka_conf_set_default_topic_conf is relevant for producer topics).

Thanks again,
Dror

**Comment by edenhill** [comment]
Good question.

 * If rd_kafka_topic_new() is called with a topic_conf_t* argument (NULL) it will use the default topic configuration.
 * The default topic configuration is set by populating a topic_conf_t and then using rd_kafka_conf_set_default_topic_conf(global_conf, my_default_config). - This will replace any previously set default topic configuration.
 * As a convenience to the user, librdkafka now allows default topic configuration to be specified on the global topic configuration - this is handy in the case of configuration files since there is no need to split configuration between global and (default) topic. This means you can set `request.required.acks` with rd_kafka_conf_set() rather than rd_kafka_topic_conf_set(). This functionality is called topic fallthru configuration.
 * Internally, topic fallthru configuration will create a default topic config object. If you first call rd_kafka_conf_set("some.topic.property") and then call rd_kafka_conf_set_default_topic_config(), your default topic config object will replace the implicitly created one, which you probably don't want.
 * The recommendation is to not use set_default_topic_conf() but rely on the topic fallthru configuration.
 * You can still use topic-specific configuration, do note though that a topic's configuration is applied only the first time the topic is referenced, either by the application with rd_kafka_topic_new() or when the topic is created automatically internally because it was referenced in subscribe() or similar.

**Comment by drorgu** [comment]
Thanks. 
We like the topic fallthru configuration mechanism and will use it instead of  rd_kafka_conf_set_default_topic_conf (and will not use the KafkaProducerDefaultTopicConfig key values in our configuration).
We have though another question - if we do use topic-specific configuration will it come on top of the topic fallthru configuration or will it completely override the topic fallthru configuration.

**Comment by edenhill** [comment]
It will override the default topic config.

**Comment by drorgu** [comment]
Thanks.
