### ISSUE TITLE
Question about cmake static vs. dynamic libs

### ISSUE THREAD

**Issue by billygout** [edenhill/librdkafka#1912]
Hi, I noticed that cmake builds src/librdkafka.so (dynamic) and src-cpp/librdkafka++.a (static) by default. After some searching around, I found that cmake can be changed to build src/librdkafka.a (static) instead, using `RDKAFKA_BUILD_STATIC`.

My question is: would it be better to have .so and .a get built for both src and src-cpp by default, for ease of use? I'm not sure whether that would have a significant cost in build time.

Alternatively, for consistency should the default be static for both C and CPP? Or both dynamic?

Thank you.

**Comment by edenhill** [comment]
Since dynamic or static only affects the final linking step, the extra cost is insignificant, and this is also what the mklove build does.
So if it isn't atypical for cmake builds I agree that it should build both at the same time.

The CMake support in librdkafka is maintained by the community, PRs welcome :)
