### ISSUE TITLE
RdKafka::Topic::create() Segmentation fault

### ISSUE THREAD

**Issue by congchp** [edenhill/librdkafka#1947]
Description
===========
I update librdkafka from v0.11.3-RC1 to v0.11.5
It works well on v0.11.3-RC1.
But there is a Segmentation fault when create topic on v0.11.5.

```
Thread 1 "producer_test" received signal SIGSEGV, Segmentation fault.
RdKafka::Topic::create (base=<optimized out>, topic_str="test", conf=0x685950, errstr="") at TopicImpl.cpp:84
84        rd_kafka_t *rk = dynamic_cast<HandleImpl*>(base)->rk_;
```

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): `<v0.11.5>`
 - [x ] Apache Kafka version: `<kafka_2.11-1.0.0>`
 - [ ] librdkafka client configuration: `<REPLACE with e.g., message.timeout.ms=123, auto.reset.offset=earliest, ..>`
 - [x] Operating system: `<REPLACE with e.g., Centos 7 (x64)>`
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
Please provide full backtrace and your code

**Comment by chenlei16** [comment]
How can I solve this problem?

**Comment by kartur** [comment]
I have exactly the same issue. Anyone solved this? 
I first used 0.11.3-1 but also with 1.4.2 the problem persists.

The rdkafka_example.cpp like it exists works though, so I thought it must be a problem on my end. However, I can't seem to find anything really different in my code, since I basically just copied the relevant parts from the rdkafka_example.cpp. However, after fiddling around a little with the rdkafka_example.cpp I could also reproduce the issue there. [code will follow]
