### ISSUE TITLE
Reading from hundreds or thousands topics simultaneously ? 

### ISSUE THREAD

**Issue by gadde-cern** [edenhill/librdkafka#1976]
This is actually a question.

How would rdkafka behave if I try to read (no offset commit) from hundreds or even, thousands of partitions within one client ?
Each partition would stream a few kilobytes per second.

I could just try it, it would be fastidious to set up and mostly, I would like a client software point of view. Is it a sustainable idea from the client perspective.

librdkafka version = 0.11.x
Apache Kafka version = 2.0.0
OS: CentOS 7

Thanks.

**Comment by edenhill** [comment]
This should be fine, there will be increased CPU usage since lists of partitions take longer to iterate, etc, but the increase should be reasonable.

Do note that all partitions share the same fetch queue (by default), so you might need to size it appropriately (`queued.max.messages.kbytes` and `queued.min.messages`) and lower the number of messages/bytes fetch per-partition (`max.partition.fetch.bytes`) to avoid starvation.

See https://github.com/edenhill/librdkafka/wiki/FAQ#how-are-partitions-fetched and https://github.com/edenhill/librdkafka/blob/master/CONFIGURATION.md

**Comment by gadde-cern** [comment]
Very helpful. Thank you.

**Comment by edenhill** [comment]
Would be interesting to hear your in-field findings eventually :)

**Comment by gadde-cern** [comment]
If we go down that path, I will tell you!
