### ISSUE TITLE
how to add timestamp in batch message publishing 

### ISSUE THREAD

**Issue by gmdun** [edenhill/librdkafka#2044]
As i can see we can use rd_kafka_producev API to add timestamps in single Kafka message, but what API we need to use to add add timestamp in batch publish  

librdkafka API

**Comment by edenhill** [comment]
That is not possible, you will need to use producev().

Generally there is little reason to use produce_batch().

**Comment by gmdun** [comment]
ok, thanks. if we use `api.version.request=true` then can we set the timestamp for the batch messages ?

**Comment by edenhill** [comment]
api.version.request=true (default) is required for timestamp support. But the produce_batch() interface does not expose any timestamps, you will need to use producev()

**Comment by gmdun** [comment]
oh, we are using rd_kafka_produce_batch in our application very frequently. is there chances to add the timestamp in rd_kafka_produce_batch API in upcoming librdkafka release. or is there a way to achieve timestamp in batch API ?

**Comment by edenhill** [comment]
Timestamps can't be added to the produce_batch() since the rd_kafka_message_t struct can't be safely extended without breaking the ABI compatibility guarantee.

Why do you need to use the batch API?
The produce_batch() message batches are not the same as the Kafka protocol message batches (MessageSets), and the batches you pass will not necessarily end up in the same protocol batch.
To control the batch behaviour, instead look at `linger.ms` and `batch.num.messages`.
