### ISSUE TITLE
Expose partition hashing to producer client

### ISSUE THREAD

**Issue by shanson7** [edenhill/librdkafka#2046]
**Enhancement Request**

Currently, we provide a key to do consistent partitioning in kafka. However, in our case our key is about as large as our message (about 32 bytes) and we produce ~5 million of these per second. This leads to high overhead. We don't actually need the key (it is computable from the message body, if needed), so ideally we would just ask rdkafka "Which partition would you put this in?" and use the result from that in our call. Is this something that could be exposed as a utility function?

**Comment by shanson7** [comment]
Note: we use the C++ API, if that makes a difference

**Comment by rnpridgeon** [comment]
All of the built-in partitioners are exposed in rdkafka.h which you can leverage from you C++ code. 

https://github.com/edenhill/librdkafka/blob/849c066b559950b02e37a69256f0cb7b04381d0e/src/rdkafka.h#L1914-L1997

You should be able to make use of this with the use of `extern "C"`. 
```
#include <stdio.h>
extern "C" {
   #include <librdkafka/rdkafka.h>
}
```

That's not to say they shouldn't be exposed via the C++ API as well but hopefully this can unblock you until a decision can be made on when/if that should happen.

**Comment by edenhill** [comment]
@shanson7 
I'm curious what kind of performance penalty you see with message keys and where: producer? broker? consumer? consuming application?

We could add a new produce flag MSG_F_NO_KEY that only uses the key for partitioning but does not include it in the message. This might have an effect on downstream streaming systems that needs to re-partitioning.
The key would still need to be copied by librdkafka, since the partitioning might be delayed if the full metadata is not (yet) known, so if this is the source of the extra overhead it would not help.

@rnpridgeon 
The builtin partitioners are unfortunately not directly callable since they might call `rd_kafka_partition_available()` which must only be called from within a librdkafka-triggered partitioner. And the application would need to look up the partition_cnt first.

**Comment by shanson7** [comment]
@edenhill - The penalty is mostly in the size. It increases the payload size over the network, on disk (and then over the network again, whenever consumers consume). Adding such a `MSG_F_NO_KEY` option would be very nice for my case, though I'd still be interested in exposing the partitioners.

**Comment by shanson7** [comment]
Is this done or not going to be done?

**Comment by edenhill** [comment]
Sorry, not enough demand for this to make it in.
Reopen if this is a show stopper.
