### ISSUE TITLE
Pre-mature EOF on binary files.

### ISSUE THREAD

**Issue by petermpham** [edenhill/librdkafka#205]
Hi,
I wonder anyone here having problem with consuming binary data on Kafka using librdkafka?
I tried to send a binary file to kafka. The sending part is OK. Yet, when our consumer reads the partition the file is sent to, it  always detects EOF before the full file is consumed.

I knew Kafka does provide support for binary data. I suspected I may have mis-configured something.
Botth producer and consumer were using librdkafka for interface to Kafka.

Any insights would be very much appreciated.

Thanks,
Peter

**Comment by edenhill** [comment]
Hi,

Sounds weird.

What is the size of the file?
Is the EOF at some specific length or does it vary?
Will a tool like kafkacat (also using librdkafka) consume it correctly?

**Comment by petermpham** [comment]
Hi, Edenhill,

I debugged the consumer and found that its reading from Kafka is correct.
I think, somehow, the recv data are not written/flushed to the file. (The same code 
works fine for text file, the file was open in binary mode.)

BTW, is it right that the acknowledgement of the delivery of the latter packet implied 
the previous ones also successfully sent to Kafka? I assumed so, as sometime I received 
fewer "Message delivery" acks than those were sent.

Thanks,
Peter

**Comment by edenhill** [comment]
Okay, so is the issue sorted out with adding fflush() calls to your code?


**Re acks**
Each message produced (where `rd_kafka_produce*()` does not return -1) will have its
delivery report callback (`dr_cb` or `dr_msg_cb`) called eventually.
* If you are sending messages to the same topic+partition the dr_cb's should be called in the same order you produced the messages since ordering is guaranteed within a single topic+partition only.
* If you produce multiple topics or partitions (e.g., by using `RD_KAFKA_PARTITION_UA` and a partitioner (default does randomization)) then ordering is not relevant and callbacks will be unordered.
* Tthis Wiki on termination might be of interest, especially point 1): https://github.com/edenhill/librdkafka/wiki/Proper-termination-sequence
