### ISSUE TITLE
Lossless consumer group

### ISSUE THREAD

**Issue by bshafiee** [edenhill/librdkafka#2060]
Description
===========
I am trying to design a reliable kafka message processor using librdkafka (go client) and was confused by documentation so decided to clarify my understanding. 

The application will use a high level consumer to subscribe to a series of topics on different brokers. It reads a message from `topic1`, processes it and produces it back to the `topic1_processed` topic (similar to what kafka mirror-maker does but with some processing involved).

Now the requirement is all messages need to be consumed and there should be `NO LOSS`. My understanding was I can achieve this by the following loop:
```
  c = ConsumerGroup('my_group', 'topic1')
  p = Producer('topic1_processed')

 while(true) {
     msg = c.ReadMessage()
     processed_msg = process(msg)
     
     if (p.producer(processed_msg) == no_error) {
         c.CommitMessage(msg)
     } 
    // else it should read the same message again and try again.
}
```
I was wondering if this loop makes sense and how can I achieve it via the proper configuration of librdkafka. In particular, since `c.CommitMessage` is blocking it will really slowdown things, from 50K msg/sec to 10 msg/sec! However, if I remove it, I believe enabled `enable.auto.commit` will commit the offsets regardless of if my processing and producing succeeded or not. So I am not really sure what's the right comibination not to sacrifice performance and still have a loss-less loop in place. 

Finally, I had another question about if I can add topic to the consumer at runtime without stopping and starting them again. 

Thanks in advance,

**Comment by edenhill** [comment]
There are two levels of offset commit in librdkafka:
 * the offset store contains per-partition offsets to commit and resides in memory.
 * the actual offset commit on the broker, which uses either explicitly specified offsets (to Commit..()) or the stored offsets.

By default StoreOffsets() is called automatically when the message is retrieved from the internal fetch queue before passing to the application, the stored offset will be used by the next auto commit (or calling Commit() without arguments).

This means that a message's offset can be committed prior to your application finishing processing the message, in case of crash this could lead to skipped messages.

The solution is to disable the automatic store offset and do an explicit StoreOffsets are processing, you can still use auto commits. This ensures messages are seen at least once by the consumer.
Disable auto offset store with `enable.auto.offset.store=false`.

As for your processing loop, there is no easy/cheap way to have ReadMessage() return the same message again, short of seeking back - which comes at a resource cost due to messages in queues being thrown away. Instead I suggest you loop over the message yourself until processing succeeds.

So your example would look something like this:
```
c = ConsumerGroup('my_group', 'topic1') // make sure to set enable.auto.offset.store=false
  p = Producer('topic1_processed')

 while(true) {
     msg = c.ReadMessage()
     while not processed {
       processed_msg = process(msg)
        
       if (p.producer(processed_msg) == no_error) {
         c.StoreOffsets([msg.TopicPartition]))
         break
       } 
       // retrying: continue
     }
  }
```

**Comment by edenhill** [comment]
You can change your subscription by calling Subscribe() with a new set of topics.

If you know the format of future topics you can use regex subscription to match the topic name(s). You do this by prefixing the topic name with `^` in the list you pass to Subscribe(), .e.g:
`c.Subscribe(..{"^my_regex_topic_[0-9]$", "non-regex", ..})`
this will rebalance the entire group.

**Comment by bshafiee** [comment]
Hi @edenhill , 

Thank you so much for the detailed explanation! 🙏🏻 
The difficulty with retiring scheme you mentioned is my processing involves writing back to another topic (which is done asynchronously for performance reasons). Now if I produce synchronously, it will become too slow. Instead, similar to what you mentioned, I did try seeking back with `enable.auto.offset.store=false` (but auto commit enabled). It seems to work fine, something like:
```
c = ConsumerGroup('my_group', 'topic1') // make sure to set enable.auto.offset.store=false
 p = Producer('topic1_processed')

 while(true) {
     msg = c.ReadMessage()
     while not processed {
       process_async(msg)
     }
  }

while(true) { //async process loop
  if success {
     c.storeoffset(msg)
  } else {
     c.seek(msg.topicPartition)
  }
}
```
Obviously, this means if I have acked some later messages I will be reproducing those (but then again this is the same as kafka guarantee `at least once`) which is acceptable for our use case, and since process errors are rare. This is not a big deal.  I might in future, try to improve it to have `exactly once` guarantee but keeping a map of out of order acks, so not to reprocess them but too complicated for now. But I guess it will be a cool thing to build similar to how TCP ack window works!

I will try to re-scubscribe upon finding new topic! Thanks again!
