### ISSUE TITLE
Kerberos authentication allows arbitrary process execution during system(kinit_string)

### ISSUE THREAD

**Issue by cfinkenstadt** [edenhill/librdkafka#2110]
Unrelated to #1303 

Description
===========
librdkafka allows arbitrary process execution in Kerberos authentication mode.

How to reproduce
================
```
Configuration { 
  "sasl.kerberos.kinit.cmd": "/usr/games/startrek"
}
```

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): 0.11.5
 - [x] Apache Kafka version: immaterial
 - [x] librdkafka client configuration: sasl.kerberos.kinit.cmd=/usr/games/startrek
 - [x] Operating system: Unix System III and following
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [x] Critical issue

**Comment by edenhill** [comment]
Yes, since the config takes any path this is expected, I don't see a way for librdkafka to verify or enforce a certain executable.
If an application wants to prevent its users from configuring rogue executables it will need to do this in its configuration layer and check the config value string before being passed to conf_set().
