### ISSUE TITLE
Publish using gathered I/O

### ISSUE THREAD

**Issue by singularsyntax** [edenhill/librdkafka#2219]
Hello,

Would it be feasible to support gathered I/O in librdkafka when producing messages? I need to assemble several items of data into a single Kafka record, but the API for the source of the data does not provide for this and I'd like to avoid the overhead of an additional memory copy into an intermediate buffer.

It could work something like this:

    struct iovec bufs[2];

    bufs[0].iov_base = (void *) buf_one;
    bufs[0].iov_len = /* ... */;
    bufs[1].iov_base = (void *) buf_two;
    bufs[1].iov_len = /* ... */;

    rd_kafka_resp_err_t err = rd_kafka_producev(
        rk,
        RD_KAFKA_V_TOPIC(topic),
        RD_KAFKA_V_PARTITION(partition),
        RD_KAFKA_V_MSGFLAGS(RD_KAFKA_MSG_F_COPY),
        RD_KAFKA_V_IOVEC(bufs, 2),
        RD_KAFKA_V_END);

Does this seem like a useful feature to add to the producer API?

**Comment by edenhill** [comment]
For your suggested use-case with MSG_F_COPY I think this would be very easy to add to rd_kafka_producev() as you suggested (PRs welcome!).

But if you take it one step further, it would be feasible to pass an iovec without using MSG_F_COPY, to have librdkafka reference the original ivoec pointers.
Since librdkafka uses scatter-gather/iovecs (if available) on the request-buffer and socket layer, this would be possible to do to get iovec and zero-copy support working together. But that's a somewhat bigger effort, and it would change the meaning of rkmessage.payload in the delivery report callback to be a pointer to iovec rather than the buffer.

**Comment by singularsyntax** [comment]
Yes, I see what you're getting at - the application can assemble the single buffer prior to calling `produce()`, and use `RD_KAFKA_MSG_F_FREE` instead of `RD_KAFKA_MSG_F_COPY` to avoid an extra memory copy. This will work fine for my use case. I didn't consider that possibility because I'm new to librdkafka's API, the code in the examples directory use `RD_KAFKA_MSG_F_COPY` and I was unaware of `RD_KAFKA_MSG_F_FREE`. It pays to RTFM!

End-to-end zero-copy support would be interesting, but doesn't make sense for my immediate use case because the API of the data source doesn't employ `struct iovec` and the liveness of the data structures it produces last for only one iteration of its poll()-like call. Since librdkafka message delivery is asynchronous, they must thus be copied immediately prior to calling produce().

With regards to your comment about interpretation of rkmessage.payload in the delivery reports, with an eventual eye towards zero-copy - since the `payload` field of `rd_kafka_message_t` is already defined as a `void *`, seems like it could just as well be a `struct iovec *`. If the application needs interpretive context, it could provide that somehow in its opaque data.

**Comment by edenhill** [comment]
Thanks for your input.
