### ISSUE TITLE
failed: err: Local: Authentication failure: (errno: Invalid argument)

### ISSUE THREAD

**Issue by write2jaydeep** [edenhill/librdkafka#2225]
Read the FAQ first: https://github.com/edenhill/librdkafka/wiki/FAQ

Description
==============
can you please observe log and let me know what is the problem?

1550066105.760 RDKAFKA-7-AUTH: rdkafka#producer-1: [thrd:sasl_plaintext://mydomain.com:5001/bootstrap]: sasl_plaintext://mydomain.com:5001/bootstrap: Auth in state APIVERSION_QUERY (handshake supported)
1550066105.760 RDKAFKA-7-STATE: rdkafka#producer-1: [thrd:sasl_plaintext://mydomain.com:5001/bootstrap]: sasl_plaintext://mydomain.com:5001/bootstrap: Broker changed state APIVERSION_QUERY -> AUTH_HANDSHAKE
1550066105.760 RDKAFKA-7-BROADCAST: rdkafka#producer-1: [thrd:sasl_plaintext://mydomain.com:5001/bootstrap]: Broadcasting state change
1550066105.760 RDKAFKA-7-SEND: rdkafka#producer-1: [thrd:sasl_plaintext://mydomain.com:5001/bootstrap]: sasl_plaintext://mydomain.com:5001/bootstrap: Sent SaslHandshakeRequest (v0, 29 bytes @ 0, CorrId 8)
1550066105.761 RDKAFKA-7-RECV: rdkafka#producer-1: [thrd:sasl_plaintext://mydomain.com:5001/bootstrap]: sasl_plaintext://mydomain.com:5001/bootstrap: Received SaslHandshakeResponse (v0, 14 bytes, CorrId 8, rtt 0.88ms)
1550066105.761 RDKAFKA-7-SASLMECHS: rdkafka#producer-1: [thrd:sasl_plaintext://mydomain.com:5001/bootstrap]: sasl_plaintext://mydomain.com:5001/bootstrap: Broker supported SASL mechanisms: GSSAPI
1550066105.761 RDKAFKA-7-AUTH: rdkafka#producer-1: [thrd:sasl_plaintext://mydomain.com:5001/bootstrap]: sasl_plaintext://mydomain.com:5001/bootstrap: Auth in state AUTH_HANDSHAKE (handshake supported)
1550066105.761 RDKAFKA-7-STATE: rdkafka#producer-1: [thrd:sasl_plaintext://mydomain.com:5001/bootstrap]: sasl_plaintext://mydomain.com:5001/bootstrap: Broker changed state AUTH_HANDSHAKE -> AUTH
1550066105.761 RDKAFKA-7-BROADCAST: rdkafka#producer-1: [thrd:sasl_plaintext://mydomain.com:5001/bootstrap]: Broadcasting state change
1550066105.761 RDKAFKA-7-SASL: rdkafka#producer-1: [thrd:sasl_plaintext://mydomain.com:5001/bootstrap]: sasl_plaintext://mydomain.com:5001/bootstrap: Initializing SASL client: service name kafkaclient, hostname mydomain.com, mechanisms GSSAPI, provider Cyrus
1550066105.761 RDKAFKA-7-SASLREFRESH: rdkafka#producer-1: [thrd:sasl_plaintext://mydomain.com:5001/bootstrap]: sasl_plaintext://mydomain.com:5001/bootstrap: Refreshing SASL keys with command: kinit -S "kafkaclient/mydomain.com" -k -t "/home/jaydeep/kafka_2.11-1.1.1/config/stratusoft1.keytab" kafkaclient/mydomain.com@MYREALM.COM
1550066105.769 RDKAFKA-7-SASLREFRESH: rdkafka#producer-1: [thrd:sasl_plaintext://mydomain.com:5001/bootstrap]: sasl_plaintext://mydomain.com:5001/bootstrap: SASL key refreshed
1550066105.770 RDKAFKA-7-SASL: rdkafka#producer-1: [thrd:sasl_plaintext://mydomain.com:5001/bootstrap]: sasl_plaintext://mydomain.com:5001/bootstrap: My supported SASL mechanisms: GS2-IAKERB GS2-KRB5 SCRAM-SHA-1 GSSAPI GSS-SPNEGO DIGEST-MD5 EXTERNAL NTLM CRAM-MD5 LOGIN PLAIN ANONYMOUS
1550066105.771 RDKAFKA-7-SASL: rdkafka#producer-1: [thrd:sasl_plaintext://mydomain.com:5001/bootstrap]: sasl_plaintext://mydomain.com:5001/bootstrap: Send SASL frame to broker (698 bytes)
1550066105.776 RDKAFKA-7-BROKERFAIL: rdkafka#producer-1: [thrd:sasl_plaintext://mydomain.com:5001/bootstrap]: sasl_plaintext://mydomain.com:5001/bootstrap: failed: err: Local: Authentication failure: (errno: Invalid argument)
1550066105.776 RDKAFKA-3-FAIL: rdkafka#producer-1: [thrd:sasl_plaintext://mydomain.com:5001/bootstrap]: sasl_plaintext://mydomain.com:5001/bootstrap: SASL authentication failure: Disconnected: check client GSSAPI credentials and broker logs (after 15ms in state AUTH)

**IMPORTANT**: Always try to reproduce the issue on the latest released version (see https://github.com/edenhill/librdkafka/releases), if it can't be reproduced on the latest version the issue has been fixed.

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): 1.0.0
 - [x] Apache Kafka version: 1.1.1
 - [x] librdkafka client configuration: 
builtin.features=sasl_gssapi
security.protocol=sasl_plaintext
sasl.mechanisms=GSSAPI
sasl.kerberos.service.name=kafkaclient
sasl.kerberos.principal=kafkaclient/mydomain.com@MYREALM.COM
sasl.kerberos.keytab=mydomain.keytab

 - [x] Operating system:  Ubuntu 16.04.5 LTS

**Comment by rnpridgeon** [comment]
@write2jaydeep,

Could you please confirm the following:

1. Your broker's principal is `kafkaclient/{broker.host.name}@REALM`

If you are unsure you can check the broker's JAAS file. It should looks like the example in the docs linked below. If not it will need to be because the client will ask the kdc for a service ticket in the form of {sasl.kerberos.service.name}/{broker host name}@{REALM}

https://docs.confluent.io/current/kafka/authentication_sasl/authentication_sasl_gssapi.html#kafka-sasl-auth-gssapi

2. The client's principal is also `kafkaclient/{broker.host.name}@REALM. If so can you confirm that you are able to get both a TGT and a service ticket manually by executing the following commands from the host where you are running the client. 

```
kdestroy 

kinit -S "kafkaclient/mydomain.com" -k -t "/home/jaydeep/kafka_2.11-1.1.1/config/stratusoft1.keytab" kafkaclient/mydomain.com@MYREALM.COM

klist
```

If successful you should see both in your credentials cache which is printed upon execution of klist. 

If this is successful it would be good to capture the SASL handshake from start to failure by grabbing a TCP dump. Then we can load the contents into wireshark and see where the handshake falls apart. 

If it's not successful you will want to review the kerberos documentation linked above along with the librdkafka kerberos wiki which I will include below. 

https://github.com/edenhill/librdkafka/wiki/Using-SASL-with-librdkafka

**Comment by write2jaydeep** [comment]
@rnpridgeon Thanks, man!
1. Your broker's principal is `kafkaclient/{broker.host.name}@REALM`

this was the problem. broker hostname was different in **server.properties**
