### ISSUE TITLE
CPU ratio increase while partition number increase

### ISSUE THREAD

**Issue by eelyaj** [edenhill/librdkafka#2270]
Description
===========
I have one topic in mys system to receive log message.
the speed is 130K/sec. I found that larger partition number will increase CPU ratio.
partition number    CPU
10                           120%
100                         140%
500                         190%

so for one producer, larger partition number will decrease throughput.
Is this how librdkafka wroks? Is there any parameters could increase throughput under larger partition number.
Thanks.

these are parameters I set.
"queue.buffering.max.ms": "1000",
"queue.buffering.max.messages": "1000000"
"acks": "1",
"request.timeout.ms": "60000",
"batch.num.messages": "1000000",
"compression.codec": "lz4"
"retention.ms": "3600000"
replication_factor=1

librdkafka version 0.11.6
Kafka 1.0.0
3 brokers

**Comment by edenhill** [comment]
librdkafka has one thread per broker, and a specific broker thread will handle all partitions for which that broker is the leader.
As there are log(N) (N=partitions_for_this_broker) scans in the producer code, it is likely that a high-partitioned topic but with few leader brokers will lead to increased CPU usage.

As for the CPU usage numbers, those do look high.
How many (v)cores does your machine have?
Since librdkafka is multi-threaded we recommend at least 4 vcores per client instance.

**Comment by eelyaj** [comment]
the machine has 4 cores (8 vcpu). In my application, there are 6 threads, each has one producer instance.
I found a way to reduce cpu rate. I assigned partitions for each thread. The code is like this:

    RdKafka::ErrorCode resp = producer->produce(topic, partition, RdKafka::Producer::RK_MSG_COPY, buf, length, key, keyLen, timestamp, 0);

I calculate "partition" number for each thread. 
thread 1 use 0~19   
thread 2 use 20~39  
thread 3 use 40~59  
.........

by doing this, the cpu rate decreased.
