### ISSUE TITLE
Checking if topic is alive and active

### ISSUE THREAD

**Issue by ekdoan** [edenhill/librdkafka#2306]
Read the FAQ first: https://github.com/edenhill/librdkafka/wiki/FAQ

Description
===========
Is there a way to access consumer heartbeats in librdkafka api so that I can check if a topic is active?

**IMPORTANT**: Always try to reproduce the issue on the latest released version (see https://github.com/edenhill/librdkafka/releases), if it can't be reproduced on the latest version the issue has been fixed.

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): 0.11.5-1.el7.x86_64`
 - [x] Apache Kafka version: `2.11.1.1.1-1.el7.x86_64`
 - [] librdkafka client configuration: `<REPLACE with e.g., message.timeout.ms=123, auto.reset.offset=earliest, ..>`
 - [x] Operating system: `Redhat Linux`
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
The consumer heartbeats are not exposed to the application, and does not indicate if a topic is active (I'm assuming you mean a topic has active leader brokers for its partitions), the heartbeats are used by the broker to make sure the consumer itself is active.
Should the heartbeats fail the consumer will be kicked out of the consumer group and loose its assigned partitions.

As for checking livelyness of a topic; this is a bit tricky since a topic is made up of multiple partitions, and each partition may have a unique leader broker. And while a partition may have a leader assigned, that leader broker may not be reachable for whatever reason.

You can use get_metadata() to get the current leaders for a topic's partitions, or more conventiantly look at the statistics from the client (statistics.interval.ms and conf_set_stats_cb()) to see the current partition and leader states:
https://github.com/edenhill/librdkafka/blob/master/STATISTICS.md
