### ISSUE TITLE
REQTMOUT issue

### ISSUE THREAD

**Issue by silviucpp** [edenhill/librdkafka#2350]
Hello,

I'm using librdkafka v0.11.6 and very offen on my cluster I receive in logs:

```
REQTMOUT [thrd:prelive-kafka03.zz.toronto:9092/bootstrap]: prelive-kafka03.zz.toronto:9092/bootstrap: Timed out 0 in-flight, 1 retry-queued, 0 out-queue, 0 partially-sent requests
```

Seems the error comes in loop and doesn't stop will I restart the app. 

Any clue from where this can be ? Other visible effects are not. All messages are produced properly.

Silviu

**Comment by edenhill** [comment]
There's a bunch of request/timeout fixes since v0.11.6, could you try to reproduce this on the latest librdkafka version (v1.0.1)?

**Comment by silviucpp** [comment]
OK will do !

**Comment by silviucpp** [comment]
I'll close it for the moment. I upgraded and in the last days all clear. 

I'll reopen in case will see it again.

**Comment by Fankouch** [comment]
Hello,
We are using  librdkafka  0.11.6-7.2.1 and i receive in logs:

	RDKAFKA-4-REQTMOUT: rdkafka#consumer-1: [thrd:sasl_ssl://bootstrap.url]: sasl_ssl://bootstrap.url:443/bootstrap: Timed out 0 in-flight, 1 retry-queued, 0 out-queue, 0 partially-sent requests

I read that after the upgrade to version 1.0.1, the problem is solved.
But with zypper, I can't find the latest version of librdkafka. Or am I doing something wrong!
Where can I find the latest version of librdkafka for my environment?

Thanks for any help

Virtualization: vmware
Operating System: SUSE Linux Enterprise Server 12 SP5
CPE OS Name: cpe:/o:suse:sles:12:sp5
Kernel: Linux 4.12.14-122.116-default
Architecture: x86-64

S  | Name             | Type       | Version      | Arch   | Repository
---+------------------+------------+--------------+--------+----------------------
   | librdkafka       | srcpackage | 0.11.6-7.2.1 | noarch | SLE12-SP5-SDK-Updates
   | librdkafka       | srcpackage | 0.11.6-7.2.1 | noarch | SLE12-SP5-Updates
i+ | librdkafka-devel | package    | 0.11.6-7.2.1 | x86_64 | SLE12-SP5-SDK-Updates
v  | librdkafka-devel | package    | 0.11.6-1.3.1 | x86_64 | SLE12-SP5-SDK-Pool
i  | librdkafka1      | package    | 0.11.6-7.2.1 | x86_64 | SLE12-SP5-Updates
v  | librdkafka1      | package    | 0.11.6-1.3.1 | x86_64 | SLE12-SP5-Pool
