### ISSUE TITLE
Will asynchronous consumer APIs be supported?

### ISSUE THREAD

**Issue by michema** [edenhill/librdkafka#241]
Hello,

It looks like the current consumer APIs (e.g consumer) are synchronous which are controlled by the parameter of "timeout_ms". The workaround to make it asynchronous is to set the "timeout_ms" as 0.

Will be better to have a separate asynchronous consumer APIs?

Thanks

**Comment by edenhill** [comment]
Hi,

what exactly do you mean by an asynchronous consumer API?
In what way do you envision that working?

Regards,
Magnus

**Comment by michema** [comment]
Hi,

Basically, I would like to receive a message without any waiting time.

Thanks

**Comment by edenhill** [comment]
You get non-blocking behaviour by supplying `timeout_ms=0`.
I.e.:
 * if a message is available - return immediately (this is always the case regardless of timeout_ms)
 * if no message is available - return immediately

**Comment by edenhill** [comment]
Which you stated yourself in your initial post :)

**Comment by edenhill** [comment]
I dont really see a reason for creating a separate API when the current API supports it though.

**Comment by michema** [comment]
Thanks for your reply. I have a another quick question. If I set timeout_ms=0, how can the consumer decide if there is no more message coming? Should I use poll(), like
                    poll(0);
                    consume(0);

**Comment by edenhill** [comment]
If you call  consume with timeout_ms=0 it will return NULL if there are no messages, otherwise a message.

**Comment by edenhill** [comment]
Does this solve your problem?

**Comment by michema** [comment]
Yes, thanks.

**Comment by cantappa** [comment]
Although this topic has already been closed, I got a question to the asynchronous behavior of the consume message. 
As far as I got it setting the timeout to 0 causes the thread that is calling the consume method of the consumer in some kind of a while(true) loop to still be busy waiting when no message is coming.
I am looking for a way to avoid this and instead provide a callback function which is called whenever a message is received without my main thread being busy waiting. Is there a way to implement this?

**Comment by edenhill** [comment]
It is a conscious decision in librdkafka not to trigger user callbacks from non-user (librdkafka internal) threads, because it would require the application developer to fully understand and grasp thread safety (which is hard) - and for the people who do, creating an application thread that does the polling is trivial.
And that is also the answer: create an application thread that does the polling. :)

**Comment by cantappa** [comment]
Thanks for your fast answer and the hint! I will try it with my on application thread that does the polling :-).

**Comment by fex** [comment]
@edenhill 
Good that the developers of libpthread (or nowadays of std::thread) did not have the same opinion...

No offense, but
1. developing in C/C++ is already a hard task and given that programmers are somewhat intelligent, I'm eager that they would understand multi threading eventually ;)
1. This mixture of polling **and** backcalls is uncommon and only confuses programmers, so the oposite happens what you actually planned to do (backcalls are not necessary since you could simply return data from the polling function)
1. It would be nice, if the developer had the chance to use a polling- **or** a backcall- scheme

One last question (repetition of that from @cantappa): How to avoid the polling thread to do busy waiting (on 100% cpu)? And on the same time, work on callbacks as soon as possible?

**Comment by fex** [comment]
>  How to avoid the polling thread to do busy waiting (on 100% cpu)? And on the same time, work on callbacks as soon as possible?

Sorry for asking these rhetorical questions. Obviously, the requirements contradict each other with the current design of librdkafka. I think, _easiness of use_ does not outweigh this shortcoming.

**Comment by edenhill** [comment]
rd_kafka_poll(), et.al, will block for up to timeout_ms for a new event/callback/message, but they will not busy-loop (they block on a cond-var).

**Comment by edenhill** [comment]
There's also an event API that returns event objects rather than trigger callbacks, see https://github.com/edenhill/librdkafka/blob/master/src/rdkafka.h#L3452
