### ISSUE TITLE
Question: batch produce

### ISSUE THREAD

**Issue by nick-zh** [edenhill/librdkafka#2415]
I am trying to port this function to php and looked a bit into the code to understand it better.
I saw this line: https://github.com/edenhill/librdkafka/blob/master/src/rdkafka_msg.c#L517
Is there a reason that headers are not copied to the new producer message?
Will i be unable to set headers for batch produce or am i misunderstanding something?
Thanks a lot in advance for taking the time and the help!

**Comment by edenhill** [comment]
The batch produce API is limited due to lacking fields for Headers, etc, in the message struct, and the API will be deprecated.

There is typically no need for batching operations, it does not provide any semantic gain, and the performance gain is microscopical.

Instead use rd_kafka_producev() and produce one message at the time.
