### ISSUE TITLE
Maximum number of consumed messages per rd_kafka_consume_callback()

### ISSUE THREAD

**Issue by michema** [edenhill/librdkafka#248]
Hi,

Is there a way to control the maximum number of consumed messages for each call of rd_kafka_consume_callback().

Thanks

**Comment by edenhill** [comment]
Currently no.
It would be trivial to add but that would break the API (which is guaranteed not to be broken).
Would a configuration property (which is immutable after `rd_kafka_[topic_]new()`) be an acceptable workaround for the time being?

**Comment by michema** [comment]
What is the name of this configuration property? And how to set it?

Thanks

**Comment by edenhill** [comment]
There isn't one yet, but I can add one for you if you feel that is an acceptable workaround for now.

**Comment by michema** [comment]
If so, that would be good.

Thanks,

**Comment by michema** [comment]
Hi, Magnus:

If we plan to introduce a property to control the maximum number of consumed messages for rd_kafka_consume_callback() , do you think its performance will be similar with rd_kafka_consume_batch()?

**Comment by edenhill** [comment]
consume_callback() will always be the fastest because it minimizes temporary storage space and lock access.

_batch() is somewhat of an odd bird performance wise, theoretically it should be almost as fast as callback(), and that was my assumption until I got reports of _batch() being slower not only to _callback() but to the single message consume()!

It turns out that, depending on batch message array size, the batch interface scres up the CPU memory caches and suffers a large performance hit.

This seems to vary between systems and array sizes, so your mileage may vary.

**Comment by edenhill** [comment]
Can you try out the new topic config property `consume.callback.max.messages`?
