### ISSUE TITLE
Feature Request: Unit Testing Stub

### ISSUE THREAD

**Issue by mpribble** [edenhill/librdkafka#2536]
Description
===========
I have written a kafka publisher that makes use of librdkafka, and from my preliminary testing, it is clearly functioning properly. Now I would like to unit test my code. A simple unit test I think is reasonable is to call my write() function, which invokes rd_kafka_produce(), and verify that the message was written due to my delivery report callback being called.

The hang up here is that such a test requires running an actual Kafka broker for my unit test to connect to. I could do this, and it appears that's what librdkafka does for its own unit tests. However, this is not a great solution, since in my mind it doesn't really qualify as a unit test due to the external dependency.

It would be great if there were a stub feature of librdkafka such that I could attempt the unit testing I want. Basically, there could be a "stub" build of the library that could be linked in for unit testing.

An alternative could be to run a C++ broker inside the actual application. Technically this could be done outside the control of librdkafka. But, the only attempt I can find at this is https://github.com/Wramberg/kafkabrokerstub, which doesn't seem to be under active development and thus doesn't seem promising.

How to reproduce
================
N/A

Checklist
=========
 - [x] librdkafka version (release number or git tag): v1.2.0
 - [x] Apache Kafka version: N/A
 - [x] librdkafka client configuration: N/A
 - [x] Operating system: N/A
 - [x] Provide logs (with `debug=..` as necessary) from librdkafka N/A
 - [x] Provide broker log excerpts N/A
 - [x] Critical issue N/A

**Comment by zhanghaowx** [comment]
I think this feature would be super useful to 1) verify if librdkafka is used correctly 2) benchmark the performance with different configurations.

**Comment by edenhill** [comment]
We're planning to add a python-based mock broker to be able to craft specific protocol responses for use with our unit tests, but I'm not sure this will be that helpful for application-level unit testing since it still requires setting up a separate process.

Instead I think it is better for librdkafka to provide a high-level mock broker that allows produce, consume, etc, simply through configuration - this will allow any application to run in unit test mode without any application changes.

What APIs do you want to be unit-testable?:
 * produce() -> delivery reports. With and without errors.
 * subscribe(), assign(), consumer_poll() - consume mock messages and trigger various error events.

**Comment by mpribble** [comment]
This is great!

What you have listed would get me quite far. I would also like to see consume(), since I don't use the high-level consumer.

**Comment by edenhill** [comment]
librdkafka now provides a built-in mock cluster:
https://github.com/edenhill/librdkafka/blob/master/src/rdkafka_mock.h#L39

**Comment by mpribble** [comment]
@edenhill I've updated my existing unit tests to use the mock cluster, and it works great. Thanks so much for implementing this feature.

**Comment by edenhill** [comment]
@mpribble Yay! Great to hear!
