### ISSUE TITLE
Feature request: Add client.dns.lookup with librdkafka 

### ISSUE THREAD

**Issue by MosheBlumbergX** [edenhill/librdkafka#2549]
It will be good to include `client.dns.lookup` so it will be consistent with the java libs.

**Comment by edenhill** [comment]
librdkafka already supports DNS round-robin, and it is always enabled.

**Comment by MosheBlumbergX** [comment]
Thank you!

**Comment by edenhill** [comment]
To be clear, librdkafka's behaviour is analogue to `client.dns.lookup= use_all_dns_ips`.
We don't support the canonical one, which I guess means treating each resolved-to address as its own broker.

**Comment by sysThematic** [comment]
There is a Note in Try It section at the link below, which tells the broker name must exactly match the hostname part of the broker's principal. 
https://github.com/edenhill/librdkafka/wiki/Using-SASL-with-librdkafka#6-try-it
That info conflicts with this one because with use_all_dns_ips I can use any dns alias as long as the IP has a valid PTR which matches broker's principal. Isn't it right @edenhill ?

**Comment by edenhill** [comment]
@sysThematic That's no longer correct, we used to have the broker's hostname as part of the service principal, but that was fixed/removed last year.

I've updated the wiki, thanks for pointing it out.

**Comment by sysThematic** [comment]
I am using kafkacat on linux and it is working as expected.
However, we've another issue for confluent-kafka-dotnet 1.4.3 librdkafka 1.4.2 on windows.
Is there a known issue on SASL via SSPI on  Windows?
When we use dnsaliasnode01 instead of node01 (which is the part of broker's principle) we get following error:

 [KAFKA_ERROR] Message:sasl_plaintext://dnsaliasnode01:9092/bootstrap: Failed to initialize SASL authentication: InitializeSecurityContext failed: Target unknown (0x80090303) (after 0ms in state AUTH_REQ), Error:sasl_plaintext://dnsaliasnode01:9092/bootstrap: Failed to initialize SASL authentication: InitializeSecurityContext failed: Target unknown (0x80090303) (after 0ms in state AUTH_REQ)

**Comment by edenhill** [comment]
@rnpridgeon Any ideas?

**Comment by omersiar** [comment]
Hello,

as of v2.2.0 we are investigating a quirky behavior involving DNS and TLS authentication.

When application's bootstrap configuration points to a dns name let's say `kafka-az1.company.com` and if this record returns multiple A record application is working as expected.

But when mixing up bootstrap configuration with both including a multiple and a single record like 
`kafka-az1.company.com,broker1-at-az2.company.com`
Application emits:

```
9093/22:ssl://broker1-at-az2.company.com:9093/22<LINK:END>:> Connection setup timed out in state AUTH_REQ (after 180701ms in state AUTH_REQ)
``` 
errors

BTW `broker1-at-az2.company.com` returns single A record.
