### ISSUE TITLE
on which port my consumer or producer is connecting to kafka server? Can we hardcode the port on which my consumer should listen on or my producer should post on?

### ISSUE THREAD

**Issue by chakri-stark** [edenhill/librdkafka#2595]
Hi,

on which port Kafka consumer or producer is connecting to the Kafka server? Can we hardcode the port on which my consumer should listen to or my producer can post on?

**Comment by edenhill** [comment]
Kafka clients (producers, consumers) don't listen to a port, they connect to the brokers' listener ports.

**Comment by chakri-stark** [comment]
Hi edenhill, Thanks for the reply. I would like to fix a port on which the clients should be contacting with the server. So, can you please point out where I can hardcode the port to avoid it from choosing a random one instead. 

Thanks,
chakri

**Comment by edenhill** [comment]
Kafka listener ports explained here:
https://rmoff.net/2018/08/02/kafka-listeners-explained/

As for specifying the client-side source port:
you would need to set up a socket_cb or connect_cb to bind the socket to a local port (see https://github.com/edenhill/librdkafka/blob/master/src/rdkafka.h#L1859), but
since the client will maintain multiple connections to the cluster you would need to dynamically allocate these ports anyway, much like the kernel already does for you. So my recommendation would be not to filter on the source port, I don't see how it adds much in ways of security.

**Comment by PoHS131** [comment]
@edenhill Hello, there.
I am a person following you.
I have one problem in using python-kafka.
I need your help.
Please help me.
