### ISSUE TITLE
Kafka Consumer failed to continue consume messages and getting error Commit Error : Local: Waiting for coordinator

### ISSUE THREAD

**Issue by Mantu-DotNetTechie** [edenhill/librdkafka#2725]
Description
===========
I used Confluent-Kafka C# v1.3.0 dll KafkaConsumer API, when the application is in idle state OR broker is down and consumer is not consuming messages,
The consumer could not consume message anymore, even if the broker was up and
could be consumed messages from the same group and the same topic by another application.

I am using librdkakfka-1.3.0.

Workaround: restart my application and it could continue to consume

Looking forward to receiving your response, thanks very much!

How to reproduce
================

1. Setup single nodekafka_2.12-2.3.1, single zookeeper
2. Created topic T1 with 1 partition using Kafka Tool. 
3. Ran my application A to send 10 messages to the T1 topic.
4. When step 3 was done, I ran my application B to consume messages from the T1 topic and handle those messages. After some time put an application in an idle state or broker restarted.
5. At a time, the consumer failed to consume the message and thought broker was down, but when it found broker was up, it failed to continue to consume the message, the following as the related log:

Broker was down

Exception	36	20/02/2020 08:51:54.599	Error	EventBusServer | 2/2 brokers are down	
Exception	37	20/02/2020 08:51:54.601	Error	EventBusServer | localhost:9092/0: Disconnected (after 198500ms in state UP)	
Exception	37	20/02/2020 08:51:54.601	Error	EventBusServer | 2/2 brokers are down	
Exception	35	20/02/2020 08:51:54.601	Error	EventBusServer | localhost:9092/0: Disconnected (after 203335ms in state UP)	
Exception	34	20/02/2020 08:51:54.604	Error	EventBusServer | localhost:9092/0: Disconnected (after 197970ms in state UP)	
Exception	34	20/02/2020 08:51:54.604	Error	EventBusServer | 2/2 brokers are down	
Exception	33	20/02/2020 08:51:54.604	Error	EventBusServer | localhost:9092/0: Disconnected (after 199893ms in state UP)	
Exception	33	20/02/2020 08:51:54.604	Error	EventBusServer | 2/2 brokers are down	
Exception	37	20/02/2020 08:52:54.655	Error	EventBusServer | 1/1 brokers are down

failed to continue to consume messages

Exception	36	20/02/2020 08:53:10.043	Error	EventBusServer | Commit Error : Local: Waiting for coordinator	
Exception	36	20/02/2020 08:53:21.044	Error	EventBusServer | Commit Error : Local: Waiting for coordinator	
Exception	36	20/02/2020 08:53:32.046	Error	EventBusServer | Commit Error : Local: Waiting for coordinator	
Exception	36	20/02/2020 08:53:42.047	Error	EventBusServer | Commit Error : Local: Waiting for coordinator	
Exception	36	20/02/2020 08:53:53.047	Error	EventBusServer | Commit Error : Local: Waiting for coordinator	
Exception	36	20/02/2020 08:54:04.048	Error	EventBusServer | Commit Error : Local: Waiting for coordinator	
Exception	36	20/02/2020 08:54:15.048	Error	EventBusServer | Commit Error : Local: Waiting for coordinator	
Exception	36	20/02/2020 08:54:26.048	Error	EventBusServer | Commit Error : Local: Waiting for coordinator	

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): `v1.3.0`
 - [x] Apache Kafka version: `2.3.1`
 - [x] librdkafka client configuration: `default configuration`
 - [x] Operating system: `Windows 7 (x64)`
 - [x] Provide logs (with `debug=..` as necessary) from librdkafka
         Exception	36	20/02/2020 09:01:43.391	Error	EventBusServer | Commit Error : Local: Waiting for coordinator	
Exception	36	20/02/2020 09:01:54.391	Error	EventBusServer | Commit Error : Local: Waiting for coordinator	
Exception	36	20/02/2020 09:02:05.392	Error	EventBusServer | Commit Error : Local: Waiting for coordinator	
Exception	36	20/02/2020 09:02:16.392	Error	EventBusServer | Commit Error : Local: Waiting for coordinator	
Exception	36	20/02/2020 09:02:27.393	Error	EventBusServer | Commit Error : Local: Waiting for coordinator	
Exception	36	20/02/2020 09:02:38.393	Error	EventBusServer | Commit Error : Local: Waiting for coordinator	
Exception	36	20/02/2020 09:02:49.393	Error	EventBusServer | Commit Error : Local: Waiting for coordinator
 - [x] Provide broker log excerpts
       [2020-02-20 14:22:54,824] INFO [GroupMetadataManager brokerId=0] Finished loading offsets and group metadata from __consumer_offsets-30 in 0 milliseconds. (kafka.coordinator.group.GroupMetadataManager)
[2020-02-20 14:22:54,824] INFO [GroupMetadataManager brokerId=0] Finished loading offsets and group metadata from __consumer_offsets-36 in 0 milliseconds. (kafka.coordinator.group.GroupMetadataManager)
[2020-02-20 14:22:54,824] INFO [GroupMetadataManager brokerId=0] Finished loading offsets and group metadata from __consumer_offsets-42 in 0 milliseconds. (kafka.coordinator.group.GroupMetadataManager)
[2020-02-20 14:22:54,824] INFO [GroupMetadataManager brokerId=0] Finished loading offsets and group metadata from __consumer_offsets-48 in 0 milliseconds. (kafka.coordinator.group.GroupMetadataManager)
[2020-02-20 14:32:53,976] INFO [GroupMetadataManager brokerId=0] Removed 0 expired offsets in 3 milliseconds. (kafka.coordinator.group.GroupMetadataManager)
 - [x] Critical issue

**Comment by edenhill** [comment]
Can you reproduce this with `debug=consumer,broker,topic` to figure out what is going on in the consumer?

**Comment by ManteshJangond** [comment]
@edenhill Thanks for your response.

Please find below logs and reproduced this with `debug=consumer,broker,topic`.

EventBusServer                27           24/02/2020 06:32:29.592               Info        EventBusMessageProviderConfluentKafka | [thrd:main]: Deferring "manual" offset commit for 1 partition(s) in state query-coord: no coordinator available  
EventBusServer                27           24/02/2020 06:32:30.074               Info        EventBusMessageProviderConfluentKafka | [thrd:main]: Topic T1 metadata information unknown    
EventBusServer                27           24/02/2020 06:32:30.074               Info        EventBusMessageProviderConfluentKafka | [thrd:main]: Topic T1 [0]: broker is down: re-query          
EventBusServer                27           24/02/2020 06:32:30.074               Info        EventBusMessageProviderConfluentKafka | [thrd:main]: Cluster connection already in progress: refresh unavailable topics   
EventBusServer                27           24/02/2020 06:32:30.074               Info        EventBusMessageProviderConfluentKafka | [thrd:main]: Not selecting any broker for cluster connection: still suppressed for 49ms: refresh unavailable topics                
EventBusServer                27           24/02/2020 06:32:30.074               Info        EventBusMessageProviderConfluentKafka | [thrd:main]: Not selecting any broker for cluster connection: still suppressed for 49ms: no cluster connection     
EventBusServer                27           24/02/2020 06:32:30.092               Info        EventBusMessageProviderConfluentKafka | [thrd:main]: Not selecting any broker for cluster connection: still suppressed for 32ms: coordinator query            
EventBusServer                27           24/02/2020 06:32:30.592               Info        EventBusMessageProviderConfluentKafka | [thrd:main]: Cluster connection already in progress: coordinator query  
EventBusServer                27           24/02/2020 06:32:31.074               Info        EventBusMessageProviderConfluentKafka | [thrd:main]: Topic T1 metadata information unknown    
EventBusServer                27           24/02/2020 06:32:31.074               Info        EventBusMessageProviderConfluentKafka | [thrd:main]: Topic T1 [0]: broker is down: re-query          
EventBusServer                27           24/02/2020 06:32:31.074               Info        EventBusMessageProviderConfluentKafka | [thrd:main]: Cluster connection already in progress: refresh unavailable topics   
EventBusServer                27           24/02/2020 06:32:31.074               Info        EventBusMessageProviderConfluentKafka | [thrd:main]: Not selecting any broker for cluster connection: still suppressed for 49ms: refresh unavailable topics                
EventBusServer                27           24/02/2020 06:32:31.074               Info        EventBusMessageProviderConfluentKafka | [thrd:main]: Not selecting any broker for cluster connection: still suppressed for 49ms: no cluster connection     
EventBusServer                27           24/02/2020 06:32:31.092               Info        EventBusMessageProviderConfluentKafka | [thrd:main]: Not selecting any broker for cluster connection: still suppressed for 33ms: coordinator query            
EventBusServer                27           24/02/2020 06:32:31.592               Info        EventBusMessageProviderConfluentKafka | [thrd:main]: Cluster connection already in progress: coordinator query  
EventBusServer                27           24/02/2020 06:32:32.074               Info        EventBusMessageProviderConfluentKafka | [thrd:main]: Topic T1 metadata information unknown    
EventBusServer                27           24/02/2020 06:32:32.074               Info        EventBusMessageProviderConfluentKafka | [thrd:main]: Topic T1 [0]: broker is down: re-query          
EventBusServer                27           24/02/2020 06:32:32.074               Info        EventBusMessageProviderConfluentKafka | [thrd:main]: Cluster connection already in progress: refresh unavailable topics   
EventBusServer                27           24/02/2020 06:32:32.074               Info        EventBusMessageProviderConfluentKafka | [thrd:main]: Not selecting any broker for cluster connection: still suppressed for 49ms: refresh unavailable topics                
EventBusServer                27           24/02/2020 06:32:32.074               Info        EventBusMessageProviderConfluentKafka | [thrd:main]: Not selecting any broker for cluster connection: still suppressed for 49ms: no cluster connection     
EventBusServer                27           24/02/2020 06:32:32.091               Info        EventBusMessageProviderConfluentKafka | [thrd:main]: Not selecting any broker for cluster connection: still suppressed for 32ms: coordinator query            
EventBusServer                27           24/02/2020 06:32:32.592               Info        EventBusMessageProviderConfluentKafka | [thrd:main]: Cluster connection already in progress: coordinator query  
EventBusServer                27           24/02/2020 06:32:33.074               Info        EventBusMessageProviderConfluentKafka | [thrd:main]: Topic T1 metadata information unknown    
EventBusServer                27           24/02/2020 06:32:33.074               Info        EventBusMessageProviderConfluentKafka | [thrd:main]: Topic T1 [0]: broker is down: re-query          
EventBusServer                27           24/02/2020 06:32:33.074               Info        EventBusMessageProviderConfluentKafka | [thrd:main]: Cluster connection already in progress: refresh unavailable topics   
EventBusServer                27           24/02/2020 06:32:33.074               Info        EventBusMessageProviderConfluentKafka | [thrd:main]: Not selecting any broker for cluster connection: still suppressed for 49ms: refresh unavailable topics                
EventBusServer                27           24/02/2020 06:32:33.074               Info        EventBusMessageProviderConfluentKafka | [thrd:main]: Not selecting any broker for cluster connection: still suppressed for 49ms: no cluster connection     
EventBusServer                27           24/02/2020 06:32:33.091               Info        EventBusMessageProviderConfluentKafka | [thrd:main]: Not selecting any broker for cluster connection: still suppressed for 32ms: coordinator query            
EventBusServer                27           24/02/2020 06:32:33.592               Info        EventBusMessageProviderConfluentKafka | [thrd:main]: Cluster connection already in progress: coordinator query  
EventBusServer                26           24/02/2020 06:32:33.702               Info        EventBusMessageProviderConfluentKafka | [thrd:localhost:9092/bootstrap]: localhost:9092/0: Timed out 0 in-flight, 1 retry-queued, 0 out-queue, 0 partially-sent requests    
EventBusServer                27           24/02/2020 06:32:33.702               Info        EventBusMessageProviderConfluentKafka | [thrd:main]: localhost:9092/0: MetadataRequest failed: Local: Timed out in queue: actions Retry          
EventBusServer                26           24/02/2020 06:32:33.702               Info        EventBusMessageProviderConfluentKafka | [thrd:localhost:9092/bootstrap]: localhost:9092/0: broker in state TRY_CONNECT connecting             
EventBusServer                26           24/02/2020 06:32:33.702               Info        EventBusMessageProviderConfluentKafka | [thrd:localhost:9092/bootstrap]: localhost:9092/0: Broker changed state TRY_CONNECT -> CONNECT            
EventBusServer                26           24/02/2020 06:32:33.702               Info        EventBusMessageProviderConfluentKafka | [thrd:localhost:9092/bootstrap]: localhost:9092/0: Connecting to ipv4#localhost:9092 (plaintext) with socket 3508       
EventBusServer                27           24/02/2020 06:32:34.074               Info        EventBusMessageProviderConfluentKafka | [thrd:main]: Topic T1 metadata information unknown    
EventBusServer                27           24/02/2020 06:32:34.074               Info        EventBusMessageProviderConfluentKafka | [thrd:main]: Topic T1 [0]: broker is down: re-query          
EventBusServer                27           24/02/2020 06:32:34.074               Info        EventBusMessageProviderConfluentKafka | [thrd:main]: Cluster connection already in progress: refresh unavailable topics   
EventBusServer                27           24/02/2020 06:32:34.074               Info        EventBusMessageProviderConfluentKafka | [thrd:main]: Not selecting any broker for cluster connection: still suppressed for 49ms: refresh unavailable topics                
EventBusServer                27           24/02/2020 06:32:34.074               Info        EventBusMessageProviderConfluentKafka | [thrd:main]: Not selecting any broker for cluster connection: still suppressed for 49ms: no cluster connection     
EventBusServer                27           24/02/2020 06:32:34.092               Info        EventBusMessageProviderConfluentKafka | [thrd:main]: Not selecting any broker for cluster connection: still suppressed for 32ms: coordinator query            
EventBusServer                27           24/02/2020 06:32:34.592               Info        EventBusMessageProviderConfluentKafka | [thrd:main]: Cluster connection already in progress: coordinator query  
EventBusServer                26           24/02/2020 06:32:34.704               Info        EventBusMessageProviderConfluentKafka | [thrd:localhost:9092/bootstrap]: localhost:9092/0: Moved 1 retry buffer(s) to output queue              
EventBusServer                27           24/02/2020 06:32:35.074               Info        EventBusMessageProviderConfluentKafka | [thrd:main]: Topic T1 metadata information unknown    
EventBusServer                27           24/02/2020 06:32:35.074               Info        EventBusMessageProviderConfluentKafka | [thrd:main]: Topic T1 [0]: broker is down: re-query          
EventBusServer                27           24/02/2020 06:32:35.074               Info        EventBusMessageProviderConfluentKafka | [thrd:main]: Cluster connection already in progress: refresh unavailable topics   
EventBusServer                27           24/02/2020 06:32:35.074               Info        EventBusMessageProviderConfluentKafka | [thrd:main]: Not selecting any broker for cluster connection: still suppressed for 49ms: refresh unavailable topics                
EventBusServer                27           24/02/2020 06:32:35.074               Info        EventBusMessageProviderConfluentKafka | [thrd:main]: Not selecting any broker for cluster connection: still suppressed for 49ms: no cluster connection     
EventBusServer                27           24/02/2020 06:32:35.092               Info        EventBusMessageProviderConfluentKafka | [thrd:main]: Not selecting any broker for cluster connection: still suppressed for 32ms: coordinator query            
EventBusServer                27           24/02/2020 06:32:35.593               Info        EventBusMessageProviderConfluentKafka | [thrd:main]: Cluster connection already in progress: coordinator query  
EventBusServer                26           24/02/2020 06:32:35.704               Info        EventBusMessageProviderConfluentKafka | [thrd:localhost:9092/bootstrap]: localhost:9092/0: failed: err: Local: Broker transport failure: (errno: Unknown error)    
EventBusServer                26           24/02/2020 06:32:35.704               Info        EventBusMessageProviderConfluentKafka | [thrd:localhost:9092/bootstrap]: localhost:9092/0: Connect to ipv4#localhost:9092 failed: No connection could be made because the target machine actively refused it... (after 2001ms in state CONNECT)        
EventBusServer                26           24/02/2020 06:32:35.704               Info        EventBusMessageProviderConfluentKafka | [thrd:localhost:9092/bootstrap]: localhost:9092/0: Broker changed state CONNECT -> DOWN            
EventBusServer                27           24/02/2020 06:32:35.704               Info        EventBusMessageProviderConfluentKafka | [thrd:main]: localhost:9092/0: MetadataRequest failed: Local: Broker transport failure: actions Retry  
EventBusServer                27           24/02/2020 06:32:36.075               Info        EventBusMessageProviderConfluentKafka | [thrd:main]: Topic T1 metadata information unknown    
EventBusServer                27           24/02/2020 06:32:36.075               Info        EventBusMessageProviderConfluentKafka | [thrd:main]: Topic T1 [0]: broker is down: re-query          
EventBusServer                27           24/02/2020 06:32:36.075               Info        EventBusMessageProviderConfluentKafka | [thrd:main]: Cluster connection already in progress: refresh unavailable topics   
EventBusServer                27           24/02/2020 06:32:36.075               Info        EventBusMessageProviderConfluentKafka | [thrd:main]: Not selecting any broker for cluster connection: still suppressed for 49ms: refresh unavailable topics                
EventBusServer                27           24/02/2020 06:32:36.075               Info        EventBusMessageProviderConfluentKafka | [thrd:main]: Not selecting any broker for cluster connection: still suppressed for 49ms: no cluster connection     
EventBusServer                27           24/02/2020 06:32:36.093               Info        EventBusMessageProviderConfluentKafka | [thrd:main]: Not selecting any broker for cluster connection: still suppressed for 32ms: coordinator query            
EventBusServer                27           24/02/2020 06:32:36.594               Info        EventBusMessageProviderConfluentKafka | [thrd:main]: Cluster connection already in progress: coordinator query  
EventBusServer                26           24/02/2020 06:32:36.704               Info        EventBusMessageProviderConfluentKafka | [thrd:localhost:9092/bootstrap]: localhost:9092/0: Moved 1 retry buffer(s) to output queue              
EventBusServer                26           24/02/2020 06:32:36.704               Info        EventBusMessageProviderConfluentKafka | [thrd:localhost:9092/bootstrap]: localhost:9092/0: Broker changed state DOWN -> INIT        
EventBusServer                26           24/02/2020 06:32:36.704               Info        EventBusMessageProviderConfluentKafka | [thrd:localhost:9092/bootstrap]: localhost:9092/0: Broker changed state INIT -> TRY_CONNECT        
EventBusServer                26           24/02/2020 06:32:36.704               Info        EventBusMessageProviderConfluentKafka | [thrd:localhost:9092/bootstrap]: localhost:9092/0: Delaying next reconnect by 6998ms         
EventBusServer                27           24/02/2020 06:32:37.075               Info        EventBusMessageProviderConfluentKafka | [thrd:main]: Topic T1 metadata information unknown    
EventBusServer                27           24/02/2020 06:32:37.075               Info        EventBusMessageProviderConfluentKafka | [thrd:main]: Topic T1 [0]: broker is down: re-query          
EventBusServer                27           24/02/2020 06:32:37.075               Info        EventBusMessageProviderConfluentKafka | [thrd:main]: Cluster connection already in progress: refresh unavailable topics   
EventBusServer                27           24/02/2020 06:32:37.075               Info        EventBusMessageProviderConfluentKafka | [thrd:main]: Not selecting any broker for cluster connection: still suppressed for 49ms: refresh unavailable topics                
EventBusServer                27           24/02/2020 06:32:37.075               Info        EventBusMessageProviderConfluentKafka | [thrd:main]: Not selecting any broker for cluster connection: still suppressed for 49ms: no cluster connection     
EventBusServer                27           24/02/2020 06:32:37.093               Info        EventBusMessageProviderConfluentKafka | [thrd:main]: Not selecting any broker for cluster connection: still suppressed for 31ms: coordinator query            
EventBusServer                27           24/02/2020 06:32:37.594               Info        EventBusMessageProviderConfluentKafka | [thrd:main]: Cluster connection already in progress: coordinator query  
EventBusServer                27           24/02/2020 06:32:38.075               Info        EventBusMessageProviderConfluentKafka | [thrd:main]: Topic T1 metadata information unknown    
EventBusServer                27           24/02/2020 06:32:38.075               Info        EventBusMessageProviderConfluentKafka | [thrd:main]: Topic T1 [0]: broker is down: re-query          
EventBusServer                27           24/02/2020 06:32:38.075               Info        EventBusMessageProviderConfluentKafka | [thrd:main]: Cluster connection already in progress: refresh unavailable topics   
EventBusServer                27           24/02/2020 06:32:38.075               Info        EventBusMessageProviderConfluentKafka | [thrd:main]: Not selecting any broker for cluster connection: still suppressed for 49ms: refresh unavailable topics                
EventBusServer                27           24/02/2020 06:32:38.075               Info        EventBusMessageProviderConfluentKafka | [thrd:main]: Not selecting any broker for cluster connection: still suppressed for 49ms: no cluster connection     
EventBusServer                27           24/02/2020 06:32:38.093               Info        EventBusMessageProviderConfluentKafka | [thrd:main]: Not selecting any broker for cluster connection: still suppressed for 31ms: coordinator query            
EventBusServer                27           24/02/2020 06:32:38.594               Info        EventBusMessageProviderConfluentKafka | [thrd:main]: Cluster connection already in progress: coordinator query  
EventBusServer                27           24/02/2020 06:32:39.075               Info        EventBusMessageProviderConfluentKafka | [thrd:main]: Topic T1 metadata information unknown    
EventBusServer                27           24/02/2020 06:32:39.075               Info        EventBusMessageProviderConfluentKafka | [thrd:main]: Topic T1 [0]: broker is down: re-query          
EventBusServer                27           24/02/2020 06:32:39.075               Info        EventBusMessageProviderConfluentKafka | [thrd:main]: Cluster connection already in progress: refresh unavailable topics   
EventBusServer                27           24/02/2020 06:32:39.075               Info        EventBusMessageProviderConfluentKafka | [thrd:main]: Not selecting any broker for cluster connection: still suppressed for 49ms: refresh unavailable topics                
EventBusServer                27           24/02/2020 06:32:39.075               Info        EventBusMessageProviderConfluentKafka | [thrd:main]: Not selecting any broker for cluster connection: still suppressed for 49ms: no cluster connection     
EventBusServer                27           24/02/2020 06:32:39.093               Info        EventBusMessageProviderConfluentKafka | [thrd:main]: Not selecting any broker for cluster connection: still suppressed for 31ms: coordinator query            
EventBusServer                27           24/02/2020 06:32:39.594               Info        EventBusMessageProviderConfluentKafka | [thrd:main]: Cluster connection already in progress: coordinator query  
EventBusServer                27           24/02/2020 06:32:39.594               Info        EventBusMessageProviderConfluentKafka | [thrd:main]: Not selecting any broker for cluster connection: still suppressed for 49ms: coordinator query            
EventBusServer                15           24/02/2020 06:32:39.594               Error      Commit Error : Local: Waiting for coordinator

**Comment by edenhill** [comment]
The log is incomplete:
```
[thrd:localhost:9092/bootstrap]: localhost:9092/0: Broker changed state INIT -> TRY_CONNECT
EventBusServer 26 24/02/2020 06:32:36.704 Info EventBusMessageProviderConfluentKafka | [thrd:localhost:9092/bootstrap]: localhost:9092/0: Delaying next reconnect by 6998ms
```

at 06:32:36 it is delaying the next reconnect by ~7 seconds, but the log is cut off just short of 7 seconds.

**Comment by pthalasta** [comment]
@edenhill is there an update on how to resolve this issue? I'm seeing similar issue with confluent kafka python library

**Comment by edenhill** [comment]
@pthalasta What version are you on?

Is the cluster healthy and fully replicated?

**Comment by pthalasta** [comment]
@edenhill this looks like an issue with get_watermark function in oauth based authentication and i'll open a new issue based on my findings
