### ISSUE TITLE
Default sending and receiving sizes seem to be out of sync, and out of sync with Kafka's defaults

### ISSUE THREAD

**Issue by skandragon** [edenhill/librdkafka#274]
It seems like the defaults should produce a working producer which can send to a default-configured Kafka, and read back what it wrote.

fetch.message.max.bytes is set to 1048576 by default, but message.max.bytes is 4000000.  This means I can successfully write much larger messages than the consumer can successfully read.  (worse, it seems to get stuck in a loop trying to read a message it has no hope of ever reading)

These defaults are also out of sync with Kafka I think, which defaults the max message size to around 1000000.

**Comment by rthalley** [comment]
I will add that compression was being used in skandragon's case.  I think the issue is that the output buffer size doesn't take into account it might produce a single compressed message that is bigger than a consumer can subsequently read.  But I'm not sure I understand things well enough :)

**Comment by edenhill** [comment]
You are both right.
The reason for a larger (producer) message.max.bytes is because it is reused also for maximum MessageSet (e.g., batch of messages) size.
This should probably be fixed so that:
 * `message.max.bytes` is the per-message maximum size
 * `batch.max.bytes` is the per-message-set maximum size, but only if uncompressed
 * `message.max.bytes` is the maximum size for a compressed message-set (since a compressed message-set is enveloped in a message).

**Comment by edenhill** [comment]
With the adaptive receive size increments added in 0.9.2 this is no longer an issue.
