### ISSUE TITLE
Question on rd_kafka_commit_message

### ISSUE THREAD

**Issue by accelerated** [edenhill/librdkafka#2745]
Hi @edenhill, I just wanted to understand why `rd_kafka_commit_message` is equivalent to `rd_kafka_commit(message_offset+1)`? I noticed you are incrementing the offset before committing it but this is not documented anywhere in the API. When you commit an offset, my understanding was that you actually commit the current position not the next one. Please let me know. 
I also noticed that `rd_kafka_offset_store` increments the offset by 1 before storing it, but `rd_kafka_offsets_store` doesn't seem to do that. 

Cheers!

**Comment by edenhill** [comment]
The Kafka commit semantics is to commit the offset where consumption should *resume*, i.e., the last processed offset + 1.

To make the commit_message() meaningful it thus does the +1 automatically, since if an application has the message_t it is assumed to have been processed.

Thanks for pointing out the lack of documentation, I will clarify the API docs.

**Comment by accelerated** [comment]
Hi, yes this is what i figured, however there is still the inconsistency between the two offset_store functions. The one taking a list should also increment the offset by 1.

**Comment by edenhill** [comment]
The reason it treats the offsets as-is is because the typical usage is getting the offsets list from position(), which is last_consumed + 1.

**Comment by accelerated** [comment]
Hmmm ok. I personally would prefer to see the same behavior in both and perhaps have a function which you can use to do the proper translation such as `rd_kafka_offsets_store(rd_kafka_make_store_list_from_position(position()))`. If someone calls position() but then decides to store individually because of some application logic, it won't work. Or just properly document it with a bit WARNING note.

**Comment by jcalcote** [comment]
The problem I have with this disparity in functionality is that I specifically want to commit the offset of the current message so that if I restart, I can pick up at _this_ message, not the next one. (My system requires this functionality, so please don't tell me I'm wrong to do this.) Here is the equivalent code for managing this with the offset commit api:

```
                    rd_kafka_topic_partition_t offset = { kc->topars->elems[0].topic, kc->topars->elems[0].partition,
                            msg->offset, 0, 0, 0, 0 };
                    rd_kafka_topic_partition_list_t offsets = { 1, 1, &offset };
                    rd_kafka_commit(kc->rk, &offsets, 1);
```
whereas the msg-based api is simply:

```
                    rd_kafka_commit_message(kc->rk, msg, 1);
```

**Comment by edenhill** [comment]
@jcalcote That's fine,  the only thing to watch out for is that librdkafka will not commit older offsets, that is, if it has committed offset 5 it will not commit offset 4, but happily offset 6.
