### ISSUE TITLE
A skimming capability for produce.offset.report would be nice

### ISSUE THREAD

**Issue by lehenbauer** [edenhill/librdkafka#279]
I think it would be handy to be able to get offset reports less frequently than once per message.  For instance I would like an offset report for every 100,000th message produced so that I can generate an index topic that ties epoch clocks and offsets together.

If you decide you like that idea then it would also be nice if one could set a time interval as well.  Offset reports would be generated whenever the time interval had passed since the last one was emitted.  That way a topic that may not be busy or may be variable will still get some offset reports while a topic that is very busy would get them from via the counter above.

**Comment by edenhill** [comment]
The reason for having offset reports as a configurable rather than always-on is because it requires an additional O(N) scan over each produced message in a batch to assign the per-message offset.
https://github.com/edenhill/librdkafka/blob/master/src/rdkafka_broker.c#L1941

Your suggestions are good, and the cheapest (both performance and coding wise) way to achieve this skimming behaviour would be to assign the offset to the last message in a produced batch.
A produced batch is an internal phenomena constrained by batch message count (`batch.num.messages`), batch message size (`message.max.bytes`) or time (`queue.buffering.max.ms`). For high throughput applications a batch most likely contains `batch.num.messages`.

Delivery report callbacks will be called for all messages in a produced batch for one .._poll() call, which effectively means that for each time you call .._poll() to serve your delivery reports you will know the latest/greatest offset produced  (the last message's offset).

Would this work for you?


This behaviour would always be enabled, and for more fine grained offsets (per-message rather than batch) the existing config property `produce.offset.report` is used.

**Comment by lehenbauer** [comment]
Hi Magnus, that will work perfectly.

**Comment by edenhill** [comment]
This is fixed in dev branch (but not pushed yet)

**Comment by edenhill** [comment]
Fixed on master
