### ISSUE TITLE
Socket.keepalive.enable

### ISSUE THREAD

**Issue by winbatch** [edenhill/librdkafka#283]
I see it disabled by default. What is the downside of enabling it?

We are seeing some cases when Kafka still shows an established connection even though librdkafka is down.

**Comment by edenhill** [comment]
There is no downside to enabling keepalives.
The only reason it is off by default is because I dont want to change the default behaviour when adding new features, but in this case that sounds a bit daft.

I believe socket keepalives need to be enabled on both sides to expedite connection termination on connectivity loss (e.g., network partitioning) for both parties.
This means the broker needs to implement it too.

**Comment by winbatch** [comment]
Perfect. Thanks as always
