### ISSUE TITLE
Repeatable strangeness with producer "halting"

### ISSUE THREAD

**Issue by skandragon** [edenhill/librdkafka#285]
I am seeing some very strange behavior with rdkafka on MacOS.  So far, this seems limited to just MacOS.

I have a data cruncher which consumes from a Kafka topic, farms the messages out internally to one of N threads, and then writes to a producer to return the result to Kafka.  With 4 (out of 6) physical cores running this cruncher, I am seeing some odd behavior, and I think it's in rdkafka.

First, the consumers continue to function as expected: the data flows in just fine from the consumer side.  However, at some point, the output "text" topic with 2 partitions (random) goes from both partitions getting lots of data, to first one, then the other, then the first, then the second...  and this cycle happens slower and slower until eventually all data seems to stop flowing.  Also during this time, my process goes from being user-CPU time dominated to system time dominated.  This is likely caused by the memory of the process bloating to more than my physical RAM of 64 GB, where the process normally uses about 10 GB.

No errors are reported by rdkafka. We have a callback set up to print out any events.

I have not been able to reproduce this with a simple test case, but I can seemingly reproduce it at will on my Mac.

What debug flags should I start with, or what settings should I tweak?

I am currently only setting these away from the default:

```            global-properties => {
                message.max.bytes => '2000000'
                compression.codec => 'snappy'
            }```

**Comment by skandragon** [comment]
A workaround seems to be setting queue.buffering.max.messages to 1000.  My messages are up to 128k in size, so this would be a good idea anyway, but it is a little concerning that limiting the outgoing queue makes things seem to work again.

**Comment by edenhill** [comment]
The default value for `queue.buffering.max.messages` is 100 000, **per partition**,
thus in your case it would allow up to 24 Gigs of data on the two partitions.
Reducing `queue.buffering.max.messages` is a good idea.

But, what makes it start queueing in the first place?
One thing to note is that the consumer is much faster than the producer, and you are running two consumers that end up forwarding to the same producer, so if the consumerX2 -> producer message rate is higher than what the producer can handle then queueing will ensue, and eventually message drop (produce() failure) when the queues get full.
Is this the case for you? What is your message rate?

Why it only happens on OSX? Beats me, but the OSX scheduler might not be as suited for this kind of highly concurrent work than Linux, but thats just a guess.
Also, if things are run close to the limit and any hickup occurs (another process comes rumbling in for instance) then things might just escalate out of control because there is not enough processing power to catch up again.

To troubleshoot this further I'd suggest that you enable statistics output (`..conf_set_stats_cb()`) and set it a low interval, e,g, 1000 ms, and forward the stats to a file for later processing.

**Comment by skandragon** [comment]
I'll try the statistics thing.

The consumer reads 1 MB messages in a pretty compact binary form and writes them out to a text topic.  The expansion is roughly 1 MB in for 2 MB out in the form of 128k-max messages.  The input rate is about 250 messages/sec, so the output will be around 2000 messages/sec.  In my tests, this is not a high load; the disk does not saturate, nor does the Kafka process itself.  Loading test data into the binary topic happens at a much higher sustained rate than writing text.

What is strange is when it does start queueing, it seems to not actually recover until the queue hits its upper limit.

**Comment by edenhill** [comment]
Yeah, those rates shouldn't be a problem, unless the actual transformation processing starves the CPU.

But lets start with collecting some statistics to see where things are queuing up, it will also be interesting to see some broker latencies (reported as 'rtt' in the stats).

**Comment by edenhill** [comment]
Hi @skandragon, any luck with the statistics?

**Comment by skandragon** [comment]
I think I found the reason.  I think it was working just fine, but that the messages were not being written due to size, and we don't have a (working) delivery callback.
