### ISSUE TITLE
Doubt - Is the produce option in rdkafka_performance singlethreaded?

### ISSUE THREAD

**Issue by prabcs** [edenhill/librdkafka#287]
Hi Folks,

I'm trying to evaluate Kafka using librdkafka from performance standpoint.
I want to see its performance when messages are written sequentially. I've skimmed through rdkafka_performance.c. 
I have a doubt:-
With the producer option 'P', line 1005, when 'rd_kafka_produce' is called, is it a sequential call ?
Or are multiple threads calling 'rd_kafka_produce' somewhere ?

**Comment by edenhill** [comment]
Hi, 
rdkafka_performance is single threaded indeed, it would perhaps make sense to provide a multi threaded variant too. 
Librdkafka itself is completely thread safe in this respect though, an application may call produce() from multiple threads simultaneously. 
Does that answer your question?

**Comment by prabcs** [comment]
Hi,

Thanks for your prompt reply.
This answers my question, however now I've another doubt,  not sure if I
should be asking it in this thread or create a new thread.
If end to end throughput and latency have to be tested/evaluated, can it be
done with  the -l option? E.g. I want to dump around 1M messages to a topic
and I want to see in how much time they all get consumed

Thanks again

On May 26, 2015 8:22 PM, "Magnus Edenhill" <notifications@github.com> wrote:
>
> Hi,
> rdkafka_performance is single threaded indeed, it would perhaps make
sense to provide a multi threaded variant too.
> Librdkafka itself is completely thread safe in this respect though, an
application may call produce() from multiple threads simultaneously.

**Comment by edenhill** [comment]
If you want to measure end-to-end latency (e.g., the time it takes from a produce() call to the same message being returned by a consume() call) then `-l` is a perfect candidate.
However, if you just want to measure consumer throughput, which is typically much higher than producer throughput, what I would do is:
 1) produce 1 million messages to a topic.
 2) wait for all messages to be produced.
 3) start consumer, consume last 1 million messages.   (time this step)

However, due to disk cache sizes (which is very favourable with Kafka) you might get higher throughput if messages are still in the disk cache, in this case you might want to try this instead:
 1) start consumer, start consuming at end of partition.
 2) start N producers (e.g., 4), let each one produce its share of the 1M messages.
 3) in consumer, measure the time it took between the first and last message received.

**Comment by prabcs** [comment]
Sure. Thanks again for your help

**Comment by rathdeep** [comment]
Sorry to comment on closed issue.

When you say "
edenhill commented on May 26
Hi, 
Librdkafka itself is completely thread safe in this respect though, an application may call produce() from multiple threads simultaneously. 
...
"

Hope this holds true when producing to same topic + partition  from multiple threads.

Thanks.

**Comment by edenhill** [comment]
@rathdeep Yep, producing to the same topic+partition simultaneously is safe.

**Comment by rathdeep** [comment]
Thanks.
