### ISSUE TITLE
Counter

### ISSUE THREAD

**Issue by renatocosta** [edenhill/librdkafka#2870]
Hello,

Does librdkafka to be able to count the total of messages in Topic?

Thank you

**Comment by edenhill** [comment]
Since a topic may be compacted and thus have gaps in the message series there is no sure way of knowing the number of messages in a topic short of actually consuming all messages and counting them, which can be costly for obvious reasons.

If you want a rough estimate you can query a partition for the low and high watermarks, i.e., the oldest and newest offset, using rd_kafka_query_watermark_offsets().
