### ISSUE TITLE
Doubt - Kafka benchmarking - backpressure rate

### ISSUE THREAD

**Issue by prabcs** [edenhill/librdkafka#290]
Hi,

I've seen that a certain backpressure rate occassionally. A sample output:-

time librdkafka-master/examples/rdkafka_performance -P -t temp4 -s 1024 -c 1048576  -b x.x.x.x:9092,y.y.y.y:9092,z.z.z.z:9092 -u
% Sending 1048576 messages of size 1024 bytes
|    elapsed |       msgs |      bytes |        rtt |         dr |     dr_m/s |    dr_MB/s |     dr_err |     tx_err |       outq 
|          0 |          1 |       1024 |          0 |          0 |          0 |       0.00 |          0 |          0 |          1 
|       1000 |     405562 |  415295488 |          0 |        143 |        142 |       0.15 |          0 |          0 |     405419 
|       2000 |     559408 |  572833792 |          0 |      59615 |      29807 |      30.52 |          0 |     234390 |     499793 
|       3000 |     679483 |  695790592 |          7 |     179567 |      59855 |      61.29 |          0 |     363874 |     499916 
|       4000 |     795991 |  815094784 |          8 |     296243 |      74057 |      75.83 |          0 |     528323 |     499748 
|       5000 |     912203 |  934095872 |          8 |     412455 |      82484 |      84.46 |          0 |     724841 |     499748 
|       6000 |    1043487 | 1068530688 |          8 |     543487 |      90574 |      92.75 |          0 |     960314 |     500000 
|       7000 |    1048576 | 1073741824 |          7 |     673768 |      96246 |      98.56 |          0 |     969664 |     374808 
|       8000 |    1048576 | 1073741824 |          7 |     802795 |     100343 |     102.75 |          0 |     969664 |     245781 
|       9000 |    1048576 | 1073741824 |          8 |     935135 |     103898 |     106.39 |          0 |     969664 |     113441 
% 969664 backpressures for 1048576 produce calls: 92.474% backpressure rate
|       9860 |    1048576 | 1073741824 |          7 |    1048576 |     106340 |     108.89 |          0 |     969664 |          0 

real	0m9.893s
user	0m2.220s
sys	0m10.270s

I have some doubts on this:-
1. if I do not create a topic prior to starting this binary, the binary creates the topic itself. In this case, the backpressure rate is severely high i.e. somewhere more than 100%. What could be the reason for this?
2. Also, even if the topic is already created before starting the binary, the backpressure rate varies  many times
3. I have modified the binary to have queue.buffering.max.messages as 5M instead of 500k. Can this have any affect on the benchmarking of kafka as a messaging system?

**Comment by edenhill** [comment]
Backpressures happen when librdkafka's internal produce queue (e.g., messages waiting to be sent to broker) is full.
Since `rd_kafka_new()` with friends are asynchronous APIs they will return immediately and the connection to the broker will ensue in a background thread, this takes some time and during this time the unknown rdkafka_performance application produce()s messages at full speed, eventually filling up the internal queue and a backpressure is counted.

If the topic doesn't exist and needs to be created it takes even more time before the broker starts accepting messages for a topic+partition, thats why you are seeing high backpressure rates in that scenario.

Backpressures in itself is not a problem, it is simply a flow indicator, and it makes most sense when rdkafka_performance is run without the message count `-c` option, e,g., run forever.  In that case it might be interesting to see if messages suddenly start queueing up.

In 3) you increase the internal queue to be larger than the number of messages you send and thus there will be no backpressure.
There is however no effect on the throughput or latency with or without a high backpressure in your case.

**Comment by prabcs** [comment]
Great. Thanks for your answer. It is very helpful

**Comment by yuangezhizao** [comment]
I also saw backpressure in the output of the test producer performance, thanks for the detailed explanation above.
My understanding of tx_err is because the internal produce queue was full of messages and could not be sent out at the time.
But in the end the message was still sent out, no message was lost, right?
@edenhill
