### ISSUE TITLE
Question - Variance in throughput using rdkafka_performance

### ISSUE THREAD

**Issue by prabcs** [edenhill/librdkafka#291]
Hi,

I've seen a variance in throughput when the same command is run multiple times using rdkafka_performance.
This is the command that I've used:-

 time /client_kafka/librdkafka-master/examples/rdkafka_performance -P -t temp4 -s 1024 -c 1048576  -b x.x.x.x:9092,y.y.y.y:9092,z.z.z.z:9092 -u -i 100

The dr_MB/s (i.e. the throughput ) varies between 104MB/s to 125MB/s in consecutive runs.
What could be the possible explanation for this?

**Comment by edenhill** [comment]
* Sample size too small. At that rate the test finishes in less than 10 seconds, if startup (connecting, querying metadata, etc) varies somewhat in duration it will also show in the stats.  Try increasing your sample size and see if it hepls.
 * Disk buffer flushing on the broker, this will degrade the broker performance when flushing to disk is performed. See log.flush. settings here: http://kafka.apache.org/documentation.html#brokerconfigs

It is typically a good idea to run the same test multiple times and grab an average number since there are so many moving parts.

**Comment by prabcs** [comment]
Thanks
