### ISSUE TITLE
rd_kafka_producev fails without DNS configuration

### ISSUE THREAD

**Issue by babuveld** [edenhill/librdkafka#2921]
Hi,

librdkafka rd_kafka_producev() works fine when DNS configuration is available. When DNS configuration is not available, then librdkafka rd_kafka_producev() fails. Even if we add the DNS configuration later, the API still fails. We figured out that adding res_init() before this line number https://github.com/edenhill/librdkafka/blob/master/src/rdaddr.c#L184 solves the issue. 

Want to check if there is any other librdkafka API to fix this issue other than modifying librdkafka code.

Please let me know your suggestion.

**Comment by edenhill** [comment]
Please fill out the issue checklist, in particular what OS you are on and what librdkafka version.

What error did you get from producev?

**Comment by babuveld** [comment]
Please find the details below.

OS - Linux
librdkafka - 0.11.6
producev error - "Local: Message timed out"

**Comment by edenhill** [comment]
I don't think producev() will return Message timed out, that should only be seen in delivery report callbacks, and that error is expected if the client can't connect to the cluster due to DNS issues.

**Comment by bebound** [comment]
I met the same problem. It's likely related to DNS.

I‘m using confluent kafka python 1.7.0 on Linux. When DNS is failed, if I try to create a producer, I will get these log:
```
%7|1626405233.692|STATE|rdkafka#producer-2| [thrd:sasl_plaintext://xxxxxx.kafka.db.:31]: sasl_plaintext://tendata-gtrace-proclog-sz-710.sz2.kafka.db.:31179/bootstrap: Broker changed state TRY_CONNECT -> CONNECT
* %7|1626405233.692|BRKMAIN|rdkafka#producer-2| [thrd::0/internal]: :0/internal: Enter main broker thread
* %7|1626405234.692|CONNECT|rdkafka#producer-2| [thrd:main]: Cluster connection already in progress: no cluster connection
* %7|1626405235.692|CONNECT|rdkafka#producer-2| [thrd:main]: Cluster connection already in progress: no cluster connection

after some time

%7|1626406816.626|CONNECT|rdkafka#producer-2| [thrd:main]: Cluster connection already in progress: refresh unavailable topics
%7|1626406816.626|METADATA|rdkafka#producer-2| [thrd:main]: Skipping metadata refresh of 1 topic(s): refresh unavailable topics: no usable brokers

```
If I use this producer to send message, all of the message will lose, and the error is `KafkaError{code=_MSG_TIMED_OUT,val=-192,str="Local: Message timed out"}`.

I have two questions:
1. After DNS recovering,  if I create a new producer in the same thread, the new producer still cannot connect to broker, is this expected?
2. I can reproduce these behaviors by changing `/etc/resolv.conf`, so I guess it caused by DNS fail. However, after using broker ip as `bootstrap.servers`, the problem still exists. This makes no sense. Is there any other possible cause for this problem? Thank you.
