### ISSUE TITLE
Using seek to consume messages backwards

### ISSUE THREAD

**Issue by bowu** [edenhill/librdkafka#2965]
Read the FAQ first: https://github.com/edenhill/librdkafka/wiki/FAQ

Description
===========

Is the following the right pattern to consume messages of a partition backwards?
```
uint64_t offset = RdKafka::Topic::OFFSET_END;

while(true) {
    //partition is the assigned partition to the consumer
    partition->set_offset(offset);
    consumer->seek(*partition, TIME_OUT);
    RdKafka::Message *msg = consumer->consume(TIME_OUT);
    consumer->poll(0);
    if(msg->err() == RdKafka::ERR_NO_ERROR) {
        consume_msg(msg);
    } else {
        break;
    }
    offset-=2;
}
```
I know this doesn't work, but I don't now how to get the offset of the newest message.

How to reproduce
================
<your steps how to reproduce goes here, or remove section if not relevant>

**IMPORTANT**: Always try to reproduce the issue on the latest released version (see https://github.com/edenhill/librdkafka/releases), if it can't be reproduced on the latest version the issue has been fixed.

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): `<d4360a57>`
 - [ ] Apache Kafka version: `<REPLACE with e.g., 0.10.2.3>`
 - [ ] librdkafka client configuration: `<REPLACE with e.g., message.timeout.ms=123, auto.reset.offset=earliest, ..>`
 - [ ] Operating system: `<REPLACE with e.g., Centos 5 (x64)>`
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
Messages are fetched (and pre-fetched) in batches from Kafka, by default the consumer will try to pre-fetch up to 1 GB in the background so that a new message is always available for the application to poll.
When changing the assignment, seek()ing, pause() or resume()ing, the pre-fetchq is purged and pre-fetching restarts at the new position.
So if you have 1000 messages in your topic and you seek backwards for each one, then worst case (depending on how the batches are formed (by the producer) the consumer will download the same message 1000 times.

Kafka is not really suited for reading things backwards, so what you will need to do is read larger chunks of messages before seek():ing, depending on your message size say you seek 1000 messages back, instead of 1.
You should also minimize the pre-fetch queue by setting `queued.max.message.kbytes` to a very low value.

**Comment by bowu** [comment]
Is there a way to do it more efficiently if I know exactly how many messages to consume and their total size? Say I'd like to seek to position P, and would like to consume K messages of total size S. Can I seek and then prefetch the K messages? Is there a way to supply the parameter S which changes dynamically for different starting positions?

**Comment by edenhill** [comment]
If you want to consume messages from offset OEND to OSTART in reverse I'd seek to OSTART and then consume and accumulate messages until OEND is reached, pause (if processing takes longer than max.poll.interval.ms) then traverse the accumulated messages backwards. When done, seek to the next window and redo.

**Comment by bowu** [comment]
One more question on a related problem. If I have a list of offsets of the messages to consume, what's the most efficient way to do it? I can buffer all messages from the first offset to the last offset, but doing so consumes many unneeded messages.

**Comment by edenhill** [comment]
Kafka is really fast at streaming messages, but not optimal for random access.
It is typically more efficient to stream messages and throw away what you don't need instead of seeking to individual message offsets.
