### ISSUE TITLE
Strangeness with error reporting

### ISSUE THREAD

**Issue by skandragon** [edenhill/librdkafka#299]
Any idea how I got things into this state?

```
SilverGryphon:~ explorer$ ./rdkafka_example -L
1433288004.747 RDKAFKA-3-FAIL: rdkafka#producer-0: localhost:9092/bootstrap: Failed to connect to broker at [localhost]:9092: Connection refused
1433288004.747 RDKAFKA-3-ERROR: rdkafka#producer-0: localhost:9092/bootstrap: Failed to connect to broker at [localhost]:9092: Connection refused
1433288004.747 RDKAFKA-3-ERROR: rdkafka#producer-0: 1/1 brokers are down
1433288006.756 RDKAFKA-3-ERROR: rdkafka#producer-0: 0/1 brokers are down
Metadata for all topics (from broker -1: localhost:9092/bootstrap):
 1 brokers:
  broker 0 at localhost:9092
 1 topics:
  topic "nom-dns-base" with 1 partitions:
    partition 0, leader 0, replicas: 0, isrs: 0
```

**Comment by edenhill** [comment]
You mean this:
`1433288006.756 RDKAFKA-3-ERROR: rdkafka#producer-0: 0/1 brokers are down`
?

**Comment by skandragon** [comment]
Actually, the whole thing.

I have one Kafka broker, running on localhost.  I can connect to it via telnet reliably.  However, rdkafka in the example app shown above fails with those error messages, but then ultimately works!  I'm not sure what's going on since usually when I see "brokers are down" I don't expect it to ultimately work.  Why is it complaining about the broker being down, then able to actually do the list anyway?

I'm not sure how I got things into this state, or even what state this is in for sure.

--Michael

**Comment by edenhill** [comment]
Ah, I think I know what's wrong.
The brackets around the hostname indicate an IPv6 address, and 'localhost' probably resolves both to IPv6 localhost (::1) and IPv4 localhost (127.0.0.1) on your system, while your Kafka broker might only be listening on IPv4. librdkafka will attempt to connect to all addresses returned by the name resolver, 
that's why it fails first and then works.

Try these two commands and see which one works:
`rdkafka_example -L -X broker.address.family=v6`
and
`rdkafka_example -L -X broker.address.family=v4`

My bet is on the latter.

**Comment by skandragon** [comment]
That is in fact the case.  Thanks!  Now, I need to find out why the broker isn't on ipv6, too.
