### ISSUE TITLE
Library handling when output queue is full

### ISSUE THREAD

**Issue by skandragon** [edenhill/librdkafka#306]
I'm thinking about how clients will typically handle queue full messages when producing.  My current thoughts are to add two options to the topic, where one can specify:

*  The time to wait between retries
*  The number of times to retry

If the error is other than ERR__QUEUE_FULL, it will return immediately, otherwise it will loop, basically with this:

```
do {
    try to queue
    if error == ERR__QUEUE_FULL
        poll(delay_ms)
} while (error == ERR__QUEUE_FULL && retries-- > 0);
```

Questions before I begin on this:

One, does it seem reasonable to do it this way?
Two, should there be a send-time override?

I thought about making this a producer characteristic, but in our applications some things are more important than others, and are entirely topic based.

**Comment by edenhill** [comment]
**DISCLAIMER**
All data interfaces in librdkafka are asynchronous, and while this might seem inconvenient at times it is for the better as it provides a time consistent API and also requires the application developer to properly think through and handle backpressure.
Providing a configuration option to turn on sync behaviour when the queue is full makes it too easy to say: "oh yeah, thats probably a good thing to turn on", only to try figuring out months later in production (always in production) when the application suddenly stalls, builds up a backlog and causes backpressure up the data pipeline where it wasn't expected.

For some applications a suddenly sync interface is okay, for some it is not, librdkafka sure doesn't know, most of the time the application developer doesn't know either :)


With that out of the way: sure that might be a good idea:
 * a per-topic configuration property (probably time based rather than retry based): `produce.queue.full.retry.timeout.ms` (or something longer if possible)
 * a produce() flag to turn it on for each invocation (e.g. `..MSG_F_BLOCK`)

This allows the application to know when a blocking call might occur, e.g.:

````
     r = rd_kafka_produce(..., 0);
     if (r == -1 && ...QUEUE_FULL) {
         proper_backpressure_handling();
         r = rd_kafka_produce(...., MSG_F_BLOCK);
     }
     if (r == -1) { 
         error_handling..
     }
````

What do you think?

**Comment by skandragon** [comment]
The reason I went with a count for the "number of retries" and a delay for the "how hard to try" was so we could indicate how hard to try inside each loop, and then an upper bound of how long to try.  They could certainly both be times, but then it might be easy to do silly things too, like say "try for a total of 100ms but wait 1s between retries so we don't consume CPU" -- in effect, this would be 1s total time.

I'm just trying to make the client code simpler, and cover what seems to be a common usage pattern most of our client code uses.  If the pattern I'm trying to push into rdkafka is really a bad one, that's a good discussion to have too!  Most of our code is doing a "read an item from somewhere, process it in some way, emit it into Kafka as fast as possible, without dropping" while at the same time doing "emit statistics about our work to another topic, but if that fails, don't stop processing!"

**Comment by edenhill** [comment]
There is now an experimental blocking API (pass RD_KAFKA_MSG_F_BLOCK to produce()) in master.
