### ISSUE TITLE
statistics callback

### ISSUE THREAD

**Issue by skandragon** [edenhill/librdkafka#307]
I'm thinking of doing monitoring of a Kafka producer and consumer through Kafka.  Basically, I want to gather internal statistics from inside my own apps, and then augment it with the librdkafka statistics.

Is it safe to call other rdkafka methods from the statistics (aka log) callback?  I assume no, and if not, how can I acquire the stats to include in my telemetry?

If there's a method to call to generate them, that would work.  If there's not, I could store the string, but then I'm always slightly out of sync with reality as my app-generated stats will never completely line up with the librdkafka stats.

**Comment by edenhill** [comment]
It is generally not safe to call any of the librdkafka APIs from within a callback, but in the case of stats_cb it should be safe.

Stats collection is performed in a background thread (the main rdkafka thread) at configured intervals and instead of locking the topic and partition objects to gather its counters it atomically reads counter variables belong to the various rdkafka broker threads.
What this effectively means is that specific stats counters may be slightly out of sync even within the same stats_cb, e.g., it is possible that `rx` has accounted for a received message but `rxbytes` hasn't.

And due to the asynchronous nature of multi threaded programs even if the stats counters were intra-synced the counters would be outdated by the time your application reads them.

**Comment by skandragon** [comment]
I would like to include the stats in a message I send to a remote monitoring system.  As things stand now, it is hard to do that since I use Kafka to send the message to the remote system. :)

What I would like is one of these options:

(1)  I can call Kafka from the callback, which is scary, so it's a last resort.
(2)  I can call the "collect statistics" call from my application, and get the JSON formatted data that way.

It's ok if (2) is a "as of the last update" thing -- which I could do myself if exposing the gathering is not an option.

**Comment by skandragon** [comment]
I completely understand that an instantaneous snapshot of the stats is not self-consistent, but over time will be eventually consistent, and usable only for trends, not absolutes.

**Comment by edenhill** [comment]
I think option 1) should be safe actually. There are no locks held at that point and it doesn't rely on any internal state.

**Comment by skandragon** [comment]
kk, I'll make a patch for the code and the callback docs, so we know this :)

**Comment by edenhill** [comment]
We're good here, right?
