### ISSUE TITLE
Relocatable RPMs

### ISSUE THREAD

**Issue by edenhill** [edenhill/librdkafka#3102]
There is a need for relocatable RPMs, which seem to boil down to adding `Prefix: /usr` to the spec file. But how does this interact with `{_libdir}` et.al?

https://github.com/edenhill/librdkafka/blob/master/packaging/rpm/librdkafka.spec

Do you have any input on this, @remicollet ?

**Comment by remicollet** [comment]
relocatable RPMs doesn't work, never try to use this.

What is the need ?

**Comment by rolandyoung** [comment]
I'm guessing the need is the one mentioned in the comments here: https://serverfault.com/a/773985 (user wants to install without sudo access).
That answer also explains why not to make an RPM relocatable: Fedora guidelines strongly discourage them, because installers and dependency managers, including yum, apparently can't cope well with them.

**Comment by remicollet** [comment]
By definition, RPM are system, so cannot be installed without root privilege

Another need is to install multiple versions, but this can be managed in RPM, using a different prefix, or bumping soname (the way I do for php, to use the latest version, not the default one in the distribution).

**Comment by edenhill** [comment]
Thank you for your input, @remicollet , very valuable. I'll close this as wontfix.
