### ISSUE TITLE
rdkafka#producer-106| Unable to create broker thread: Resource temporarily unavailable

### ISSUE THREAD

**Issue by prabcs** [edenhill/librdkafka#312]
Hi,

I'm seeing this error.
I'am producing to the broker to only 1 topic in 1 thread.
I think the threads that the error refers to is internal to librdkafka.

Also, I see this error on the broker log on kafka server machines:-

[2015-06-19 06:57:30,622] WARN [KafkaApi-3] Produce request with correlation id 749 from client rdkafka on partition [qos.6994.135,180] failed due to Leader not local for partition [qos.6994.135,180] on broker 3 (kafka.server.KafkaApis)

**Comment by edenhill** [comment]
That's weird, is your application using a lot of threads? Do you have a low thread ulimit?

**Comment by edenhill** [comment]
ping?

**Comment by DEvil0000** [comment]
do you use multiple brokers?
what is the replication factor of your topic?
is there a leader active and working for every partition?
is producing and consuming with kafka command line tools working?
is your ZK working correct?
have you tried to restart ZK & Kafka (in correct order and with some wait time)?
do you use some key? what is your key and how long is it?
networking issue?

**Comment by prabcs** [comment]
Apologies for the delay. I was out on vacation.

edenhill:
1. My application was writing only to 1 topic and using just 1 thread.
2. not sure how thread ulimit would affect a single thread here?

DEvil0000:
1. I 'm using a 3 node cluster
2. The replication factor is 1. I've created 255 partitions for this topic on this 3 node cluster
3. Yes, the leader is active and working for each partition. Because the replication factor is 1, out of the 3 nodes, ideally, each node is being a leader for 85 partitions of a topic. Is there a limit to the number of partitions for which a node can become a leader of?
4. yes. Producing and consuming are both working fine with command line tools
5. ZK log is not showing any problems
6. nope. I haven't restart ZK or kafka. What are the reasons for which I should be doing that ? Do the restarts have to be a regular activity ?
7. I dont use any key here. I'm selecting a partition for the data by using a hash function on the data. So, I'm not using the default partitioner. 
8. Not sure.

**Comment by DEvil0000** [comment]
>1. My application was writing only to 1 topic and using just 1 thread.
>2. not sure how thread ulimit would affect a single thread here?

rdkafka is of course using some more threads inside of the lib
>2. The replication factor is 1. I've created 255 partitions for this topic on this 3 node cluster

this does not make much sense. in my understanding your partition count should not be greater then your node count. you can add more partitions when you add more nodes later.
>3. Yes, the leader is active and working for each partition. Because the replication factor is 1, out of the 3 nodes, ideally, each node is being a leader for 85 partitions of a topic. Is there a limit to the number of partitions for which a node can become a leader of?

i don't know
>6. nope. I haven't restart ZK or kafka. What are the reasons for which I should be doing that ? Do the restarts have to be a regular activity?

when I was testing ZK and Kafka I got some wired problems because Kafka was starting before ZK finished starting or when ZK started to shutdown before Kafka finished the shutdown.
It may also happen that Kafka loses the ZK connection.
In a good setup there should not be a need to do this but I don' assume a good setup because it looks like the problems I had ;)
>Could this issue have been created if I do not use this in my code:-
>RdKafka::wait_destroyed(5000);

only if your problem only occurs on shutdown of your application.

**Comment by edenhill** [comment]
Since librdkafka is purely asynchronous it will decommission itself in the background after your call to `rd_kafka_destroy()` or delete of the handle.
Thus if your application repeatedly creates, uses , and destroys kafka handles in quick succession it is possible that you do this faster than librdkafka is able to decommission its threads and that will eventually lead to the number of threads exceeding the ulimit.

But this application design seems questionable, librdkafka handles are costly to set up and should be reused as far as possible (there is very little cost in persisting an idle handle until you need it)
