### ISSUE TITLE
%4|1434713706.863|METADATA|rdkafka#producer-1| 198.18.85.154:9092/2: Metadata request failed: Local: Message timed out

### ISSUE THREAD

**Issue by prabcs** [edenhill/librdkafka#313]
Hi,

In what cases would be get this error ?

%4|1434713706.863|METADATA|rdkafka#producer-1| 198.18.85.154:9092/2: Metadata request failed: Local: Message timed out

Thanks

**Comment by prabcs** [comment]
I'm seeing all these errors:-

%3|1434713791.196|FAIL|rdkafka#producer-1| 198.18.85.154:9092/2: 7 request(s) timed out: disconnect
%3|1434713791.196|ERROR|rdkafka#producer-1| 198.18.85.154:9092/2: 7 request(s) timed out: disconnect
%4|1434713791.197|METADATA|rdkafka#producer-1| 198.18.85.154:9092/2: Metadata request failed: Local: Message timed out
%4|1434713791.197|METADATA|rdkafka#producer-1| 198.18.85.154:9092/2: Metadata request failed: Local: Message timed out
%4|1434713791.197|METADATA|rdkafka#producer-1| 198.18.85.154:9092/2: Metadata request failed: Local: Message timed out
%3|1434713792.146|FAIL|rdkafka#producer-1| 198.18.85.155:9092/3: 10 request(s) timed out: disconnect
%3|1434713792.147|ERROR|rdkafka#producer-1| 198.18.85.155:9092/3: 10 request(s) timed out: disconnect
%4|1434713792.147|METADATA|rdkafka#producer-1| 198.18.85.155:9092/3: Metadata request failed: Local: Message timed out
%4|1434713792.147|METADATA|rdkafka#producer-1| 198.18.85.155:9092/3: Metadata request failed: Local: Message timed out
%4|1434713792.147|METADATA|rdkafka#producer-1| 198.18.85.155:9092/3: Metadata request failed: Local: Message timed out
%3|1434713792.544|FAIL|rdkafka#producer-1| 198.18.85.154:9092/2: 7 request(s) timed out: disconnect
%3|1434713792.544|ERROR|rdkafka#producer-1| 198.18.85.154:9092/2: 7 request(s) timed out: disconnect
%4|1434713792.544|METADATA|rdkafka#producer-1| 198.18.85.154:9092/2: Metadata request failed: Local: Message timed out
%4|1434713792.544|METADATA|rdkafka#producer-1| 198.18.85.154:9092/2: Metadata request failed: Local: Message timed out
%4|1434713792.545|METADATA|rdkafka#producer-1| 198.18.85.154:9092/2: Metadata request failed: Local: Message timed out
%3|1434713793.497|FAIL|rdkafka#producer-1| 198.18.85.155:9092/3: 10 request(s) timed out: disconnect
%3|1434713793.497|ERROR|rdkafka#producer-1| 198.18.85.155:9092/3: 10 request(s) timed out: disconnect
%4|1434713793.497|METADATA|rdkafka#producer-1| 198.18.85.155:9092/3: Metadata request failed: Local: Message timed out
%4|1434713793.497|METADATA|rdkafka#producer-1| 198.18.85.155:9092/3: Metadata request failed: Local: Message timed out

**Comment by edenhill** [comment]
Looks like a network issue, the client is not getting any responses to its requests.
Check network connectivity and also the broker logs for hints.

**Comment by prabcs** [comment]
Can this happen if i dont close the connections ?

**Comment by DEvil0000** [comment]
maybe tcp keepalive?

**Comment by edenhill** [comment]
Reopen if reseen

**Comment by AKR2015** [comment]
Could any please help on this below issue..

I am using Kafka 9.0.1
rdkafka :9.0.1
librdkafka: 9.0.1

thank you for your help.

3|2016-10-21 10:26:33.546|rdkafka#producer-37|FAIL| usiadansetl04:9092/2: 3 request(s) timed out: disconnect
3|2016-10-21 10:26:33.546|rdkafka#producer-37|ERROR| usiadansetl04:9092/2: 3 request(s) timed out: disconnect

3|2016-10-21 10:26:35.733|rdkafka#producer-37|FAIL| usiadansetl04:9092/2: 3 request(s) timed out: disconnect
3|2016-10-21 10:26:35.733|rdkafka#producer-37|ERROR| usiadansetl04:9092/2: 3 request(s) timed out: disconnect
5|2016-10-21 10:26:37.093|rdkafka#producer-37|FAIL| usiadansetl04:9092/2: Connection closed
3|2016-10-21 10:26:37.093|rdkafka#producer-37|ERROR| usiadansetl04:9092/2: Connection closed
4|2016-10-21 10:26:41.186|rdkafka#producer-41|METADATA| usiadansetl03:9092/1: Metadata request failed: Local: Timed out
rdkafka#consumer-64|FAIL| 10.61.19.88:9092/bootstrap: Connection closed
rdkafka#consumer-64|ERROR| 10.61.19.88:9092/bootstrap: Connection closed
rdkafka#consumer-62|FAIL| 10.61.19.88:9092/bootstrap: Connection closed
rdkafka#consumer-62|ERROR| 10.61.19.88:9092/bootstrap: Connection closed
rdkafka#producer-61|FAIL| 10.61.19.88:9092/bootstrap: Connection closed

if i increase the *batch.num.messages*, the error i get in broker log is similar to below

org.apache.kafka.common.network.NetworkReceive.readFromReadableChannel(NetworkReceive.java:91)
at org.apache.kafka.common.network.NetworkReceive.readFrom(NetworkReceive.java:71)
at org.apache.kafka.common.network.KafkaChannel.receive(KafkaChannel.java:153)
at org.apache.kafka.common.network.KafkaChannel.read(KafkaChannel.java:134)
at org.apache.kafka.common.network.Selector.poll(Selector.java:286)
at kafka.network.Processor.run(SocketServer.scala:413)
at java.lang.Thread.run(Thread.java:745)
[2016-10-06 22:17:42,001] WARN Unexpected error from /10.61.48.28; closing connection (org.apache.kafka.common.network.Selector)
org.apache.kafka.common.network.InvalidReceiveException: Invalid receive (size = 1969447758 larger than 104857600)
at

**Comment by edenhill** [comment]
The timeouts happen when the broker can't keep up with the producer message rate.

The InvalidReceiveException is fixed on latest librdkafka master, please give it a spin.

**Comment by AKR2015** [comment]
@edenhill, appreciated your feedback on this.
Here is my kafka cluster specification-
**Kafka cluster : 3 vms with each one has 4 vcpu, 8 gb RAM**

in terms of producing the messages, its only around 200k every 2-3 minute. these messages are not of same sizes.. 
will try to increase the cluster config and try. will try librdkafka from master branch and let you know.
thanks for your help.

**Comment by DEvil0000** [comment]
Things I can think off affecting this:
How many partitions per topic?Whats the replication factor?Whats your ack config (producer/broker)? Whats your avg message size?Whats your IO bandwith (disk)?Whats your network bandwith?

Von meinem Samsung Gerät gesendet.

-------- Ursprüngliche Nachricht --------
Von: AKR2015 <notifications@github.com> 
Datum: 25.10.2016  12:37  (GMT+01:00) 
An: edenhill/librdkafka <librdkafka@noreply.github.com> 
Cc: "A. Binzxxxxxx" <alexander@binzberger.de>, Comment <comment@noreply.github.com> 
Betreff: Re: [edenhill/librdkafka]
  %4|1434713706.863|METADATA|rdkafka#producer-1| 198.18.85.154:9092/2: Metadata
  request failed: Local: Message timed out (#313) 

@edenhill, appreciated your feedback on this.

Here is my kafka cluster specification-

Kafka cluster : 3 vms with each one has 4 vcpu, 8 gb RAM

in terms of producing the messages, its only around 200k every 2-3 minute. these messages are not of same sizes.. 

will try to increase the cluster config and try. will try librdkafka from master branch and let you know.

thanks for your help.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/edenhill/librdkafka","title":"edenhill/librdkafka","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/edenhill/librdkafka"}},"updates":{"snippets":[{"icon":"PERSON","message":"@AKR2015 in #313: @edenhill, appreciated your feedback on this.\r\nHere is my kafka cluster specification-\r\n**Kafka cluster : 3 vms with each one has 4 vcpu, 8 gb RAM**\r\n\r\nin terms of producing the messages, its only around 200k every 2-3 minute. these messages are not of same sizes.. \r\nwill try to increase the cluster config and try. will try librdkafka from master branch and let you know.\r\nthanks for your help."}],"action":{"name":"View Issue","url":"https://github.com/edenhill/librdkafka/issues/313#issuecomment-255999680"}}}

**Comment by edenhill** [comment]
Please also provide logs with debug=protocol enabled

**Comment by edenhill** [comment]
@AKR2015 Also please dont hijack other issues (you've pasted the above comment in at least three other (mostly unrelated) issues).

**Comment by AKR2015** [comment]
@edenhill- apologizes about that.
1. yes, broker is not able to keep up with producer message rate. verified by slowing down the producer.
2. The invalid message size is fixed by using latest librdkafka.

The additional details are 
1. a topic with 12 partitions with RF=1
2. the message size varies between(10 kb to 1 mb)
3 IO stats
10:37:49 PM   UID       PID   kB_rd/s   kB_wr/s kB_ccwr/s  Command
10:37:51 PM     0      7315      0.00   3992.00      0.00  java
10:37:53 PM     0      7315      0.00   2814.00      0.00  java
10:37:55 PM     0      7315      0.00   3756.00      0.00  java
10:37:57 PM     0      7315      0.00   3170.00      0.00  java
10:37:59 PM     0      7315      0.00   4940.00      0.00  java
10:38:01 PM     0      7315      0.00   2802.00      0.00  java
10:38:03 PM     0      7315      0.00   3660.00      0.00  java
10:38:05 PM     0      7315      0.00   3888.00      0.00  java
10:38:07 PM     0      7315      0.00   3608.00      0.00  java
10:38:09 PM     0      7315      0.00   3896.00      0.00  java
Average:        0      7315      0.00   3652.60      0.00  java


will provide the debug log soon.

Thanks for your help.

**Comment by DEvil0000** [comment]
3652kB/s is quite slow.
So I guess you have very slow disks or your broker/producer configuration is quite strange. Also check FS jornaling.
I get about 3-11MB/s write speed with kafkacat consumer piped to kafkacat producer

**Comment by AKR2015** [comment]
@DEvil0000 - IO could be slow in my env. my clusters are in vcloud on SAN storage.
from the kafka configuration side, i am using the defaults as of now.

One thing i am noticing it consume and produce the message very fast in first 4-5 minutes and then it slows down and around after few minute later it stop consuming/producing messages

**Comment by DEvil0000** [comment]
I do not know your setup or software so I can't really help you but here are some performance hints which could help you here:If it is fast at the beginning and getting slow later it sounds like disk or network is too slow. If you have some idle cpus you could compress your messages with lzw or whatever does strong compression on your data. Use a binary packed format insted of plain text.You could turn off jornaling if any. The kafka data could reside on a separate partition or even disc array/raid.Adding more brokers or separate the broker to an other machine migth also help.Do not use virtual machines and if you do you should not use virtual discs. Use a raw partition mount instead.Use SSDs instead of old school magnetic discs.
Von meinem Samsung Gerät gesendet.

-------- Ursprüngliche Nachricht --------
Von: AKR2015 <notifications@github.com> 
Datum: 27.10.2016  15:24  (GMT+01:00) 
An: edenhill/librdkafka <librdkafka@noreply.github.com> 
Cc: "A. Binzxxxxxx" <alexander@binzberger.de>, Mention <mention@noreply.github.com> 
Betreff: Re: [edenhill/librdkafka]
  %4|1434713706.863|METADATA|rdkafka#producer-1| 198.18.85.154:9092/2: Metadata
  request failed: Local: Message timed out (#313) 

@DEvil0000 - IO could be slow in my env. my clusters are in vcloud on SAN storage.

from the kafka configuration side, i am using the defaults as of now.

One thing i am noticing it consume and produce the message very fast in first 4-5 minutes and then it slows down and around after few minute later it stop consuming/producing messages

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/edenhill/librdkafka","title":"edenhill/librdkafka","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/edenhill/librdkafka"}},"updates":{"snippets":[{"icon":"PERSON","message":"@AKR2015 in #313: @DEvil0000 - IO could be slow in my env. my clusters are in vcloud on SAN storage.\r\nfrom the kafka configuration side, i am using the defaults as of now.\r\n\r\nOne thing i am noticing it consume and produce the message very fast in first 4-5 minutes and then it slows down and around after few minute later it stop consuming/producing messages\r\n"}],"action":{"name":"View Issue","url":"https://github.com/edenhill/librdkafka/issues/313#issuecomment-256639414"}}}
