### ISSUE TITLE
[question] kubernetes clusterip vs headless service

### ISSUE THREAD

**Issue by rjshrjndrn** [edenhill/librdkafka#3150]
Hi,
Thank you for this awesome library. I'm trying to connect to a kafka cluster running in the kubernetes cluster.
I've a service `kafka.default.svc.cluster.local (clusterIP)` and  `kafka-headless.svc.cluster.local (headless)`. This service is loadbalancing b/w 2 brockers.

for my application(which uses librdkafka) I've one environment variable `KAFKA_SERVERS (which points to bootstrap.servers in librdkafkka)`. Should I keep that to clusterIP ( which will loadbalance b/w the 2 brockers) or the headless( dns resolution will give 2 ips, and its up to librdkafka to decide which one to take up)

Any pointers appreciated.

**Comment by rolandyoung** [comment]
It doesn't matter very much which of these you put in the bootstrap.servers, because librdkafka only uses that to contact one of the brokers. That broker then tells librdkafka what addresses to use to connect to all the brokers in the cluster. It is very important that the address it gives out ("advertised.listeners" in the server config) will work for the Kafka clients.
See https://hub.docker.com/r/wurstmeister/kafka to get an idea of some of the issues you need to address and how the authors of a very popular Docker image for Kafka have addressed them.

**Comment by rjshrjndrn** [comment]
Thank you @rolandyoung. That was an awesome read. I figured out, it should be the **headless service as a hard rule**; because the advertised ips will be the pod ips itself, as the advertised address filed have value
```
advertised.listeners=INTERNAL://kafka-0.kafka-headless.db.svc.cluster.local:9093,CLIENT://kafka-0.kafka-headless.db.svc.cluster.local:9092
```
