### ISSUE TITLE
About conf: max.poll.record 

### ISSUE THREAD

**Issue by kevinfitzroy** [edenhill/librdkafka#3234]
Description
===========
I found that max.poll.record cannot be configured. Does librdkafka have plans to add this configuration?
*Our usage scenarios*:
The processing time of each message is very long, and there are multiple consumer clients, so I hope to set max.poll.record = 1.

**Comment by edenhill** [comment]
librdkafka's consumer_poll() API will only return one message at a time, so there is no need for a max.poll.records

**Comment by ym2048** [comment]
I use wireshark to capture the packets, and find that fetch response will return more than one records.
<img width="351" alt="image" src="https://user-images.githubusercontent.com/3700288/172579855-42b1e4f5-a3d3-4190-8ac0-d487e6b2967e.png">


software info:
librdkafka 1.8.2
PHP 7.4.29

**Comment by LGouellec** [comment]
@ym2048  
Librdkafka pre-fetch messages from broker and store them into a local queue. 
High level consumer take one message into the local queue and return it one at time.

**Comment by ym2048** [comment]
@LGouellec

**Comment by LGouellec** [comment]
This poll interval means the interval between two consume call in the high level consumer, not prefetch messages from broker

**Comment by smares** [comment]
I am confused about `max.poll.interval.ms` and `max.poll.records`. Let's say `max.poll.interval.ms` is set to the default 5 minutes and I have a consumer that takes 1 minute to process a single message. Given the default for `max.poll.records` is 500, does that mean I will always run into trouble (= rebalancing)? While reading the documentation, I assumed the first poll will fetch 500 messages and put them into an internal queue. Then I process the first message, 1 minute since the poll that retrieved 500 messages passes, then the second message, 2 minutes pass, third message, 3 minutes, fourth message, 4 minutes, fifth message, 5 minutes, BOOM, there hasn't been a poll for `max.poll.interval.ms`.
