### ISSUE TITLE
rd_kafka_consumer_poll() returns NULL while consuming

### ISSUE THREAD

**Issue by reddybhargava** [edenhill/librdkafka#3506]
Read the FAQ first: https://github.com/edenhill/librdkafka/wiki/FAQ

Description
===========
Hi,

So my use case for kafka is consuming messages from the beginning of an existing topic (after entire production is complete) always. So I'm setting `enable.auto.commit=false` and `auto.offset.reset=earliest` accordingly. But when I'm consuming messages I get a lot of NULL messages in between consumption. What could be the reason for this? Why is NULL returned when there are still messages to be consumed ?
When using poll_timeout of 100ms, I see about 1000 NULL responses (with around 700k messages in the topic) and when I increase the timeout, the number of NULLs received decreases. 

When I perform no processing after consumption, I see higher throughput and higher CPU usage by broker threads. Both throughput and CPU usage reduce by half even for minimal processing operations. Am I doing something wrong with any config  setting here?

I'm only consuming from one topic by running a single consumer. Each message in the topic are of size 30k - 60k bytes.
Could I change any config setting to suit my needs better?
I know I can probably achieve better performance with multiple consumer instances, but wanted to know how I could improve on my current situation.

How to reproduce
================
I've used the example consumer given in the repo and developed on it. I do some processing with messages after consuming them. 

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): `1.7.0 (0x010700ff)`
 - [x] Apache Kafka version: `kafka_2.13-2.8.0`
 - [x] librdkafka client configuration: `fetch.message.max.bytes=655360`,`socket.receive.buffer.bytes=655360`,  `queued.min.messages=1000000`,  `auto.offset.reset=earliest`, `enable.auto.commit=false`
 - [x] Operating system: `Linux`
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
Recommend you use default settings as much as possible since those settings should work fine for most use-cases.

The consumer will return NULL rather than a message if there are no messages pre-fetched in the queue. This can be due to a couple of reasons:
 * No more messages on the broker (does not seem to be the case here). You can check this by setting `enable.partition.eof=true` and then look for a ERR__PARTITION_EOF error in a returned message object.
 * Partition has been paused by pause().
 * Consumer can't fetch messages fast enough. This could be because of slow network, slow broker, under powered client machine (high CPU usage), or simply that the processing time is lower than the time it takes to fetch messages. You can troubleshoot this by setting `debug=fetch`.

**Comment by reddybhargava** [comment]
okay thanks will try those and reopen if i face any other issues.
