### ISSUE TITLE
How to build a librdkafka shared library file(.so) for the Android armeabi-v7a architecture 

### ISSUE THREAD

**Issue by sarathsureshh** [edenhill/librdkafka#3594]
Hi, I was trying to find ways on building the shared library(.so) files for the librdkafka for Android armeabi-v7a architecture, not much familiar in this area, please help out. 

The specifications are,

OS used for building: Windows 10
OS for deploying: Android
Version: librdkafka.redist.0.9.4
Visual Studio 2019. 

Thanks in advance :)

**Comment by OneCricketeer** [comment]
Android runs Java code, so there's not really a need for using this library in it.

However, due to network instability of mobile clients, and persistent connections to Kafka, Android devices definitely should not be consumers. If you need to produce data, it's better to expose that via an HTTP endpoint such as the Kafka REST proxy or your own server
