### ISSUE TITLE
question about EventCb

### ISSUE THREAD

**Issue by better629** [edenhill/librdkafka#364]
Hi
   When I run the rdkafka_example.cpp with parameters of "-P -t batch_test_1 -o beginning"
   It occurs to me that :
% Created producer rdkafka#producer-0
LOG-5-TOPICBRK: Topic batch_test_1 [1] migrated to unknown broker 3: requesting metadata update
LOG-5-TOPICBRK: Topic batch_test_1 [0] migrated to unknown broker 2: requesting metadata update
LOG-5-TOPICBRK: Topic batch_test_1 [0] migrated to unknown broker 2: requesting metadata update

It has connected to the brokers(I can see the logsize and lag in KafkaMonitor), so what's the problem? Does it mean that I have not connected the broekrs.

**Comment by edenhill** [comment]
That should be a debug message, it is an intermediary situation while parsing the metadata reply: it learns of the topics and partitions before it learns of the brokers, so a partition will momentarily point to an unknown broker. You can disregard this message.

This will be fixed prior to 0.8.7 release.

**Comment by better629** [comment]
Hi
  I find that in 0011-produce_batch.c "rkmessages = calloc(sizeof(*rkmessages), msgcnt);" but the usage of calloc is calloc(size_t n, size_t size). Is that right ??

**Comment by edenhill** [comment]
The order of calloc arguments don't matter

**Comment by better629** [comment]
Hi
   Why in librdkafka c++ ,the batch is not supplied ? I tested rd_kafka_produce and ra_kafka_produce_batch both with same configuration ( message nums ,message size and so on),but they cost almost same time to produce messages. How to speed producing message with rd_kafka_produce_batch ??

**Comment by edenhill** [comment]
The C++ interface is lagging behind the C interface somewhat.

It has turned out that produce_batch() is not always faster than produce(), possibly due to cache eviction, but it depends on your usage of batch. If you specify a specific `partition` (rather than PARTITION_UA) it should be faster, but for PARTITION_UA (i.e., use partition) it might not be.


What message rate are you looking to achieve and what is the current message rate you get with produce() and produce_batch()?

**Comment by better629** [comment]
Hi
  I am not sure for particular message rate but faster rate. Now in my mac pro(8g ,2.6GHz,i5), the cost of 100000 messages with per message 70byte is 0.8s what ever in which method .

**Comment by better629** [comment]
and I test the rdkafka_performance.c in my latop with Test1 , the result is about 3Mb/s which is far from your 80Mb/s. Is machine Configuration is the main problem. By the way ,my brokers are not in local server.

**Comment by edenhill** [comment]
You will need to check network capacity, and CPU capacity on both the client and broker nodes.

**Comment by better629** [comment]
Hi 
    I'm confused about rd_kafka_poll.
   1、 That is if I don't use rd_kafka_poll , the KafkaMonitor won't see the lag I send to broker. Instead I can. Why can it be, Is it not the method to poll the handler to the event?
   2、I use clock() to compute execution time. If I use rd_kafka_poll(producer , 0) , the result is the time that from the begining to the end of all the messages nums shown in KafkaMonitor(A tool I can see the produce message num in the brokers). But if I use rd_kafka_poll(producer , a num bigger than 0) , the execution time will be very short, and I will see the result in the console, but the num of all messages is still not shown in KafkaMonitor. Have you compared the performance of KafkaClient(python) with your tool.

**Comment by edenhill** [comment]
There are some performance numbers here:
https://github.com/edenhill/librdkafka/blob/master/INTRODUCTION.md#performance

rd_kafka_poll() with a timeout_ms of 0 means it will not block but return immedately if there are no events to be handled, with a timeout > 0 it will block for that time waiting for an event if there are none initially.

If you call poll(,... timeout_ms > 0) after each produce() call you will get bad performance since it will most likely slow down your produce loop by min(timeout_ms, broker_roundtrip_time).
You should generally call poll(.., 0) if you are calling it from your produce() loop.
Another alternative is to create a separate thread that only does poll(.., 1000); or so.

**Comment by better629** [comment]
Hi 
   How to query data with a limitation that some fields will not return.?
   I know the query method realized the method with the pramaters fieldToReturn, is there any methods?
