### ISSUE TITLE
DeliveryReportCb::dr_cb is not called correctly

### ISSUE THREAD

**Issue by ankurjohri** [edenhill/librdkafka#367]
Hi,

I have a requirement to call produce API of producer synchronously. However, the API is async, it returns immediately irrespective of the result of the operation. I believe, the sync mechanism can be achieved using callback DeliveryReportCb::dr_cb. Once dr_cb is called with SUCCESS, wrapper can return to the end application programs. Is that true, can this functionality be achieved like this?
If yes, there looks to be an issue in the callback functionality. The callback is not called for the same message but it is for the previous message. For example, when message 1 is sent, there is no callback, when message 2 is sent, callback for message 1 is received, when message 3 is sent, callback for message 2 is received and so on. Please confirm if this observation is correct and if yes, is there any work around for this?
Thanks,
Ank

**Comment by edenhill** [comment]
Hi,

please have a look at the wiki page on implementing a sync producer:
https://github.com/edenhill/librdkafka/wiki/Sync-producer

**Comment by ankurjohri** [comment]
Thanks Eden, this is useful.
Typically, how much time API takes in case of async and sync modes?

**Comment by edenhill** [comment]
The async APIs will not block at all, they are instantaneous.
If you implement the sync approach given in the wiki link it will block for the time it takes to produce a message and get a reply back from the broker (i.e., network latency + broker processing time), which is usually around ~20 ms.

**Comment by ankurjohri** [comment]
I implemented the sync model as given in wiki link using cpp library. However, it was taking all the CPU (more than 100%). This is because we use a completely blocked while loop to call poll. I am wondering if poll uses a periodic sleep of few msec, it should not happen like that. For now, I used a sleep for 5 msec in while loop and it helped. Do you have any better way to address this issue?

Another question I have is on latency. As you mentioned, latency of ~20 ms is likely to be received. But for my implementation, I am getting it to be very high. It is coming out to be around 240 ms. I just have one host and 1 broker and writing to local broker of localhost.

**Comment by edenhill** [comment]
You should provide a reasonable timeout to rd_kafka_poll() in your wait loop, it can really be any large value since you want to block until a reply is available. E.g., 1000 ms.

Having a low or no timeout will cause a busy loop, as you've discovered.

For the latency part you enable "protocol" debugging to see the round trip time (rtt) of each request.
You want to look for the ProduceRequest and ProduceResponse, see here:

````
%7|1442269425.435|SEND|rdkafka#producer-0| [thrd:bib.local:9091/1]: bib.local:9091/1: Sent ProduceRequest (v0, 83 bytes, CorrId 2)
%7|1442269425.439|RECV|rdkafka#producer-0| [thrd:bib.local:9091/1]: bib.local:9091/1: Received ProduceResponse (v0, 28 bytes, CorrId 2, rtt 3.73ms)
`````

If that rtt is high it means the network or broker has that latency, if the rtt is low it means the latency is inside librdkafka - typically in the transmit queue because of batching. See batching.num.messages and queue.buffering.max.ms config properties.

**Comment by ankurjohri** [comment]
I am already using poll interval to be 1000 (m_kafkaProducer->poll(1000);) Even with that, CPU reaches to more than 100%. When I added usleep(5000), it becomes normal to 6%. I did not get the poll API completely. It says "The 'timeout_ms' argument specifies the minimum amount of time
   * (in milliseconds) that the call will block waiting for events." What does minimum mean here, shouldn't it be maximum time?

For latency issue, setting batch.num.messages to 1 helps. Latency has come out to 22 ms. Thanks.

**Comment by edenhill** [comment]
Can you paste your code around the poll() call?


You usually dont want to decrease batch.num.messages since it will affect throughput, the larger the batches the better.
It is better to decrease queue.buffering.max.ms which controls how long it will wait for a batch to reach batch.num.messages.
Good values for high throughput and low latency is:
 `queue.buffering.max.ms=1` 
 `batch.num.messages=<expect number of messages per millisecond> x 2`

Yeah, timeout_ms should say maximum :)

**Comment by ankurjohri** [comment]
Here is the CPP implementation.

    while ((mode == sync) && (err == RdKafka::ERR_UNKNOWN)) {
        kafkaProducerInstance->poll(1000);
        usleep(5000); //Sleep for 5 msec
    }

I tried queue.buffering.max.ms to 1 and latency results look okay, however the kind of application we are using requires complete guarantee of message delivery. In that case, I think batch.num.messages=1 would be a better option. Also, we create topic with flush.messages=1 to have these messages completely written on disk. Does this sync model (with callback) assure that messages are also written on disk when topic used is for flush.messges=1?

**Comment by edenhill** [comment]
Yes, if you use `request.required.acks=-1` you will only get the delivery report callback when the message has been written to disk (and flushed, since you configured that too).

Why that loop spins like crazy without the usleep: I dont really know, seems weird. Can you check the return value of poll(), it should tell you how many events it processed, which should be > 0 if it returns before the timeout.

The only issues Ive seen with loops like that is this:
https://github.com/edenhill/librdkafka/issues/272

Is your application using pthread_cancel() or seteuid()?

**Comment by ankurjohri** [comment]
Okay, information regarding disk write is very useful. Thanks.
No I am not using pthread_cancel() or seteuid(). For 1 produce call, poll returns multiple times (around 224 times) all with value 0 and 2 times it returned with value 1.
But, we have a workaround with sleep in while loop.

**Comment by edenhill** [comment]
Huhm, is your application getting stray signals perhaps? Such as SIGPIPE, SIGIO, SIGALRM, etc?
Running your program in gdb will make it pause when a signal is received which might help finding out what is going on.
Basic idea is that something causes the pthread_cond_timedwait() to get interrupted for some reason.

**Comment by ankurjohri** [comment]
It should not get these signals. I ran with gdb and there is no issue. My application is making periodic produce API call after every 100 ms.

**Comment by edenhill** [comment]
Okay, then I'm out of ideas, if you have the time you will need to add debug printfs to  rd_kafka_q_serve() in src/rdkafka.c to figure out why timedwait() is returning early.
Thanks

**Comment by ankurjohri** [comment]
That's fine Eden. I am not blocked because of this issue and have a workaround for this.
Thank you so much for your help.

**Comment by edenhill** [comment]
Okay, let me know if you find anything. Will close this for the time being.

**Comment by ankurjohri** [comment]
Sure.
