### ISSUE TITLE
Batch Configurations not working

### ISSUE THREAD

**Issue by kcnguyen** [edenhill/librdkafka#368]
For testing purposes, I want to send batches of 10 messages and if the queue does not fill up to 10 messages by 5 minutes, then send whatever is in the queue to kafka. I set batch.num.messages = 10, queue.buffering.max.messages = 1000, queue.buffering.max.ms = 30000 and my queue is filling up passed 10. Even after 5 minutes, the queue does not decrease at all. Please help. Thank you.

**Comment by edenhill** [comment]
Buffering for 5 minutes is a very long time, while you typically want to buffer for as little as possible while still accumulating enough messages in the buffer to send a batch that timeout is usually no more than 100ms or so.

Make sure your message.timeout.ms is larger than queue.buffering.max.ms, otherwise the messages will time out waiting for the batch to fill up.

Having said that I dont think thats the problem here.
Does it work if you use default values for those settings? Is it able to produce messages then?

**Comment by kcnguyen** [comment]
Yeah it works if I don't set queue.buffering.max.messages, queue.buffering.max.ms, and batch.num.messages and use the default values. I will change message.timeout.ms and let you know if it fixes my problem. Thanks for the quick response :)

**Comment by kcnguyen** [comment]
I made message.timeout.ms larger than queue.buffering.max.ms, but the queues are still growing larger than batch.num.messages without delivering any message to kafka. When you mentioned earlier that the messages have a timeout while they are in queue for delivery, do they get removed from queue when they timeout? Previously, I did not see the queue decrease in size at all after the default timeout of 5 minutes passed.

**Comment by edenhill** [comment]
That might be actually be a bug, where messages are not timed out if they are waiting to get batched and the batching period is really long. Will look in to that.

I'm curious, what is your reason for waiting so long for the batch to fill up?

**Comment by edenhill** [comment]
Messages should be timed out even on the xmit queue (the batch queue):
https://github.com/edenhill/librdkafka/blob/master/src/rdkafka_broker.c#L2620

**Comment by kcnguyen** [comment]
It's just a random value I chose for testing purposes. I tried again changing queue.buffering.max.ms to 1 minute and it has the same problem that I described early. What is the longest interval for buffering the message queue that will still work?

**Comment by edenhill** [comment]
Can you reproduce this with a look like rdkafka_example or kafkacat?
Be aware though that the first bunch of messages sent will not wait for the batch to fill up, they will be sent immedately, but after that it should start batching.
So when testing first send a message, wait for it to be delivered, and then send a couple of other messages which should now take time to produce since they are accumulating in the batch queue.

E.g.:
````
$ kafkacat -b mybroker -t test -p 0 -P -X batch.num.messages=10 -X queue.buffering.max.ms=5000
msg1 is sent right away
<wait a bit>
msg2
msg3
msg4... these will take some time (5000ms) before being delivered
````

**Comment by kcnguyen** [comment]
I switched back to default values and it is working fine again, I will stick with the default settings. Thanks for the help!

**Comment by edenhill** [comment]
Good news!

**Comment by kcnguyen** [comment]
I'm still noticing that the size of the queue of messages waiting to be delivered is not updating correctly. I can see the message delivered in kafka, yet the size of the queue is not decreasing. I am calling the function rd_kafka_outq_len (rd_kafka_t *rk) to get the size of the queue. I think there is a bug here.

**Comment by edenhill** [comment]
rd_kafka_outq_len() correlates to the number of messages in different internal librdkafka queues.

Is it possible that you are not calling `rd_kafka_poll()`  to handle delivery reports?
