### ISSUE TITLE
Delivery report order sequence

### ISSUE THREAD

**Issue by rathdeep** [edenhill/librdkafka#391]
One question regarding delivery reports. If i publish Messages 1, 2,3,4,5 in this order. Is it guaranteed that delivery reports will also have same order.

Thanks.

**Comment by edenhill** [comment]
If messages are not retried then they will be in order, but if they are retried (due to temporary error)
then there is a risk that messages were not delivered in order and thus the delivery report callbacks will be unordered too.

**Comment by fsaintjacques** [comment]
This invariant is only true within one partition, if messages are routed to different partitions, then there's no guarantee on the consumer side.

**Comment by rathdeep** [comment]
Thanks. Good to know, so in case of error, even the message ordering on Kafka bus will be out of order as librdkafka might change the order before sending it to broker.

**Comment by edenhill** [comment]
librdkafka cannot guarantee ordering of messages in case messages are retried (due to intermittent errors)

**Comment by rathdeep** [comment]
lets say 1,2,3,4,5.  1,2 are successfully sent. Then there is an error for 3,4,5,

Will retry order be 3,4,5. or it is not guaranteed.

**Comment by edenhill** [comment]
The retry order is undefined.

librdkafka will typically have a number of messages in-flight to the producer, lets say:
1,2,3,4 are in flight, while 5,6,7 are waiting in the local producer queue.

If the broker rejects message 2 and 3 because the broker leader changed then messages 1,4 will be written to the broker's disk log.
While acknowledgements are on their way back from the broker to librdkafka messages 5,6,7 are sent to the broker and accepted.
When librdkafka receives the acks and sees that messages 2,3 fails it will retry them and send to the broker which now accepts them.
In effect this gives the order: 1,4,5,6,7,2,3.

While this situation is not very common it is still possible and an application must not rely on messages being ordered.
One way to fix this is to allow only one (batch of) messages in-flight at any given time, but this has performance implications since the throughput will then be bound by the broker round trip time.

There is currently no option to limit the number of in-flight messages in librdkafka.

**Comment by fsaintjacques** [comment]
The only way you can ensure ordering is with a topic of only one partition and a blocking producer, i.e. don't send message `m+1` until ack is received for message `m`. If your volume is low, you shouldn't have problem.

**Comment by edenhill** [comment]
Here is an example how to implement a sync/blocking producer on top of librdkafka:
https://github.com/edenhill/librdkafka/wiki/Sync-producer

**Comment by rathdeep** [comment]
sending one message at a time is too slow. Thanks for your inputs. 
Hope client will be informed of such errors/retry by librdkafka.

I have configured both rd_kafka_set_logger and rd_kafka_conf_set_error_cb.
Also in normal success scenario,  rd_kafka_set_logger and rd_kafka_set_log_level(rk, LOG_DEBUG);  does see any info/debug statements.

**Comment by edenhill** [comment]
Final/permanent errors are reported through the delivery report callback, but retries currently are not.
There was some discussion here on adding callbacks for when retries were made, see here:
https://github.com/edenhill/librdkafka/issues/204#issuecomment-147142517

**Comment by rathdeep** [comment]
Thanks. How does rd_kafka_set_logger differs from rd_kafka_conf_set_error_cb. I assume, if i want to receive only failure messages,  rd_kafka_conf_set_error_cb should suffice.

**Comment by edenhill** [comment]
The logger is for log and debug messages while the error_cb is for more precise error signaling.
But if no error_cb is set librdkafka will convert errors to log messages internally.

But none of those are used for message delivery reporting, that's what the dr_cb is for (or dr_msg_cb which is richer).
You can configure `delivery.report.only.error=true` if you only want delivery reports for failed messages.

**Comment by fsaintjacques** [comment]
That's a good question, I believe the doc is a bit unclear at what are the differences between dr_cb and dr_msg_cb. I myself struggled with this (and still couldn't answer!)

**Comment by edenhill** [comment]
dr_msg_cb provides a richer interface, i.e., more information through the rd_kafka_message_t object.
There is no upside to using dr_cb
