### ISSUE TITLE
PARTITION_EOF

### ISSUE THREAD

**Issue by incessantier** [edenhill/librdkafka#420]
When a consumer reaches the partition_eof, does the API automatically wrap back to the start of the partition, or do I need to do that myself?

**Comment by edenhill** [comment]
You wouldn't want it to wrap back and start over each time it reaches the end.
All it does is back off for `fetch.error.backoff.ms` before trying to fetch messages at the last offset again.
If new messages have been produced then those will be fetched, otherwise it will back off again and try again.

**Comment by incessantier** [comment]
ok, thanks

**Comment by incessantier** [comment]
Is the message payload "good" when the err is ERR__PARTITION_EOF (i.e. is it the last message on the partition), then?

**Comment by edenhill** [comment]
No, there is only a proper message payload when err == 0.
If err != 0 and payload is non-NULL then payload contains an error string.
