### ISSUE TITLE
Can I remove message in producer queue which is not delivered correctly?

### ISSUE THREAD

**Issue by wbtwins** [edenhill/librdkafka#426]
hi,edenhill

I use rd_produce_new to make new message and push it into producer queue. the dr_cb would tell me the delivery report for the message when I use rd_rdkafka_poll. If everything goes well,I can get delivery report. there were some exception during the delivery process,the message is not delivered correctly.

But consider following senario:

Client call rd_producer_new repeatly to send many messages to kafka server. If connection with server went down,the messages would not be delivered correctly.But these messages are still in queue.If connection restore,the messages would be sent out. 

 Is there any way to delete the message in quene which is failed to delivered? 

Thanks in advance!

**Comment by edenhill** [comment]
There is currently no way to explicitly delete the messages waiting in the producer queue, but you could decrease the message.timeout.ms value to speed up their expiration.

**Comment by wbtwins** [comment]
Thanks for your info.
Message.timeout.ms is a global configuration.If decrease it ,that would be speed up whole messages in queue to their expiration. Considering that  many message with different size,some would cost much time to deliver,and some would be sent out as fast as possible.
In this case,I think it may have chance to lost message in quenue which is not delivered timely

**Comment by edenhill** [comment]
I suggest you measure your typical message delivery times and then find a good value for message timeouts well above that to cater for network hickups and such.

To turn the reasoning around; if there was a way to purge the send queue; when would you do it? As soon as a broker goes down? But broker connections can be reset just intermittenly and be quickly restored, you dont want to fail messages just because of that. So then you probably want a timeout; if broker is down for more than X seconds then purge message queue.

And when you come to that realization you can simplify your approach by just using `message.timeout.ms` directly.

librdkafka really tries to abstract as many problems as possible and tries to boil it down to what these things typically are about: How long will we try to deliver a message? Specific errors are just a subset of that question.

**Comment by edenhill** [comment]
#990
