### ISSUE TITLE
questions on examples

### ISSUE THREAD

**Issue by microwish** [edenhill/librdkafka#460]
I found some new changes:

1) The implementation of consumers in rdkafka_consumer_example.c is different with that in rdkafka_example.c and rdkafka_performance.c.
2) The default value of offset.store.method is changed from file to broker.

However, in the old examples (rdkafka_example.c and rdkafka_performance.c), no "group.id" is set for consumers so that it is not workable. Correct?

**Comment by edenhill** [comment]
1) rdkafka_example and rdkafka_performance uses the legacy simple consumer interface, while rdkafka_consumer_example uses the new high-level KafkaConsumer interface. The legacy consumer doesn't make use of a group.id since there are no consumer groups, just a single uncoordinated consumer.
2) Yes, with the addition of the new high-level KafkaConsumer the offset.store.method default was changed.

**Comment by microwish** [comment]
OK, got it. Thanks a lot.
