### ISSUE TITLE
Non-blocking variants of list_groups and position

### ISSUE THREAD

**Issue by ah-** [edenhill/librdkafka#490]
It would be really useful to have non-blocking variants of those.

.net has really nice async apis, and I would love to use those in the rdkafka-dotnet API without having to mess around with blocking calls.

Something like the rd_kafka_produce API would be perfect, you kick off the operation and pass in an opaque pointer for state tracking, and then later you get a callback in rd_kafka_poll with the result or a timeout.

**Comment by ah-** [comment]
Also, it would be nice to be able to pass in an opaque to rd_kafka_commit, otherwise I can't track multiple async in flight commits.

**Comment by edenhill** [comment]
I'm happy to hear your interest in async calls since this was the plan all along, but shortage of time pushed them forward a bit.

There are two ways to go about this:
 * Serve callbacks from rd_kafka_poll()
 * Serve callbacks from arbitrary queue_t

The latter is more flexible since it works for both cases, it can use a long-living global queue, or a short-lived queue just for this particular call.
E.g.:
````
  rd_kafka_queue_t *tmpq;

  tmpq = rd_kafka_queue_new();

  err = rd_kafka_position_callback(rk, partitions, tmpq, my_cb, some_opaque);
  if (err) {
     immediate error;
     return;
  }

 rd_kafka_queue_serve(tmpq, 5000 /* 5s */);

 rd_kafka_queue_destroy(tmpq); 
}

static void my_cb (rd_kafka_t *rk, .. partitions, .. opaque) {
..
}
````

This is actually exactly what it looks like under the hood:
https://github.com/edenhill/librdkafka/blob/master/src/rdkafka.c#L1640

**Comment by ah-** [comment]
No worries, I can live with the blocking ones for now and I'm far from actually needing them async for performance reasons.

I think the global rd_kafka_poll callback queue is rather nice for things that shouldn't cause any blocking on the app side (i.e. one hopefully wouldn't start doing a lot of work in a commit callback), because it's so simple. Have one thread consuming that so you get log messages and things immediately and do all the heavy message processing in another.

More control over queues would be nice for subscribing to multiple topics. If you want to subscribe to a bunch of low-troughput topics you could just handle all of them via one queue on a single thread, if you want to subscribe to 10 heavy ones you could handle each one in a thread.

Is there a way to get a non-blocking/multiplexed dequeue? Could I have 10 threads serving 20 queues, each doing work as messages arrive?
