### ISSUE TITLE
Request: support for LZ4 compression codec

### ISSUE THREAD

**Issue by agboom** [edenhill/librdkafka#507]
As the title says. I like the `kafkacat` tool and use it for my daily kafka needs, but I'm hitting a wall since we've moved to LZ4, so support for that compression codec would be nice.

**Comment by ah-** [comment]
Should be very straightforward, I've use lz4 before and it would be easy to integrate I think.

**Comment by edenhill** [comment]
I've got a patch in the works

**Comment by edenhill** [comment]
Turned out to be a bit messy because the broker has a bug in its LZ4 framing implementation which means we'll have to meddle with the framing header after/before liblz4 is done with it.

I've got a patch in the works for the broker which keeps the existing broken lz4 framing (since it needs to be compatible with messages already produced), but adds a new compression.type "lz4f" that has the proper LZ4F framing.

**Comment by edenhill** [comment]
The WIP LZ4 implementation for librdkafka is on the lz4 branch and should be ready for testing on existing (broken) brokers given you are using compression.codec="lz4" in librdkafka.

**Comment by agboom** [comment]
Thanks for the update. I will try it as soon as I get the source to build (see #520)

**Comment by agboom** [comment]
It looks like it's working. When using `kafkacat` the LZ4 hexdump is printed. I assume that's some temporary debug log for testing purposes in `librdkafka` ([here](https://github.com/edenhill/librdkafka/blob/lz4/src/rdkafka_broker.c#L1881))

**Comment by edenhill** [comment]
This is cleaned up now and supports KIP-57:
https://cwiki.apache.org/confluence/display/KAFKA/KIP-57+-+Interoperable+LZ4+Framing

But I'll wait merging this until after the next release.

**Comment by edenhill** [comment]
Fixed on master, please give it a go.
