### ISSUE TITLE
librdkafka c++ consumer reports end of partition when read in batch with sleep/timer on 5-10 seconds

### ISSUE THREAD

**Issue by mazharshaikh86** [edenhill/librdkafka#524]
Hi Magnus,

I have a problem while reading from librdkafka CPP Consumer in a batch of 5 msgs.

the code will look as below.

void Consumer()
{
    UInt32 nbatchCount  = 5;
    while(nbatchCount--)
    {       

        RdKafka::Message *msg = m_pConsumer->consume(m_pTopicHandler, m_nKafkaPartition,m_nKafkaConsumerTimeout);

        switch (message->err())
        {
            case RdKafka::ERR__TIMED_OUT:
            {
                cout<<"timedout"<<endl;
                startTimer();
                return;
            }
        
            case RdKafka::ERR_NO_ERROR:
            {
                cout << "Offset = "<<message->offset()<<endl;
                break;
            }
        
            case RdKafka::ERR__PARTITION_EOF:
            {
                cout<<"eof"<<endl;
                startTimer();
                return;
            }
        
            default:
            {
                cout<<"default"<<endl;
                startTimer();
                return;
            }
        }
 
        delete msg;
    }
  
    startTimer();
}

viod startTimer()
{
    int delay = 5; // 5 sec
    timerCallBack(Consumer, delay);
}

Here The idea is to read 5 msg in a batch and to sleep/timer of 5 seconds.
Now, the producer is sending 2 msg at every 1 seconds (this can be confirmed by "bin/kafka-console-consumer.sh --zookeeper localhost:2181 --topic topic1")

Now, In 1st Batch the consumer reads 2 msg and reports "ERR__PARTITION_EOF" and timer is started for 5 sec.

But, when the 2nd Batch of consume function is started. the librdkafka provides only 2 msg and reports "ERR__PARTITION_EOF", instead of reading all the new msg from kafka broker which contains a minimum of 4 seconds data (4*2 = 8 msgs).

How can I solve this issue.

Is there any configuration which can be used to let librdkafka consumer fetch all the msg from broker.

Requesting your help on this.

Thanks & Regards,
Mazhar

**Comment by edenhill** [comment]
librdkafka fetches messages from the broker to a local queue of fetched messages (the fetchq).
When you call consume() all it does is read messages from that local queue.
In the background librdkafka keeps track of how large the fetchq is and stops fetching new messages from the broker if `queued.max.messages.kbytes` is reached while striving to have at least `queued.min.messages` messages queued.

Whenever the fetcher reaches the end of the partition it enqueues a PARTITION_EOF message on the local queue, backs off a short while (`fetch.error.backoff.ms`)  and then continues fetching messages for that partition.
What this means is that the local fetchq can look something like:
`msg1 msg2 ..3 EOF 4 5 6 7 8 EOF 9 10 EOF`

The PARTITION_EOF event is strictly informational and the application should typically not do anything with it. It exists for applications such as kafkacat that should read to the end of the partition and then exit, in a best effort manner. (Since the end of a partition is a moving target).

Btw, what is the reason you want to sleep 5 seconds after every 5 messages?

**Comment by mazharshaikh86** [comment]
Thanks Magnus.
with 5 sec timer, I'm trying to achieve non blocking mechanism.
