### ISSUE TITLE
Change default partitioner to consistent?

### ISSUE THREAD

**Issue by sczizzo** [edenhill/librdkafka#546]
More of an open question, but wondering what you think about changing the default partitioner to _consistent_ by default. I'll admit the default _random_ partitioner caught me a bit off guard: After reading the Kafka docs, I figured messages with the same key would be assigned to the same topic, which is the default behavior in the JVM implementation.

Now setting the partitioner is not difficult in C, so I understand this isn't an issue with `librdkafka` per se, but I've been using the library through [HaskaKafka](https://github.com/cosbynator/haskakafka), which doesn't have a direct mechanism for this AFAICT. I have contacted the maintainer there about exposing this ([HaskaKafka Issue #17](https://github.com/cosbynator/haskakafka/issues/17))

**Comment by edenhill** [comment]
That is a good idea, the problem is changing default behaviour for existing applications, we dont want to break things in obscure ways for people.

Having said that the upcomimng 0.9.1 release is the first formal 0.9 release with a wide range of new improvements and modifications so we could probably get away with changing the default partitioner too.

**Comment by ah-** [comment]
+1 for useful defaults.
