### ISSUE TITLE
Why is rd_kafka_toppar_producer_serve called 10/sec?

### ISSUE THREAD

**Issue by MaximGurschi** [edenhill/librdkafka#647]
I noticed this while using the .NET wrapper if i have the maximum debug level set on a producer, then i notice that this is called in librdkafka:

`rd_rkb_dbg(rkb, QUEUE, "TOPPAR",
                   "%.*s [%"PRId32"] %i+%i msgs",...`

, 10 times per second. 

Example output is:
rdkafka#producer-1|7|TOPPAR|_some machine_:9092/1: MyTopic [0] 0+0 msgs

Not a problem per se - the producer does not generate network traffic as no messages are produced. I thought that increasing "queue.buffering.max.ms" would affect this frequency but it does not. Can you please shed some light onto the reason this is continuously called 10/sec?

**Comment by edenhill** [comment]
This is how often it checks the internal produce queue for new messages to transmit.
The interval is based on `socket.blocking.max.ms`

**Comment by MaximGurschi** [comment]
I see. But then what is the difference between:
queue.buffering.max.ms
and
socket.blocking.max.ms

Reading the description of both i would think that the former is the one that controls this behaviour.

**Comment by edenhill** [comment]
`queue.buffering.max.ms` is how long the producer will wait for more messages before sending a messageset/batch to the broker.

`socket.blocking.max.ms` controls how long the broker thread(s) may stall on IO (POLLIN), while they are waiting on IO they cannot serve the internal producer queue, thus this property controls the internal latency of librdkafka.
And yes, this is a problem, and yes, it will be fixed in some future version :)

**Comment by MaximGurschi** [comment]
Understood. Thank you!
