### ISSUE TITLE
stats not reported when falling behind

### ISSUE THREAD

**Issue by shanson7** [edenhill/librdkafka#657]
Description
===========
We are using the cpp API, and we install our event_cb and try to use the stats element to report when consumer lag is growing. We set the report milliseconds to 10,000. This seems to work great until we actually start to lag, at which point we stop receiving the callbacks.

Is there some additional call we should make other than 'consume'?

How to reproduce
================
Consuming like this:
```
while (d_running) {
        MessagePtr message(d_kafkaConsumer->consume(1000));
...
}
```

Checklist
=========
Please provide the following information (if applicable):

 - [x] librdkafka version (release number or git tag): master
 - [x] Apache Kafka version: 0.9.0
 - [ ] librdkafka client configuration:
 - [ ] Using the legacy Consumer
 - [x] Using the high-level KafkaConsumer
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by shanson7** [comment]
Additional information: After letting it run for 30 minutes (the whole time it was processing lots and lots of messages) the stats callback was called 103 times in 1 second.

**Comment by edenhill** [comment]
Interesting.
Is the lag caused by slow processing on your side or is it due to librdkafka?

**Comment by shanson7** [comment]
I don't think so. We process several hundred thousand messages between calls, meaning we call 'consume' quite a lot. I'm not sure where to look to determine the issue. 

It seems like every 15-25 minutes all of the callbacks trigger at once. Is there something I can call from a separate thread (not my main processing thread) that can trigger the callbacks more reliably?

**Comment by edenhill** [comment]
Ah, okay, so the KafkaConsumer inserts all fetched messages from all consumed partitions, as well as librdkafka events, into the queue served by consume().
So the queue looks something like this:
`  [N msgs] [some event] [N msgs] [stats callback] [N msgs] [stats callback] ... `

If your application processes messages slowly the events and callbacks will be stuck in the queue until your application reaches that point in the queue.

The number of queued messages on this queue is controlled by `queued.min.messages` which is global  (contrary to the docs) when using KafkaConsumer.

If your processing speed is determined by message size rather than message count you might also want to decrease `queued.max.message.kbytes`.

Try playing around with these values to see if it improves the situation, the above queue length and size is indicated by the per-partition (but the value is global..) `fetchq_size` and `fetchq_cnt` in stats.

A "fix" for this issue might be to prepend non-message events/callbacks to the head of the queue, but this needs some thinking-through to avoid event reordering, etc.

**Comment by shanson7** [comment]
Ah, that makes sense. 

So, if the default value is 100k and there are 200 partitions, then 200*100k = 20 million messages need to be processed before we will start getting the callbacks? 

Is there a significant performance impact to dropping `queued.max.message.kbytes` down to, say 1k.

**Comment by edenhill** [comment]
When using the high-level KafkaConsumer all partition queues are directed/forwarded to a single consumer queue, so in this case those two conf settings applies to that queue in its entirety rather than per partition. I.e., if you set it to 100k messages it will be limited 100k regardless of the number of partitions. This might change some time in the future to reinstate the per-partition behaviour.

The point of librdkafka's local fetch queue is to avoid the extra round-trip time to fetch new messages when the application is done processing the previously fetched messages. The idea is that the application should never have to wait for a new message when calling consume(), it should already have been fetched. You will need to find a good setting for the `queued.min.messages` setting that works for you using either testing or back-of-envelope calculations (the broker round trip time is useful, try debug=protocol or look at the rtt stats).

**Comment by shanson7** [comment]
That all makes sense to me, but I'm still a little stymied by this callback. 

I verified that I'm handling 1200 messages per second (avg, +/- 50). 

I set `queued.min.messages = 1500` and `statistivs.interval.ms = 15000`, yet it still took around 4 minutes for the stats callback to be called (at which point it was called multiple times in quick succession).

My understanding is that rdkafka should be keeping ~1500 messages in this queue (possibly a little bit more).  But we are processing several hundred thousand messages before we see this callback.

My next question is "What constitutes a message?". In my terminology, a message is the single JSON object that I put into rdkafka via a separate producer. Is a message in rdkafka terms a large chunk of these (i.e. the response from kafka)?

**Comment by shanson7** [comment]
I think this is related to my values for `fetch.message.max.bytes`. This causes the queue to automatically be huuuuge after a single fetch.

**Comment by edenhill** [comment]
> My next question is "What constitutes a message?". In my terminology, a message is the single JSON object that I put into rdkafka via a separate producer. Is a message in rdkafka terms a large chunk of these (i.e. the response from kafka)?

A message is a message as you produce it no more no less. But you are right that a large `fetch.message.max.bytes` supercedes the `queued.min.messages`.

You can look at the process of how librdkafka decides if a partition should be fetched or not here:
https://github.com/edenhill/librdkafka/blob/master/src/rdkafka_partition.c#L1433

**Comment by shanson7** [comment]
Well goldarnit, that was it. dropped that to 10kb and the stats callbacks started showing up like clockwork. You were right, I'll mess around with those settings. 

Thanks so much for your help!!

**Comment by edenhill** [comment]
Great!
