### ISSUE TITLE
RdKafka::Conf::create not detecting all errors

### ISSUE THREAD

**Issue by oregonduckman** [edenhill/librdkafka#746]
Description
===========
RdKafka::Conf::create does not return errors for some properties

How to reproduce
================
set("metadata.broker.list" with an invalid broker address and no error is returned.

Checklist
=========
Please provide the following information:

 - [x] librdkafka version (release number or git tag):
 - [ ] Apache Kafka version: 
 - [ ] librdkafka client configuration:
 - [ ] Operating system:
 - [ ] Using the legacy Consumer
 - [ ] Using the high-level KafkaConsumer
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
What is an invalid broker address? Bad address format or something that doesnt resolve?

**Comment by oregonduckman** [comment]
Something that doesn't resolve. Say “0,0,0,0::0”. It seems that if a bad broker address is set then RDKafka does not see the error until a consume or produce occurs. I thought that the set function would return an error…

**Comment by edenhill** [comment]
librdkafka will not validate address resolution during configuration since those errors might be temporary and the initilization of the library should not depend on DNS connectivity.
As soon as the address resolves librdkafka will connect to the broker and resume operation.

In the case where all provided bootstrap brokers are bad (failure to resolve, failure to connect, fail to auth) librdkafka will emit the _ALL_BROKERS_DOWN event which an application can use to terminate.

**Comment by edenhill** [comment]
"0,0,0,0::0" is a valid address (0, which is the same as local host), while the port (0) is invalid.
librdkafka does not currently verify the address or port syntax during configuration.
