### ISSUE TITLE
FD based polling with librdkafka ?

### ISSUE THREAD

**Issue by fishelson** [edenhill/librdkafka#749]
Hi, Is there a way we can do fd based polling with librdkafka. In my usecase, we need the consumer to read a message when a new message arrives. I see rd_kafka_transport_connect storing some fd. Can we utilize them?

**Comment by edenhill** [comment]
I guess you want to incorporate librdkafka in an IO-based event loop dispatcher?

This is currently not possible and even if you managed to extract the fd (which is local to internal librdkafka threads...) a POLLIN event would not necessarily indicate message availability since other communication takes places on the same socket (heartbeats, commits, metadatarequest, empty fetch responses, etc).

If you cannot mix your IO-based event loop with librdkafka's consume() or poll() API, which admittedly is a hard thing to do, your best bet is to create a separate thread that consumes/polls librdkafka and then communicate with your IO-poller thread through a standard unix pipe.

**Comment by fishelson** [comment]
Thanks, yes we have an IO-based event loop dispatcher. We have decided to create another thread that will poll Kafka and send notification.

**Comment by fishelson** [comment]
Is there a way to just poll Kafka without consuming message. Basically, how to utilize the rd_kafka_consumer_poll API?

**Comment by edenhill** [comment]
What do you mean by polling Kafka? Just check if there are any messages?

**Comment by fishelson** [comment]
yes, check if there are any new messages.

**Comment by edenhill** [comment]
I see, that's unfortunately not currently possible.

What would you like that API to look like?

**Comment by edenhill** [comment]
I've added an experimental API (subject to change) that allows an application to set up an FD that librdkafka will write to whenever a queue goes from 0 to >0 messages.

See `rd_kafka_queue_io_event_enable()` in rdkafka.h on `events_api` branch.

There's also an example in tests/0040-io_event.c that shows how it can be used (the use of events rather than callbacks is optional though..)

Please try it out and comment.

**Comment by edenhill** [comment]
Ping @webmakersteve, this might be of interest to you guys.

**Comment by webmakersteve** [comment]
Definitely an interesting addition. We're generally consuming thousands of messages per second on a pretty consistent basis, so we call consume/produce (which implicitly, in our case, calls `poll`) enough to get the events we need without needing a separate polling thread. But i can see some cases in which it would be useful. Thanks for the tag!

**Comment by mfs-git** [comment]
Is there any way to get i/o event per message? (not just when q size increases from 0)
I have kafka consumer, zmq pull and some other input sockets, and i want to read from these sockets fairly, with provided interface ( rd_kafka_queue_io_event_enable() ) it could lead to stravation in other inputs.

**Comment by edenhill** [comment]
@mfs-git That's not currently possible and there are no plans to provide level-triggered FD signalling, you'll have to adapt to the edge-triggered signalling.
I.e., if you get an FD event you should read as many messages/events as possible until it returns empty, at which point the queue is empty. Go back to waiting for FD events.
