### ISSUE TITLE
Async Producer

### ISSUE THREAD

**Issue by fishelson** [edenhill/librdkafka#780]
For Kafka producers, it appears that the following blocking call is required

 /* 1) Make sure all outstanding requests are transmitted and handled. */
     while (rd_kafka_outq_len(rk) > 0)
         rd_kafka_poll(rk, 50);

So while produce requests are asynchronous , we still need this call after requests. Is there some way we can relegate this call to background threads? If that is not possible, is there some property, which can help in safely timing out ?

**Comment by edenhill** [comment]
While it may seem practical to have spontanous callbacks on background threads librdkafka chooses the explicit poll() approach instead to avoid having the app developer need to understand and take threading into consideration (calling user callbacks on internal librdkafka threads requires a proper concurrency design of the app).

What do you mean by "safely timing out"? Do you want to flush the messages waiting delivery instead of waiting for them to finish?

**Comment by fishelson** [comment]
Yes, I mean, this may take sometime,

while (rd_kafka_outq_len(rk) > 0)
           rd_kafka_poll(rk, 50);

so if we call it once for 1st message
rd_kafka_poll(rk, 50);

and if the application calls it again for 2nd message,
will the 1st delivery report be also displayed (if it is not able to do it within the time quanta) ?

**Comment by edenhill** [comment]
poll will serve the dr callbacks for all delivered messages that have not yet had their dr callback called.

In other words: the dr callback will only be called once per message.
outq_len() returns the number of messages waiting to be produced + number of messages waiting to have their dr callback called
