### ISSUE TITLE
Consumer callback issue

### ISSUE THREAD

**Issue by jupiterh** [edenhill/librdkafka#832]
Description
===========
In the example of  rdkafka_example.cpp, the consumer callback using RdKafka::ConsumeCb is called inside the loop while(run), that behaviour looks like polling. I thought the mechanism for the callback in general is you should only set up / call the consumer->consume_callback(topic, partition, 1000,&ex_consume_cb, &use_ccb) once, the callback should be invoked when the data is available. But that is not what the consumer->consume_callback behaved, I tried to move the statement of consumer->consume_callback out of the while(run) loop, it called once, never received data again. Is it a bug of did I miss something here? I don't want to use polling to poll consumer data, please enlighten me how to make the consumer callback work properly.

Thank you for the excellent program.

Kind regards,

jupiter

How to reproduce
================

Run rdkafka_example_cpp with -C and -f ccb

Checklist
=========
Please provide the following information:

 - [ ] librdkafka version (release number or git tag):
 - [ ] Apache Kafka version: 
 - [ ] librdkafka client configuration:
 - [ ] Operating system:
 - [ ] Using the legacy Consumer
 - [ ] Using the high-level KafkaConsumer
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
The consume callback still needs to be triggered by something, and it needs to be called in application thread(s), not librdkafka internal threads, that's why a ..._poll() call is still necessary.

So in effect there is no real difference in calling convention between standard and callback usage, but there is a performance increase with using the callback (do note though that the standard interface is typically fast enough).
