### ISSUE TITLE
Best practice?  rd_kafka_consume_callback and balanced consumer group

### ISSUE THREAD

**Issue by dw09** [edenhill/librdkafka#992]
Not a bug, but the documentation is not so clear about this:

The documentation suggests that rd_kafka_consume_callback() is the fastest way to consume.  On the other hand, it seems to me not usable with balanced consumer groups.
Is rd_kafka_consumer_poll() the best/fastest way to go if I want balanced consumer groups?  Would there be any other way at all?

**Comment by edenhill** [comment]
You are right, consume_callback() is part of the legacy consumer API and wont work with the new high-level balanced consumer.
For that you use consumer_poll() or queue_poll() (if you've redirected partition queues), neither of them feature a callback mode.

While the callback approach is somewhat faster since there is less overhead per message, I dont really think it matters in practice, the performance different should be minimal.
