### ISSUE TITLE
Why is message modeled as a void pointer?

### ISSUE THREAD

**Issue by mcandre** [edenhill/librdkafka#995]
Curious why kafka messages are treated as `void *` rather than a `byte[]`? Does the void pointer allow for more kinds of message types to be successfully handled?

Disclaimer: I'm a novice C programmer

**Comment by edenhill** [comment]
The type of the message payload is completely opaque to librdkafka and `void *` is the common pattern to express that in C, since it removes the need for explicit casting when passing any pointer type to a `void *` interface. Also, you probably mean `char[]` (or actually `char *) rather than `byte[]` in C.
